# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Red Hat, Inc.
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# dcantrel <dcantrell@redhat.com>, 2011
# Dimitris Glezos <glezos@indifex.com>, 2011
# Hajime Taira <htaira@redhat.com>, 2013-2015
# hyuugabaru <hyu_gabaru@yahoo.co.jp>, 2007,2009
# Kenzo Moriguchi <kmoriguc@redhat.com>, 2014
# Makoto Mizukami <mmk9060@aol.com>, 2008
# Naoki Shigematsu <sigematu@linuxml.net>, 2004
# noriko <noriko@fedoraproject.org>, 2013-2014
# noriko <noriko@fedoraproject.org>, 2010,2012-2013
# SATO Satoru <ssato@redhat.com>, 2001
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2014
# Yoshinari Takaoka <mumumu@mx.edit.ne.jp>, 2004
# carrotsoft <www.carrotsoft@gmail.com>, 2012-2013
# Casey Jones <nahareport@live.com>, 2015. #zanata
# Hajime Taira <htaira@fedoraproject.org>, 2015. #zanata
# Jiro Matsuzawa <jmatsuzawa@gnome.org>, 2015. #zanata
# Noriko Mizumoto <noriko.mizumoto@gmail.com>, 2015. #zanata
# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2015. #zanata
# Aiko Sasaki <asasaki@redhat.com>, 2016. #zanata
# Noriko Mizumoto <noriko.mizumoto@gmail.com>, 2016. #zanata
# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2016. #zanata
# Takuro Nagamoto <tnagamot@redhat.com>, 2016. #zanata
# Ludek Janda <ljanda@redhat.com>, 2017. #zanata, 2021.
# Ludek Janda <ljanda@redhat.com>, 2018. #zanata, 2021.
# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2018. #zanata
# Keiko Moriguchi <kemorigu@redhat.com>, 2019. #zanata
# Hajime Taira <htaira@pantora.net>, 2021.
# Mie Yamamoto <myamamot@redhat.com>, 2024.
# Koichiro Iwao <meta@vmeta.jp>, 2024.
msgid ""
msgstr ""
"Project-Id-Version: anaconda 21.48.22.158\n"
"Report-Msgid-Bugs-To: anaconda-devel-list@redhat.com\n"
"POT-Creation-Date: 2020-04-15 15:07+0200\n"
"PO-Revision-Date: 2024-10-16 01:07+0000\n"
"Last-Translator: Koichiro Iwao <meta@vmeta.jp>\n"
"Language-Team: Japanese <https://translate.fedoraproject.org/projects/"
"anaconda/rhel-7/ja/>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Weblate 5.7.2\n"

#: pyanaconda/bootloader.py:253
msgid "/boot file system"
msgstr "/boot ファイルシステム  "

#: pyanaconda/bootloader.py:410
#, python-format
msgid ""
"RAID sets that contain '%(desc)s' must have one of the following raid "
"levels: %(raid_level)s."
msgstr "'%(desc)s' を含む RAID セットには、次の RAID レベルのいずれかが必要です: %(raid_level)s。"

#: pyanaconda/bootloader.py:418
#, python-format
msgid ""
"RAID sets that contain '%(desc)s' must have one of the following metadata "
"versions: %(metadata_versions)s."
msgstr ""
"'%(desc)s' を含む RAID セットは、次のメタデータのバージョンのいずれかが必要です: %(metadata_versions)s。"

#: pyanaconda/bootloader.py:426
#, python-format
msgid ""
"RAID sets that contain '%(desc)s' must have one of the following device "
"types: %(types)s."
msgstr "'%(desc)s' を含む RAID セットには、次のデバイスタイプのいずれかが必要です: %(types)s。"

#: pyanaconda/bootloader.py:442
#, python-format
msgid "%(name)s must have one of the following disklabel types: %(types)s."
msgstr "%(name)s には、次のディスクラベルのタイプのいずれかが必要です: %(types)s。"

#: pyanaconda/bootloader.py:454
#, python-format
msgid "%(desc)s cannot be of type %(type)s."
msgstr "%(desc)s は、%(type)s タイプにはできません。"

#: pyanaconda/bootloader.py:460
#, python-format
msgid "%(desc)s must be mounted on one of %(mountpoints)s."
msgstr "%(desc)s を %(mountpoints)s の１つにマウントする必要があります。"

#: pyanaconda/bootloader.py:472
#, python-format
msgid "%(desc)s must be between %(min)d and %(max)d MB in size"
msgstr "%(desc)s のサイズは、%(min)d MB から %(max)d MB の値でなければなりません"

#: pyanaconda/bootloader.py:478
#, python-format
msgid "%(desc)s must not be smaller than %(min)dMB."
msgstr "%(desc)sのサイズは %(min)d MB 以下でなければなりません。"

#: pyanaconda/bootloader.py:487
#, python-format
msgid "%(desc)s must not be larger than %(max)dMB."
msgstr "%(desc)s のサイズは %(max)d MB を超えてはいけません。"

#: pyanaconda/bootloader.py:505
#, python-format
msgid "%(desc)s must be within the first %(max_end)s of the disk."
msgstr "%(desc)s は、ディスク先頭の %(max_end)s 内になければなりません。"

#: pyanaconda/bootloader.py:515
#, python-format
msgid "%s must be on a primary partition."
msgstr "%s は、プライマリーパーティション上になければなりません。"

#: pyanaconda/bootloader.py:599
msgid ""
"Boot loader stage1 device cannot be on an iSCSI disk which is not configured "
"in iBFT."
msgstr ""
"ブートローダーstage1 デバイスは、iBFT に設定されていない iSCSI ディスク上に配"
"置できません。"

#: pyanaconda/bootloader.py:656 pyanaconda/bootloader.py:767
#, python-format
msgid "%s cannot be on an encrypted block device."
msgstr "%s は、暗号化ブロックデバイス上に置くことができません。"

#: pyanaconda/bootloader.py:721
#, python-format
msgid ""
"%(bootloader_stage2_description)s cannot be on an iSCSI disk which is not "
"configured in iBFT."
msgstr ""
"%(bootloader_stage2_description)s は、iBFT に設定されていない iSCSI ディスク"
"上に配置できません。"

#: pyanaconda/bootloader.py:726
#, python-format
msgid "%(desc)s cannot be of type %(type)s"
msgstr "%(desc)sは %(type)s タイプにすることはできません"

#: pyanaconda/bootloader.py:1377
#, python-format
msgid ""
"boot loader stage2 device %(stage2dev)s is on a multi-disk array, but boot "
"loader stage1 device %(stage1dev)s is not. A drive failure in %(stage2dev)s "
"could render the system unbootable."
msgstr ""
"ブートローダー stage2 デバイス %(stage2dev)s は複数ディスクアレイ上にあります"
"が、ブートローダー stage1 デバイス %(stage1dev)s はこのアレイ上にありませ"
"ん。%(stage2dev)s でドライブ障害が発生するとシステムが起動できなくなる可能性"
"があります。"

#: pyanaconda/bootloader.py:1383
#, python-format
msgid ""
"boot loader stage2 device %(stage2dev)s is on a multi-disk array, but boot "
"loader stage1 device %(stage1dev)s is not part of this array. The stage1 "
"boot loader will only be installed to a single drive."
msgstr ""
"ブートローダー stage2 デバイス %(stage2dev)s は複数ディスクアレイ上にあります"
"が、ブートローダー stage1 デバイス %(stage1dev)s はこのアレイ上にありません。"
"stage1 ブートローダーだけは単一ドライブにインストールされます。"

#: pyanaconda/bootloader.py:1676
#, python-format
msgid ""
"%(deviceName)s may not have enough space for grub2 to embed core.img when "
"using the %(fsType)s file system on %(deviceType)s"
msgstr ""
"%(deviceType)s の %(fsType)s ファイルシステムを使用する場合、grub2 によって組み込まれる core.img 用の領域が "
"%(deviceName)s には不足している可能性があります"

#: pyanaconda/constants.py:73
msgid "Start VNC"
msgstr "VNC を起動する"

#: pyanaconda/constants.py:74
msgid "Use text mode"
msgstr "テキストモードを使用する"

#: pyanaconda/constants.py:141
msgid ""
"Simultaneous Multithreading (SMT) technology can provide performance "
"improvements for certain workloads, but introduces several publicly "
"disclosed security issues. You have the option of disabling SMT, which may "
"impact performance. If you choose to leave SMT enabled, please read https://"
"red.ht/rhel-smt to understand your potential risks and learn about other "
"ways to mitigate these risks."
msgstr ""
"同時マルチスレッディング (SMT) 技術を使用すると、特定のワークロードではパ"
"フォーマンスが改善されますが、公開済みのセキュリティー問題がもたらされます。"
"SMT は無効にすることもできますが、その場合はパフォーマンスにマイナス影響が出"
"る可能性があります。SMT を有効にしておく場合は、https://red.ht/rhel-smt の"
"アーティクルで、潜在的なリスクとこれらのリスクの軽減方法を確認してください。"

#: pyanaconda/constants.py:150
msgid ""
"Simultaneous Multithreading (SMT) may improve performance for certain "
"workloads, but introduces several publicly disclosed security issues. You "
"can disable SMT, which may impact performance. Please read https://red.ht/"
"rhel-smt to understand potential risks and learn about ways to mitigate "
"these risks."
msgstr ""
"同時マルチスレッディング (SMT) を使用すると、特定のワークロードではパフォーマ"
"ンスが改善されますが、公開済みのセキュリティー問題がもたらされます。SMT は無"
"効にすることもできますが、その場合はパフォーマンスにマイナス影響が出る可能性"
"があります。潜在的なリスクとこれらのリスクの軽減方法については、https://red."
"ht/rhel-smt のアーティクルを参照してください。"

#: pyanaconda/constants.py:158
#, python-format
msgid "The %(password)s is empty."
msgstr "%(password)s は空です。"

#: pyanaconda/constants.py:159
#, python-format
msgid "The %(passwords)s do not match."
msgstr "%(passwords)s が一致しません。"

#: pyanaconda/constants.py:160
#, python-format
msgid "The %(passwords)s you entered were different.  Please try again."
msgstr "入力した %(passwords)s が違います。やり直してください。"

#: pyanaconda/constants.py:163
#, python-format
msgid "The %(password)s is too short"
msgstr "%(password)s が短すぎます"

#: pyanaconda/constants.py:164
#, python-format
msgid "The %(password)s you have provided is weak."
msgstr "入力された %(password)s では弱すぎます。"

#: pyanaconda/constants.py:165
#, python-format
msgid "The %(password)s you have provided is weak: %(error_message)s."
msgstr "入力された %(password)s では弱すぎます: %(error_message)s。"

#: pyanaconda/constants.py:166
msgid "Press Done again to use anyway."
msgstr "完了を再度押して使用します。"

#: pyanaconda/constants.py:167
#, python-format
msgid ""
"The %(password)s you have provided contains non-ASCII characters. You may "
"not be able to switch between keyboard layouts when typing it."
msgstr ""
"入力した %(password)s に ASCII 以外の文字が含まれています。入力する際、キー"
"ボードレイアウトの切り替えができない場合があります。"

#: pyanaconda/constants.py:169
msgid "You will have to press Done twice to confirm it."
msgstr "確認する場合は、完了を 2 回押す必要があります。"

#: pyanaconda/constants.py:170
msgid "Press Done to continue."
msgstr "完了を押して続けます。"

#: pyanaconda/constants.py:173
msgid "Empty"
msgstr "未入力"

#: pyanaconda/constants.py:174
msgid "Too short"
msgstr "短すぎます"

#: pyanaconda/constants.py:175
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade.h:7
msgid "Weak"
msgstr "弱い"

#: pyanaconda/constants.py:176
msgid "Fair"
msgstr "普通"

#: pyanaconda/constants.py:177
msgid "Good"
msgstr "良好"

#: pyanaconda/constants.py:178
msgid "Strong"
msgstr "強い"

#: pyanaconda/constants.py:181
msgid "password"
msgstr "パスワード"

#: pyanaconda/constants.py:182
msgid "passwords"
msgstr "パスワード"

#: pyanaconda/constants.py:185
msgid "passphrase"
msgstr "パスフレーズ"

#: pyanaconda/constants.py:186
msgid "passphrases"
msgstr "パスフレーズ"

#: pyanaconda/errors.py:109
#, python-format
msgid ""
"The following errors occurred with your partitioning:\n"
"\n"
"%(errortxt)s\n"
"\n"
"The installation will now terminate."
msgstr ""
"パーティション設定で次のエラーが発生しました。\n"
"\n"
"%(errortxt)s\n"
"\n"
"インストールを終了します。"

#: pyanaconda/errors.py:115
#, python-format
msgid "An error occurred while resizing the device %s."
msgstr "デバイス %s のサイズ変更中にエラーが発生しました。"

#: pyanaconda/errors.py:124
#, python-format
msgid ""
"There is a problem with your existing storage configuration: %(errortxt)s\n"
"\n"
"You must resolve this matter before the installation can proceed. There is a "
"shell available for use which you can access by pressing ctrl-alt-f1 and "
"then ctrl-b 2.\n"
"\n"
"Once you have resolved the issue you can retry the storage scan. If you do "
"not fix it you will have to exit the installer."
msgstr ""
"既存のストレージ構成に問題があります: %(errortxt)s\n"
"\n"
"インストールを行う前にこの問題を解決する必要があります。ctrl-alt-f1 の後に "
"ctrl-b 2 を押すとシェルにアクセスできます。\n"
"\n"
"この問題を解決してからストレージスキャンを再試行してください。問題が解決でき"
"ない場合は、インストーラーを終了しなければなりません。"

#: pyanaconda/errors.py:133 pyanaconda/ui/gui/main.glade.h:1
msgid "_Exit Installer"
msgstr "インストーラーを終了する(_E)"

#: pyanaconda/errors.py:133
msgid "_Retry"
msgstr "再試行(_R)"

#: pyanaconda/errors.py:140
msgid ""
"An error has occurred - no valid devices were found on which to create new "
"file systems.  Please check your hardware for the cause of this problem."
msgstr ""
"エラーが発生しました。新しいファイルシステムを作成する有効なデバイスが見つか"
"りませんでした。ハードウェアをチェックし、この問題の原因を調査してください。"

#: pyanaconda/errors.py:147
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Would you like to mount them anyway?\n"
"%s"
msgstr ""
"Linux システム用の、次のファイルシステムは正常にアンマウントされませんでし"
"た。とにかくそれらをマウントしますか?\n"
"%s"

#: pyanaconda/errors.py:158
msgid ""
"There is an entry in your /etc/fstab file that contains an invalid or "
"incorrect file system type:\n"
"\n"
msgstr ""
"/etc/fstab ファイルに、無効または不正なファイルシステムの種類を含むエントリー"
"があります：\n"
"\n"

#: pyanaconda/errors.py:164
#, python-format
msgid ""
"The ISO image %s has a size which is not a multiple of 2048 bytes.  This may "
"mean it was corrupted on transfer to this computer.\n"
"\n"
"It is recommended that you exit and abort your installation, but you can "
"choose to continue if you think this is in error. Would you like to continue "
"using this image?"
msgstr ""
"ISO イメージ %s のサイズは 2048 バイトの倍数になっていません。このコンピュー"
"タへの転送中にイメージが破損したことを示している可能性があります。\n"
"\n"
"インストールを終了、中止することをお勧めしますが、これが何かの間違いだと思わ"
"れる場合は、続行を選択することもできます。このイメージで続行しますか?"

#: pyanaconda/errors.py:178
msgid ""
"The installer has tried to mount the installation image, but cannot find it "
"on the hard drive.\n"
"\n"
"Should I try again to locate the image?"
msgstr ""
"インストーラーによりインストールイメージのマウントが試行されましたが、ハード"
"ドライブ上にイメージが見つかりません。\n"
"\n"
"イメージの検索をやり直しますか?"

#: pyanaconda/errors.py:188
#, python-format
msgid "An error occurred mounting the source device %s. Retry?"
msgstr "ソースデバイス %s のマウント中にエラーが発生しました。やり直しますか?"

#: pyanaconda/errors.py:196
#, python-format
msgid ""
"An error occurred unmounting the disc.  Please make sure you're not "
"accessing %s from the shell on tty2 and then click OK to retry."
msgstr ""
"ディスクのアンマウント時にエラーが発生しました。tty2 上でシェルから %s へのア"
"クセスを行っていないことを確認してから OK をクリックし再試行します。"

#: pyanaconda/errors.py:204
#, python-format
msgid ""
"The group '%s' is required for this installation. This group does not exist. "
"This is a fatal error and installation will be aborted."
msgstr ""
"このインストールにはグループ '%s' が必要ですが、存在していません。致命的なエ"
"ラーのため、インストールは中止されます。"

#: pyanaconda/errors.py:210
#, python-format
msgid ""
"You have specified that the group '%s' should be installed.  This group does "
"not exist.  Would you like to ignore this group and continue with "
"installation?"
msgstr ""
"グループ '%s' をインストールするように指定されていますが、このグループは存在"
"していません。このグループを省略してインストールを続行しますか?"

#: pyanaconda/errors.py:215
#, python-format
msgid ""
"You have specified that the group '%s' should be excluded from "
"installation.  This group does not exist.  Would you like to ignore this "
"group and continue with installation?"
msgstr ""
"グループ '%s' をインストールから除外するように指定されていますが、このグルー"
"プは存在していません。このグループを省略してインストールを続行しますか?"

#: pyanaconda/errors.py:227
#, python-format
msgid ""
"The package '%s' is required for this installation. This package does not "
"exist. This is a fatal error and installation will be aborted."
msgstr ""
"このインストールにはパッケージ '%s' が必要ですが、存在していません。致命的な"
"エラーのため、インストールは中止されます。"

#: pyanaconda/errors.py:234
#, python-format
msgid ""
"You have specified that the package '%s' should be installed.  This package "
"does not exist.  Would you like to ignore this package and continue with "
"installation?"
msgstr ""
"パッケージ '%s' をインストールするように指定されていますが、このパッケージは"
"存在していません。このパッケージを省略してインストールを続行しますか?"

#: pyanaconda/errors.py:245
#, python-format
msgid ""
"There was an error running the kickstart script at line %(lineno)s.  This is "
"a fatal error and installation will be aborted.  The details of this error "
"are:\n"
"\n"
"%(details)s"
msgstr ""
"Kickstart ファイル中のスクリプトの %(lineno)s "
"行目の実行中にエラーが発生しました。致命的なエラーとなるためインストールを中止します。このエラーの詳細は次のとおりです。\n"
"\n"
"%(details)s"

#: pyanaconda/errors.py:253
msgid ""
"The following error occurred while installing.  This is a fatal error and "
"installation will be aborted."
msgstr ""
"インストール中に次のエラーが発生しました。致命的なエラーとなるため、インス"
"トールを中止します。"

#: pyanaconda/errors.py:261
msgid ""
"The following software marked for installation has errors.  This is likely "
"caused by an error with\n"
"your installation source."
msgstr ""
"インストールの印が付いた以下のソフトウェアにエラーが発生しました。インストー"
"ル\n"
"ソースでのエラーが原因となっている可能性が高いと思われます。"

#: pyanaconda/errors.py:269
msgid ""
"The following error occurred while installing the boot loader. The system "
"will not be bootable. Would you like to ignore this and continue with "
"installation?"
msgstr ""
"ブートローダーのインストール中に以下のエラーが発生しました。システムが起動で"
"きなくなります。エラーを無視してインストールを続行しますか？"

#: pyanaconda/errors.py:282
#, python-format
msgid ""
"Installation was stopped due to an error installing the boot loader. The "
"exact error message is:\n"
"\n"
"%s\n"
"\n"
"The installer will now terminate."
msgstr ""
"ブートローダーのインストール時に問題があると思われる症状が発生したため、イン"
"ストール作業が停止しました。エラーメッセージは次のとおりです。\n"
"\n"
"%s\n"
"\n"
" インストーラーを終了します。"

#: pyanaconda/errors.py:290
#, python-format
msgid "Unable to encrypt password: unsupported algorithm %s"
msgstr "パスワードを暗号化できません: サポートされていないアルゴリズム %s "

#: pyanaconda/exception.py:104
#, python-format
msgid ""
"The installation was stopped due to what seems to be a problem with your "
"hardware. The exact error message is:\n"
"\n"
"%s.\n"
"\n"
" The installer will now terminate."
msgstr ""
"インストール作業は、ハードウェアに問題があると思われる症状が発生したため停止"
"されました。エラーメッセージは次のとおりです。\n"
"\n"
"%s\n"
"\n"
" インストーラーを終了します。"

#: pyanaconda/exception.py:108
msgid "Hardware error occurred"
msgstr "ハードウェアのエラーが発生しました"

#: pyanaconda/exception.py:143
#, python-format
msgid ""
"\n"
"The installation was stopped due to an error which occurred while running in "
"non-interactive cmdline mode. Since there cannot be any questions in cmdline "
"mode, edit your kickstart file and retry installation. \n"
"The exact error message is: \n"
"\n"
"%s. \n"
"\n"
"The installer will now terminate."
msgstr ""
"\n"
"インストール作業は非対話型コマンドラインモードでエラーが発生したため停止されました。Kickstart "
"ファイルを編集し、再度インストールを試行してください。\n"
"正確なエラーメッセージは次のとおりです:\n"
"\n"
"%s\n"
"\n"
"インストーラーを終了します。"

#: pyanaconda/exception.py:151
#, python-format
msgid ""
"\n"
"Running in cmdline mode, no interactive debugging allowed.\n"
"The exact error message is: \n"
"\n"
"%s.\n"
"\n"
"The installer will now terminate."
msgstr ""
"\n"
"コマンドラインモードでの実行中に、対話型のデバッグ機能は利用できません。\n"
"エラーメッセージは次のとおりです。\n"
"\n"
"%s\n"
"\n"
" インストーラーを終了します。"

#: pyanaconda/install.py:83
msgid "Configuring installed system"
msgstr "インストール済みのシステムを構成"

#: pyanaconda/install.py:96
msgid "Writing network configuration"
msgstr "ネットワーク構成を書き込み中"

#: pyanaconda/install.py:100
msgid "Creating users"
msgstr "ユーザーを作成中"

#: pyanaconda/install.py:108
msgid "Configuring addons"
msgstr "アドオンを設定中"

#: pyanaconda/install.py:111
msgid "Generating initramfs"
msgstr "initramfs を生成中"

#: pyanaconda/install.py:115
#, python-format
msgid "Joining realm: %s"
msgstr "レルムに参加中: %s"

#: pyanaconda/install.py:118
msgid "Running post-installation scripts"
msgstr "ポストインストールのスクリプトを実行中"

#: pyanaconda/install.py:139
msgid "Creating snapshots"
msgstr "スナップショットを作成中"

#: pyanaconda/install.py:178
#, python-format
msgid "Waiting for %s threads to finish"
msgstr "%s つのスレッドが完了するまで待機中"

#: pyanaconda/install.py:184
msgid "Setting up the installation environment"
msgstr "インストール環境をセットアップ中"

#: pyanaconda/install.py:213 pyanaconda/kickstart.py:2485
msgid "Running pre-installation scripts"
msgstr "インストール前スクリプトを実行中"

#: pyanaconda/install.py:221
msgid "Discovering realm to join"
msgstr "参加するレルムを探索中"

#: pyanaconda/install.py:265
msgid "Installing boot loader"
msgstr "ブートローダーをインストール中"

#: pyanaconda/install.py:268 pyanaconda/packaging/livepayload.py:170
#: pyanaconda/packaging/yumpayload.py:1555
msgid "Performing post-installation setup tasks"
msgstr "インストール後セットアップ作業を実行中"

#: pyanaconda/iutil.py:789
msgid "No host url"
msgstr "ホスト URL がありません"

#: pyanaconda/iutil.py:810
msgid "malformed URL, cannot parse it."
msgstr "不正な形式の URL、こちらは解釈できません。"

#: pyanaconda/iutil.py:826
msgid "URL has no host component"
msgstr "URL にホストが含まれていません"

#: pyanaconda/kickstart.py:191
#, python-format
msgid "Escrow certificate %s requires the network."
msgstr "エスクロー証明書 %s にはネットワークが必要です。"

#: pyanaconda/kickstart.py:199
#, python-format
msgid ""
"The following error was encountered while downloading the escrow "
"certificate:\n"
"\n"
"%s"
msgstr ""
"escrow 証明書のダウンロード中に次のエラーに遭いました。\n"
"\n"
"%s"

#: pyanaconda/kickstart.py:273
#, python-format
msgid "%s is missing. Cannot setup authentication."
msgstr "%s が足りません。 認証の設定ができません。"

#: pyanaconda/kickstart.py:298
#, python-format
msgid "autopart fstype of %s is invalid."
msgstr "%s は、autopart で設定するファイルシステムタイプとして無効です。"

#: pyanaconda/kickstart.py:342
msgid "GRUB2 does not support installation to a partition."
msgstr "GRUB2 は、パーティションへのインストールをサポートしていません。"

#: pyanaconda/kickstart.py:435
#, python-format
msgid "More than one match found for given boot drive \"%s\"."
msgstr ""
"与えられたブートディスク \"%s\" と一致するディスクが複数見つかりました。"

#: pyanaconda/kickstart.py:440
#, python-format
msgid "Requested boot drive \"%s\" doesn't exist or cannot be used."
msgstr "要求されたブートディスク \"%s\" は存在しないか、使用できません。"

#: pyanaconda/kickstart.py:514
#, python-format
msgid ""
"Btrfs partition \"%(device)s\" has a format of \"%(format)s\", but should "
"have a format of \"Btrfs\"."
msgstr ""
"Btrfs パーティション \"%(device)s\" が、\"%(format)s\" の形式になっていま"
"す。\"Btrfs\" 形式に修正してください。"

#: pyanaconda/kickstart.py:519
#, python-format
msgid "Tried to use undefined partition \"%s\" in Btrfs volume specification."
msgstr ""
"未定義のパーティション \"%s\" を BTRFS ボリューム仕様で使用しようとしました。"

#: pyanaconda/kickstart.py:532
msgid ""
"Btrfs volume defined without any member devices.  Either specify member "
"devices or use --useexisting."
msgstr ""
"BTRF ボリュームにメンバーデバイスが定義されていません。メンバーデバイスを指定"
"するか、--useexisting を使用してください。"

#: pyanaconda/kickstart.py:541 pyanaconda/kickstart.py:928
#: pyanaconda/kickstart.py:1593
#, python-format
msgid "The mount point \"%s\" is not valid.  It must start with a /."
msgstr "\"%s\" は無効なマウントポイントです。/ で開始してください。"

#: pyanaconda/kickstart.py:556
#, python-format
msgid "Btrfs volume \"%s\" specified with --useexisting does not exist."
msgstr "--useexisting で指定された BTRFS ボリューム \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:640
#, python-format
msgid ""
"Disklabel \"%s\" given in clearpart command is not supported on this "
"platform."
msgstr ""
"clearpart コマンドで指定されたディスクラベル \"%s\" は、このプラットフォーム"
"では対応していません。"

#: pyanaconda/kickstart.py:652
#, python-format
msgid "Disk \"%s\" given in clearpart command does not exist."
msgstr "clearpart コマンドで指定されたディスク \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:665
#, python-format
msgid "Device \"%s\" given in clearpart device list does not exist."
msgstr "clearpart コマンドで指定されたデバイス \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:692
#, python-format
msgid "NIC \"%s\" given in fcoe command does not exist."
msgstr "fcoe コマンドで指定された NIC \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:752
#, python-format
msgid "%s is missing. Cannot setup firewall."
msgstr "%s が足りません。ファイアウォールの設定ができません。"

#: pyanaconda/kickstart.py:807 pyanaconda/kickstart.py:818
#, python-format
msgid "Disk \"%s\" given in ignoredisk command does not exist."
msgstr "ignoredisk コマンドで指定されたディスク \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:831
#, python-format
msgid ""
"Network interface \"%(nic)s\" required by iSCSI \"%(iscsiTarget)s\" target "
"is not up."
msgstr ""
"iSCSI \"%(iscsiTarget)s\" ターゲットに必要なネットワークインターフェース "
"\"%(nic)s\" が有効になっていません。"

#: pyanaconda/kickstart.py:841
msgid ""
"iscsi --iface must be specified (binding used) either for all targets or for "
"none"
msgstr ""
"iscsi --iface は全ターゲットに指定するか (バインド使用)、どのターゲットにも指"
"定しないのいずれかにしてください。"

#: pyanaconda/kickstart.py:934
#, python-format
msgid ""
"No volume group exists with the name \"%s\".  Specify volume groups before "
"logical volumes."
msgstr ""
"名前が \"%s\" のボリュームグループが存在しません。論理ボリュームの前にボ"
"リュームグループを指定してください。"

#: pyanaconda/kickstart.py:941
msgid "Cache PVs must belong to the same VG as the cached LV"
msgstr "物理ボリューム(PV)は、論理ボリューム(LV)として同じボリュームグループ(VG)に属していなければいけません"

#: pyanaconda/kickstart.py:948
#, python-format
msgid ""
"No thin pool exists with the name \"%s\". Specify thin pools before thin "
"volumes."
msgstr ""
"名前が \"%s\" のシンプールが存在しません。シンボリュームの前にシンプールを指"
"定してください。"

#: pyanaconda/kickstart.py:956
msgid "logvol --noformat must also use the --name= option."
msgstr "logvol --noformat には、--name= オプションも使用する必要があります。"

#: pyanaconda/kickstart.py:961 pyanaconda/kickstart.py:1031
#, python-format
msgid "Logical volume \"%s\" given in logvol command does not exist."
msgstr "logvol コマンドで指定された論理ボリューム \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:972 pyanaconda/kickstart.py:981
#: pyanaconda/kickstart.py:1041 pyanaconda/kickstart.py:1385
#: pyanaconda/kickstart.py:1394 pyanaconda/kickstart.py:1477
#, python-format
msgid "Target size \"%(size)s\" for device \"%(device)s\" is invalid."
msgstr "デバイス \"%(device)s\" のターゲットサイズ \"%(size)s\" は無効です。"

#: pyanaconda/kickstart.py:995
#, python-format
msgid ""
"Logical volume name \"%(logvol)s\" is already in use in volume group "
"\"%(volgroup)s\"."
msgstr ""
"論理ボリューム名 \"%(logvol)s\" は、既にボリュームグループ \"%(volgroup)s\" "
"で使用されています。"

#: pyanaconda/kickstart.py:1002
#, python-format
msgid ""
"No size given for logical volume \"%s\".  Use one of --useexisting, --size, "
"or --percent."
msgstr ""
"論理ボリューム \"%s\" にサイズが指定されていません。 --useexisting、--"
"size、--percent のいずれかを使用してください。"

#: pyanaconda/kickstart.py:1005
#, python-format
msgid ""
"Logical volume size \"%(logvolSize)s\" must be larger than the volume group "
"extent size of \"%(extentSize)s\"."
msgstr ""
"\"%(logvolSize)s\" の論理ボリュームサイズは、ボリュームグループ拡張サイズ "
"\"%(extentSize)s\" より大きいサイズにしてください。"

#: pyanaconda/kickstart.py:1009
msgid "Percentage must be between 0 and 100."
msgstr "0 から 100 の間のパーセンテージを入れてください。"

#: pyanaconda/kickstart.py:1020 pyanaconda/kickstart.py:1413
#: pyanaconda/kickstart.py:1646
#, python-format
msgid "The \"%s\" file system type is not supported."
msgstr "\"%s\" ファイルシステムタイプはサポートされていません。"

#: pyanaconda/kickstart.py:1173
#, python-format
msgid "Unknown or invalid device '%s' specified"
msgstr "不明または無効なデバイス '%s' が指定されました"

#: pyanaconda/kickstart.py:1178
#, python-format
msgid ""
"Unknown or invalid format '%(format)s' specified for device '%(device)s'"
msgstr ""
"不明または無効なフォーマット '%(format)s' がデバイス '%(device)s' に指定され"
"ました"

#: pyanaconda/kickstart.py:1185
#, python-format
msgid "No format on device '%s'"
msgstr " デバイス '%s' にフォーマットがありません"

#: pyanaconda/kickstart.py:1223
msgid "nvdimm: nvdimm plugin not available."
msgstr "nvdimm: nvdimm プラグインは見つかりません。"

#: pyanaconda/kickstart.py:1229 pyanaconda/kickstart.py:1237
#, python-format
msgid "nvdimm: namespace %s not found."
msgstr "nvdimm: 名前空間 %s が見つかりません。"

#: pyanaconda/kickstart.py:1248
#, python-format
msgid "Disk \"%s\" given in nvdimm command does not exist."
msgstr "nvdimm コマンドで指定されたディスク \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:1256 pyanaconda/kickstart.py:1260
#, python-format
msgid "The %s kickstart command is not currently supported."
msgstr "キックスタートコマンド \"%s\" は現在サポートされていません。"

#: pyanaconda/kickstart.py:1285
#, python-format
msgid "No disk found for specified BIOS disk \"%s\"."
msgstr "指定した BIOSディスク \"%s\" に該当するディスクが見つかりません。"

#: pyanaconda/kickstart.py:1320
#, python-format
msgid "RAID partition \"%s\" is defined multiple times."
msgstr "RAIDパーティション \"%s\" が複数回定義されています。"

#: pyanaconda/kickstart.py:1331 pyanaconda/kickstart.py:1568
#, python-format
msgid "PV partition \"%s\" is defined multiple times."
msgstr "PVパーティション \"%s\" が複数回定義されています。"

#: pyanaconda/kickstart.py:1342 pyanaconda/kickstart.py:1578
#, python-format
msgid "Btrfs partition \"%s\" is defined multiple times."
msgstr "BTRFS パーティション \"%s\" が複数回定義されています。"

#: pyanaconda/kickstart.py:1362
#, python-format
msgid "The size \"%s\" is invalid."
msgstr "サイズ指定 \"%s\" は無効です。"

#: pyanaconda/kickstart.py:1369
msgid "part --noformat must also use the --onpart option."
msgstr "part --noformat には --onpart オプションも必要です。"

#: pyanaconda/kickstart.py:1374 pyanaconda/kickstart.py:1468
#, python-format
msgid "Partition \"%s\" given in part command does not exist."
msgstr "part コマンドで指定されたパーティション \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:1428 pyanaconda/kickstart.py:1442
#, python-format
msgid "Disk \"%s\" given in part command does not exist."
msgstr "part コマンドで指定されたディスク \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:1431
#, python-format
msgid "Cannot install to unpartitionable device \"%s\"."
msgstr ""
"パーティションを設定できないデバイス \"%s\" にはインストールできません。"

#: pyanaconda/kickstart.py:1438
#, python-format
msgid "Disk \"%s\" in part command is not partitioned."
msgstr ""
"part コマンドで指定されたディスク \"%s\" は、パーティションが設定されていませ"
"ん。"

#: pyanaconda/kickstart.py:1451
#, python-format
msgid "The maximum size \"%s\" is invalid."
msgstr "最大サイズ \"%s\" は無効です。"

#: pyanaconda/kickstart.py:1600
msgid "raid --noformat must also use the --device option."
msgstr "raid --noformat には --device オプションも使用する必要があります。"

#: pyanaconda/kickstart.py:1605
#, python-format
msgid "RAID device  \"%s\" given in raid command does not exist."
msgstr "raid コマンドで指定した RAID ディスク \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:1628
#, python-format
msgid ""
"RAID device \"%(device)s\" has a format of \"%(format)s\", but should have a "
"format of \"mdmember\"."
msgstr ""
"RAIDデバイス \"%(device)s\" が \"%(format)s\" の形式になっていま"
"す。\"mdmember\" 形式に修正してください。"

#: pyanaconda/kickstart.py:1633
#, python-format
msgid "Tried to use undefined partition \"%s\" in RAID specification."
msgstr "未定義のパーティション \"%s\" を RAID 仕様で使用しようとしました。"

#: pyanaconda/kickstart.py:1667
#, python-format
msgid "RAID volume \"%s\" specified with --useexisting does not exist."
msgstr "--useexisting で指定されたRAIDボリューム \"%s\" は存在しません。"

#: pyanaconda/kickstart.py:1676
#, python-format
msgid "The RAID volume name \"%s\" is already in use."
msgstr "RAIDボリューム名 \"%s\" は既に使用されています。"

#: pyanaconda/kickstart.py:1965
#, python-format
msgid ""
"Physical volume \"%(device)s\" has a format of \"%(format)s\", but should "
"have a format of \"lvmpv\"."
msgstr ""
"物理ボリューム \"%(device)s\" が \"%(format)s\" の形式になっています。\"lvmpv"
"\" 形式に修正してください。"

#: pyanaconda/kickstart.py:1970
#, python-format
msgid "Tried to use undefined partition \"%s\" in Volume Group specification"
msgstr "ボリュームグループ仕様の未定義パーティション \"%s\" の使用を試みました"

#: pyanaconda/kickstart.py:1976
#, python-format
msgid ""
"Volume group \"%s\" defined without any physical volumes.  Either specify "
"physical volumes or use --useexisting."
msgstr ""
"ボリュームグループ \"%s\" に物理ボリュームが定義されていません。物理ボリュー"
"ムを指定するか、--useexisting を使用してください。"

#: pyanaconda/kickstart.py:1986
#, python-format
msgid ""
"Volume group given physical extent size of \"%(extentSize)s\", but must be "
"one of:\n"
"%(validExtentSizes)s."
msgstr ""
"ボリュームグループに物理拡張サイズ \"%(extentSize)s\" が指定されていますが、次のいずれかでなければなりません。\n"
"%(validExtentSizes)s。"

#: pyanaconda/kickstart.py:1993
msgid ""
"volgroup --noformat and volgroup --useexisting must also use the --name= "
"option."
msgstr ""
"volgroup --noformat と volgroup --useexisting には、--name= オプションも使用"
"する必要があります。"

#: pyanaconda/kickstart.py:1998
#, python-format
msgid "Volume group \"%s\" given in volgroup command does not exist."
msgstr "volgroupコマンドで指定されたボリュームグループ\"%s\" は存在しません。"

#: pyanaconda/kickstart.py:2001
#, python-format
msgid "The volume group name \"%s\" is already in use."
msgstr "ボリュームグループ名 \"%s\" は既に使用されています。"

#: pyanaconda/kickstart.py:2124
msgid ""
"Incorrectly specified origin of the snapshot. Use format \"VolGroup/LV_name\""
msgstr ""
"スナップショットの元が間違って指定されました。\"VolGroup/LV_name\" の形式を使"
"用してください"

#: pyanaconda/kickstart.py:2135
#, python-format
msgid ""
"Snapshot: origin \"%(origin)s\" of snapshot \"%(name)s\" is not a valid thin "
"LV device."
msgstr ""
"スナップショット: スナップショット \"%(name)s\" の元となる \"%(origin)s\" "
"は、有効な論理ボリューム (LV) のシンデバイスではありません。"

#: pyanaconda/kickstart.py:2143
#, python-format
msgid "Snapshot %s already exists."
msgstr "スナップショット %s は既に存在します。"

#: pyanaconda/kickstart.py:2179
msgid ""
"The upgrade kickstart command is no longer supported. Upgrade functionality "
"is provided through fedup."
msgstr ""
"upgrade キックスタートコマンドはサポートされなくなります。アップグレード機能"
"は fedup で提供されます。"

#: pyanaconda/network.py:110
msgid "Host name cannot be None or an empty string."
msgstr "ホスト名なし、または空白の文字は設定できません。"

#: pyanaconda/network.py:113
msgid "Host name must be 255 or fewer characters in length."
msgstr "ホスト名は、255 文字か、それ以下の長さにする必要があります。"

#: pyanaconda/network.py:116
msgid ""
"Host names can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.', "
"parts between periods must contain something and cannot start or end with "
"'-'."
msgstr ""
" ホスト名には半角英数 'a-z'、'A-Z'、'0-9'、および記号 '-'、'.' を使用すること"
"ができます。ただし、ピリオドを連続して使用することはできません。また、'-' "
"は、ホスト名の先頭と終わりには使用できません。"

#: pyanaconda/network.py:1632 pyanaconda/ui/gui/spokes/custom.py:566
#: pyanaconda/ui/gui/spokes/network.py:326
#: pyanaconda/ui/gui/spokes/lib/accordion.py:64
msgid "Unknown"
msgstr "不明"

#: pyanaconda/network.py:1636
msgid "Connecting..."
msgstr "接続中..."

#: pyanaconda/network.py:1638
msgid "Disconnecting..."
msgstr "切断中..."

#: pyanaconda/network.py:1660
#, python-format
msgid "Wired (%(interface_name)s) connected"
msgstr "有線 (%(interface_name)s) が接続されました"

#: pyanaconda/network.py:1663
#, python-format
msgid "Wireless connected to %(access_point)s"
msgstr "無線 LAN のアクセスポイント %(access_point)s に接続されました"

#: pyanaconda/network.py:1666
#, python-format
msgid "Bond %(interface_name)s (%(list_of_slaves)s) connected"
msgstr "ボンド %(interface_name)s (%(list_of_slaves)s) が接続されました"

#: pyanaconda/network.py:1670
#, python-format
msgid "Team %(interface_name)s (%(list_of_slaves)s) connected"
msgstr "チーム %(interface_name)s (%(list_of_slaves)s) が接続されました"

#: pyanaconda/network.py:1674
#, python-format
msgid "Bridge %(interface_name)s (%(list_of_slaves)s) connected"
msgstr "ブリッジ %(interface_name)s (%(list_of_slaves)s) が接続されました"

#: pyanaconda/network.py:1684
#, python-format
msgid "VLAN %(interface_name)s (%(parent_device)s, ID %(vlanid)s) connected"
msgstr ""
"VLAN %(interface_name)s (%(parent_device)s, ID %(vlanid)s) が接続されました"

#: pyanaconda/network.py:1702
#, python-format
msgid "Connected: %(list_of_interface_names)s"
msgstr "接続済み: %(list_of_interface_names)s"

#: pyanaconda/network.py:1705
msgid "Not connected"
msgstr "接続していません"

#: pyanaconda/network.py:1708 pyanaconda/ui/gui/spokes/network.glade.h:45
msgid "No network devices available"
msgstr "ネットワークデバイスは利用できません"

#: pyanaconda/product.py:55
#, python-format
msgid "%(productName)s %(productVersion)s INSTALLATION"
msgstr "%(productName)s %(productVersion)s のインストール"

#: pyanaconda/product.py:59
#, python-format
msgid "New %(name)s %(version)s Installation"
msgstr "新規で %(name)s %(version)s のインストール"

#: pyanaconda/pwpolicy.py:124
#, python-format
msgid "policy name required for %s"
msgstr "%s にポリシー名が必要です"

#: pyanaconda/pwpolicy.py:133
#, python-format
msgid "A %(command)s with the name %(policyName)s has already been defined."
msgstr "%(policyName)s という名前の %(command)s は、既に定義されています。"

#: pyanaconda/rescue.py:67
#, python-format
msgid "Run %s to unmount the system when you are finished."
msgstr ""
"メンテナンスが終わったら、%s を実行してシステムをアンマウントしてください。"

#: pyanaconda/rescue.py:70
msgid "When finished, please exit from the shell and your system will reboot."
msgstr "完了したらシェルを終了してください。システムは再起動します。"

#: pyanaconda/rescue.py:78
msgid "Unable to find /bin/bash to execute!  Not starting shell."
msgstr "/bin/bash が見つかりません。シェルを起動できません。"

#: pyanaconda/rescue.py:120
msgid "Rescue"
msgstr "レスキュー"

#: pyanaconda/rescue.py:132
msgid "Continue"
msgstr "続行"

#: pyanaconda/rescue.py:132
msgid "Read-only mount"
msgstr "読み取り専用でマウント"

#: pyanaconda/rescue.py:132
msgid "Skip to shell"
msgstr "シェルへスキップ"

#: pyanaconda/rescue.py:146
msgid "Please make a selection from the above:  "
msgstr "上記から選択してください:   "

#: pyanaconda/rescue.py:151
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory : %s.  You can then make any changes required "
"to your system.  Choose '1' to proceed with this step.\n"
"You can choose to mount your file systems read-only instead of read-write by "
"choosing '2'.\n"
"If for some reason this process does not work choose '3' to skip directly to "
"a shell.\n"
"\n"
msgstr ""
"レスキュー環境では、Linuxインストールの検索、%s ディレクトリー配下へのマウン"
"トが行われ、システムに必要な変更を行うことができるようになります。このステッ"
"プを続行する場合は '1' を選択します。\n"
"読み取りと書き込みではなく、読み取り専用のアクセスでファイルシステムをマウン"
"トする場合は '2' を選択してください。\n"
"何らかの理由でこのプロセスが正しく動作しない場合は、'3' を選択すると、このス"
"テップを飛ばしてシェルに切り替わります。\n"
"\n"

#: pyanaconda/rescue.py:267
msgid "Root Selection"
msgstr "Root の選択"

#: pyanaconda/rescue.py:284
msgid "The following installations were discovered on your system.\n"
msgstr "以下のインストールがお使いのシステムで見つかりました。\n"

#: pyanaconda/rescue.py:296
msgid ""
"Please make your selection from the above list.\n"
"Press 'c' to continue after you have made your selection.  "
msgstr ""
"上記リストから選択してください。\n"
"選択後に 'c' を押して続行してください。 "

#. TRANSLATORS: 'c' to continue
#. TRANSLATORS:'c' to continue
#. TRANSLATORS: 'c' to continue
#. TRANSLATORS:'c' to continue
#. TRANSLATORS: 'c' to continue
#: pyanaconda/rescue.py:305 pyanaconda/ui/tui/hubs/summary.py:153
#: pyanaconda/ui/tui/hubs/__init__.py:123
#: pyanaconda/ui/tui/hubs/__init__.py:149
#: pyanaconda/ui/tui/simpleline/base.py:462
#: pyanaconda/ui/tui/simpleline/base.py:672
#: pyanaconda/ui/tui/spokes/storage.py:279
#: pyanaconda/ui/tui/spokes/storage.py:620
#: pyanaconda/ui/tui/spokes/storage.py:672
#: pyanaconda/ui/tui/spokes/source.py:482
#: pyanaconda/ui/tui/spokes/software.py:171
msgctxt "TUI|Spoke Navigation"
msgid "c"
msgstr "c"

#: pyanaconda/rescue.py:327
msgid "Rescue Mount"
msgstr "レスキューマウント"

#: pyanaconda/rescue.py:349
msgid ""
"Your system had dirty file systems which you chose not to mount.  From a "
"shell, you can fsck and mount your partitions manually.\n"
msgstr ""
"システムにダーティーなファイルシステムがあり、マウントしない選択をしていま"
"す。シェルで fsck を行ってから、手動によるパーティションのマウントを行うこと"
"ができます。\n"

#: pyanaconda/rescue.py:358
#, python-format
msgid ""
"Your system has been mounted under %(mountpoint)s.\n"
"\n"
"If you would like to make your system the root environment, run the "
"command:\n"
"\n"
"\tchroot %(mountpoint)s\n"
msgstr ""
"システムは、%(mountpoint)s 配下にマウントされています。\n"
"\n"
"システムを root 環境にする場合は、次のコマンドを実行します。\n"
"\n"
"\tchroot %(mountpoint)s\n"

#: pyanaconda/rescue.py:397
#, python-format
msgid "Run %s to unmount the system when you are finished.\n"
msgstr "作業が終了したら、%s を実行してシステムをアンマウントします。\n"

#: pyanaconda/rescue.py:399
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system.  Some of it "
"may be mounted under %s\n"
"\n"
msgstr ""
"システム全体またはその一部をマウントする際に、エラーが発生しました。一部が "
"%s  にマウントされている可能性があります。\n"
"\n"

#: pyanaconda/rescue.py:406
msgid "You don't have any Linux partitions.  Rebooting.\n"
msgstr "Linux パーティションがありません。再起動します。\n"

#: pyanaconda/rescue.py:413
msgid "The system will reboot automatically when you exit from the shell.\n"
msgstr "シェルを終了すると、システムは自動的に再起動します。\n"

#: pyanaconda/rescue.py:417
#, python-format
msgid "You don't have any Linux partitions. %s\n"
msgstr "Linux パーティションがありません。%s\n"

#: pyanaconda/rescue.py:446
msgid "Please press <return> to get a shell. "
msgstr "<return> を押してシェルを起動してください。"

#: pyanaconda/storage_utils.py:56 pyanaconda/storage_utils.py:88
#: pyanaconda/ui/gui/spokes/custom.glade.h:3
msgid "LVM"
msgstr "LVM"

#: pyanaconda/storage_utils.py:57 pyanaconda/storage_utils.py:89
#: pyanaconda/ui/gui/spokes/custom.glade.h:5
msgid "LVM Thin Provisioning"
msgstr "LVM シンプロビジョニング"

#: pyanaconda/storage_utils.py:58 pyanaconda/ui/gui/spokes/custom.glade.h:4
msgid "RAID"
msgstr "RAID"

#: pyanaconda/storage_utils.py:59 pyanaconda/storage_utils.py:86
#: pyanaconda/ui/gui/spokes/custom.glade.h:1
msgid "Standard Partition"
msgstr "標準パーティション"

#: pyanaconda/storage_utils.py:60 pyanaconda/storage_utils.py:87
#: pyanaconda/ui/gui/spokes/custom.glade.h:2
msgid "Btrfs"
msgstr "Btrfs"

#: pyanaconda/storage_utils.py:61 pyanaconda/ui/gui/spokes/lib/resize.glade.h:5
msgid "Disk"
msgstr "ディスク"

#: pyanaconda/storage_utils.py:72
msgid ""
"The 'swap' area on your computer is used by the operating\n"
"system when running low on memory."
msgstr ""
"コンピューターのスワップ領域は、メモリー不足の状態になると\n"
"オペレーティングシステムで使用されます。"

#: pyanaconda/storage_utils.py:74
msgid ""
"The 'boot' area on your computer is where files needed\n"
"to start the operating system are stored."
msgstr ""
"コンピューターのブート領域は、オペレーティング\n"
"システムを開始するのに必要なファイルを収納しています。"

#: pyanaconda/storage_utils.py:76
msgid ""
"The 'root' area on your computer is where core system\n"
"files and applications are stored."
msgstr ""
"コンピューターの root 領域は、システムファイルと\n"
"アプリケーションを収納しています。"

#: pyanaconda/storage_utils.py:78
msgid ""
"The 'home' area on your computer is where all your personal\n"
"data is stored."
msgstr ""
"コンピューターのホーム領域は、ユーザーの個人\n"
"データを収納しています。"

#: pyanaconda/storage_utils.py:80
msgid ""
"The BIOS boot partition is required to enable booting\n"
"from GPT-partitioned disks on BIOS hardware."
msgstr ""
"BIOS ハードウェア上で、GPT パーティションを設定したディスクからの\n"
"起動を有効にするには、BIOS のブートパーティションが必要です。"

#: pyanaconda/storage_utils.py:82
msgid ""
"The PReP boot partition is required as part of the\n"
"boot loader configuration on some PPC platforms."
msgstr ""
"一部の PPC プラットフォームでは、ブートローダー設定に\n"
"PReP ブートパーティションが必要です。"

#: pyanaconda/storage_utils.py:159
#, python-format
msgid ""
"Your root partition is less than %(size)s which is usually too small to "
"install %(product)s."
msgstr ""
"root パーティションの容量は %(size)s 未満です。これは通常、%(product)s のイン"
"ストールには不十分です。"

#: pyanaconda/storage_utils.py:165
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr ""
"root パーティション (/) が未定義です。%s をインストールするには root パーティ"
"ションが必要です。"

#: pyanaconda/storage_utils.py:178
#, python-format
msgid "Your root partition must be on a device of type: %s."
msgstr "root パーティションはタイプ: %s のデバイスにある必要があります。"

#: pyanaconda/storage_utils.py:194
#, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""
"%(mount)s パーティションの容量が %(size)s 未満であり、通常の %(productName)s "
"のインストールで推奨される容量に達していません。"

#: pyanaconda/storage_utils.py:202
#, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s which is lower than required."
msgstr ""
"%(mount)s パーティションの容量が、必要とされる %(size)s に達していません。"

#: pyanaconda/storage_utils.py:220
#, python-format
msgid ""
"Your %(mount)s partition is too small for %(format)s formatting (allowable "
"size is %(minSize)s to %(maxSize)s)"
msgstr ""
"このシステムの %(mount)s パーティションは、%(format)s フォーマットには小さす"
"ぎます (指定可能なサイズは %(minSize)s MB から %(maxSize)s MB です)。"

#: pyanaconda/storage_utils.py:226
#, python-format
msgid ""
"Your %(mount)s partition is too large for %(format)s formatting (allowable "
"size is %(minSize)s to %(maxSize)s)"
msgstr ""
"ご使用の %(mount)s パーティションは、%(format)s フォーマットするには大きすぎます (指定可能なサイズは %(minSize)s "
"から %(maxSize)s です)"

#: pyanaconda/storage_utils.py:245
msgid "No valid boot loader target device found. See below for details."
msgstr ""
"ブートローダーで有効なターゲットデバイスがありません。以下の詳細を確認してく"
"ださい。"

#: pyanaconda/storage_utils.py:260
msgid "You have not created a bootable partition."
msgstr "ブート可能なパーティションが作成されていません。"

#: pyanaconda/storage_utils.py:295
msgid ""
"Your BIOS-based system needs a special partition to boot from a GPT disk "
"label. To continue, please create a 1MiB 'biosboot' type partition."
msgstr ""
"ご使用の BIOS ベースのシステムは、GPT ディスクラベルから起動するのに、特別な"
"パーティションが必要です。継続するには、サイズが 1MiB で、タイプが "
"'biosboot' のパーティションを作成してください。"

#: pyanaconda/storage_utils.py:316
#, python-format
msgid ""
"You have not specified a swap partition. %(requiredMem)s of memory is "
"required to continue installation without a swap partition, but you only "
"have %(installedMem)s."
msgstr ""
"swap パーティションが指定されていません。swap パーティションを使用せずにイン"
"ストールを続行するには %(requiredMem)s のメモリーが必要です"
"が、%(installedMem)s しかありません。"

#: pyanaconda/storage_utils.py:322
msgid ""
"You have not specified a swap partition. Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""
"swap パーティションが指定されていません。swap パーティションは必須ではありま"
"せんが、これがあると大抵のインストールでパフォーマンスが大幅に改善します。"

#: pyanaconda/storage_utils.py:340
msgid ""
"At least one of your swap devices does not have a UUID, which is common in "
"swap space created using older versions of mkswap. These devices will be "
"referred to by device path in /etc/fstab, which is not ideal since device "
"paths can change under a variety of circumstances. "
msgstr ""
"1 つ以上の swap デバイスに UUID が設定されていません。これは、旧バージョンの mkswap コマンドを使用して作成した swap "
"領域では一般的です。これらのデバイスは、/etc/fstab "
"でデバイスパスによる参照が行われますが、デバイスパスはさまざまな事情で変更する可能性があるため、デバイスパスによる参照は理想的な方法ではありません。 "

#: pyanaconda/storage_utils.py:361
#, python-format
msgid ""
"This mount point is invalid. The %s directory must be on the / file system."
msgstr ""
"このマウントポイントは有効ではありません。%s ディレクトリーは / ファイルシス"
"テムに配置されている必要があります。"

#: pyanaconda/storage_utils.py:377
#, python-format
msgid "Your %s must be on a separate partition or LV."
msgstr ""
"%s は、別のパーティションもしくは論理ボリューム上に配置されている必要がありま"
"す。"

#: pyanaconda/storage_utils.py:394
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr "マウントポイント %s は、Linux ファイルシステム上に配置してください。"

#: pyanaconda/storage_utils.py:413
#, python-format
msgid "LUKS device %s has no encryption key"
msgstr "LUKS デバイス %s に暗号キーがありません"

#: pyanaconda/users.py:234
#, python-format
msgid "User name is reserved for system: %s"
msgstr "次のユーザー名は、システムで予約されています: %s"

#: pyanaconda/users.py:237
msgid "User name cannot start with '-' character"
msgstr "ユーザー名は '-' 文字で始めることができません"

#: pyanaconda/users.py:246
#, python-format
msgid "User name cannot contain character: '%s'"
msgstr "ユーザー名には次の文字を使用できません: '%s'"

#: pyanaconda/users.py:249
msgid "User name must be shorter than 33 characters"
msgstr "ユーザー名は 33 文字未満にしてください"

#: pyanaconda/vnc.py:76
#, python-format
msgid "%(productName)s %(productVersion)s installation"
msgstr "%(productName)s %(productVersion)s のインストール"

#: pyanaconda/vnc.py:139
#, python-format
msgid "%(productName)s %(productVersion)s installation on host %(name)s"
msgstr "ホスト %(name)s 上の %(productName)s %(productVersion)s のインストール"

#: pyanaconda/vnc.py:158
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr "ホスト %s 上の VNC クライアントに接続を試行中..."

#: pyanaconda/vnc.py:172
msgid "Connected!"
msgstr "接続しました!"

#: pyanaconda/vnc.py:175
msgid "Will try to connect again in 15 seconds..."
msgstr "15 秒後に再接続を試みます..."

#: pyanaconda/vnc.py:182
#, python-format
msgid "Giving up attempting to connect after %d try!\n"
msgid_plural "Giving up attempting to connect after %d tries!\n"
msgstr[0] "接続を %d 回試みた後に断念します。\n"

#: pyanaconda/vnc.py:190
msgid "Attempting to start vncconfig"
msgstr "vncconfig を開始しようとしています"

#: pyanaconda/vnc.py:203
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr ""
"インストールを開始するには、手動で、ご使用の vnc クライアントを %s に接続して"
"ください。"

#: pyanaconda/vnc.py:205
#, python-format
msgid ""
"Please manually connect your vnc client to <IP ADDRESS>:%s to begin the "
"install. Switch to the shell (Ctrl-B 2) and run 'ip addr' to find the <IP "
"ADDRESS>."
msgstr ""
"vnc クライアントを <IP ADDRESS>:%s に手動で接続し、インストールを開始してくだ"
"さい。シェルに移動し (Ctrl-B 2)、'ip addr' を実行して <IP ADDRESS> を検索しま"
"す。"

#: pyanaconda/vnc.py:210
msgid "Starting VNC..."
msgstr "VNC を起動中..."

#: pyanaconda/vnc.py:247
msgid "The VNC server is now running."
msgstr "VNC サーバーが稼動しています。"

#: pyanaconda/vnc.py:251
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""
"\n"
"\n"
"Listen モードの VNC Viewer への接続を選択しました。\n"
"この場合、パスワードの設定は必要ありません。\n"
"パスワードを設定すると、VNC Viewer への接続が\n"
"失敗した場合にそのパスワードが使用されます。\n"
"\n"

#: pyanaconda/vnc.py:256
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""
"\n"
"\n"
"警告!!! VNC サーバーがパスワードなしで実行されています!\n"
"サーバーの安全性を確保するには、vncpassword=<password>\n"
"ブートオプションを使うことができます。\n"
"\n"

#: pyanaconda/vnc.py:260
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""
"\n"
"\n"
"パスワードを使って VNC を実行するように選択しました。\n"
"\n"

#: pyanaconda/vnc.py:262
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""
"\n"
"\n"
"不明なエラーが発生しました。作業を中断します。\n"
"\n"

#: pyanaconda/vnc.py:284
msgid ""
"VNC password must be six to eight characters long.\n"
"Please enter a new one, or leave blank for no password."
msgstr ""
"VNCパスワードは 6 - 8 文字の長さにしてください。\n"
"新しいパスワードを入力するか、パスワードがいらない場合は空白にします。"

#: pyanaconda/packaging/__init__.py:1374
msgid "Failed to set up installation source"
msgstr "インストールソースの設定に失敗しました"

#: pyanaconda/packaging/__init__.py:1375
msgid "Error downloading package metadata"
msgstr "パッケージメタデータをダウンロード中にエラー"

#: pyanaconda/packaging/__init__.py:1376
msgid "No installation source available"
msgstr "インストールソースは利用できません"

#: pyanaconda/packaging/livepayload.py:98
#: pyanaconda/packaging/livepayload.py:119
msgid "Installing software"
msgstr "ソフトウェアをインストール中…"

#: pyanaconda/packaging/livepayload.py:220
#: pyanaconda/packaging/livepayload.py:229
#, python-format
msgid "Downloading %(url)s (%(pct)d%%)"
msgstr "%(url)s (%(pct)d%%) をダウンロード中"

#: pyanaconda/packaging/livepayload.py:358
msgid "Checking image checksum"
msgstr "イメージのチェックサムを確認中"

#: pyanaconda/packaging/yumpayload.py:1363
#, python-format
msgid "CmdlineError: Missing package: %s"
msgstr "CmdlineError: 見つからないパッケージ: %s"

#: pyanaconda/packaging/yumpayload.py:1518
msgid "Starting package installation process"
msgstr "パッケージインストールプロセスを開始しています"

#: pyanaconda/packaging/yumpayload.py:1552
msgid "Preparing transaction from installation source"
msgstr "インストールソースからのトランザクションを準備中"

#: pyanaconda/packaging/yumpayload.py:1553
msgid "Installing"
msgstr "インストール中"

#: pyanaconda/packaging/rpmostreepayload.py:163
#, python-format
msgid "Starting pull of %(branchName)s from %(source)s"
msgstr " %(source)s から %(branchName)s を引くのを開始"

#: pyanaconda/packaging/rpmostreepayload.py:193
#, python-format
msgid "Preparing deployment of %s"
msgstr " %s のデプロイ準備"

#: pyanaconda/packaging/rpmostreepayload.py:205
#, python-format
msgid "Deployment starting: %s"
msgstr " %s のデプロイ開始"

#: pyanaconda/packaging/rpmostreepayload.py:208
#, python-format
msgid "Deployment complete: %s"
msgstr " %s のデプロイ完了"

#: pyanaconda/ui/helpers.py:98 pyanaconda/ui/tui/spokes/storage.py:458
msgid "Checking storage configuration..."
msgstr "ストレージ設定をチェック中..."

#: pyanaconda/ui/categories/__init__.py:48
msgid "DEFAULT TITLE"
msgstr "デフォルトのタイトル"

#: pyanaconda/ui/categories/customization.py:32
msgid "CUSTOMIZATION"
msgstr "カスタマイズ"

#: pyanaconda/ui/categories/localization.py:31
msgid "LOCALIZATION"
msgstr "地域設定"

#: pyanaconda/ui/categories/software.py:31
msgid "SOFTWARE"
msgstr "ソフトウェア"

#: pyanaconda/ui/categories/system.py:32
#: pyanaconda/ui/gui/spokes/lib/accordion.py:180
msgid "SYSTEM"
msgstr "システム"

#: pyanaconda/ui/categories/user_settings.py:32
msgid "USER SETTINGS"
msgstr "ユーザーの設定"

#: pyanaconda/ui/lib/space.py:37
#, python-format
msgid ""
"Not enough space in file systems for the current software selection. An "
"additional %s is needed."
msgstr ""
"現在選択しているソフトウェア選択に対してファイルシステムの空き領域が不足して"
"います。追加で %s 必要です。"

#: pyanaconda/ui/lib/entropy.py:58
msgid "The system needs more random data entropy"
msgstr "このシステムは、もっと多くの乱数のエントロピーを必要としています。"

#: pyanaconda/ui/lib/entropy.py:67
msgid "Entropy can be increased by typing randomly on keyboard"
msgstr ""
"エントロピーはキーボードをランダムに入力することで増加させることができます。"

#: pyanaconda/ui/lib/entropy.py:68
#, python-format
msgid ""
"After %d minutes, the installation will continue regardless of the amount of "
"available entropy"
msgstr ""
"インストールに利用可能なエントロピーの量に関わらず、%d 分後に続行します。"

#: pyanaconda/ui/lib/entropy.py:92
#, python-format
msgid ""
"Available entropy: %(av_entr)s, Required entropy: %(req_entr)s [%(pct)d %%] "
"(%(rem)d %(min)s remaining)"
msgstr ""
"利用可能なエントロピー: %(av_entr)s, 必要なエントロピー: %(req_entr)s "
"[%(pct)d %%] (残り %(rem)d %(min)s)"

#: pyanaconda/ui/lib/entropy.py:95
#: pyanaconda/ui/gui/spokes/lib/entropy_dialog.py:92
msgid "minute"
msgid_plural "minutes"
msgstr[0] "分"

#: pyanaconda/ui/lib/entropy.py:102
#, python-format
msgid ""
"Available entropy: %(av_entr)s, Required entropy: %(req_entr)s [%(pct)d %%]"
msgstr ""
"利用可能なエントロピー: %(av_entr)s, 必要なエントロピー: %(req_entr)s "
"[%(pct)d %%]"

#: pyanaconda/ui/lib/entropy.py:107
msgid "Enough entropy gathered, please stop typing."
msgstr "十分なエントロピーが集まりました。キー入力を止めてください。"

#: pyanaconda/ui/lib/entropy.py:110
#, python-format
msgid "Giving up, time (%d minutes) ran out."
msgstr "%d 分経過したので続行します。"

#: pyanaconda/ui/lib/disks.py:113
#, python-format
msgid ""
"You selected disk %(selected)s, which contains devices that also use "
"unselected disk %(unselected)s. You must select or de-select these disks as "
"a set."
msgid_plural ""
"You selected disk %(selected)s, which contains devices that also use "
"unselected disks %(unselected)s. You must select or de-select these disks as "
"a set."
msgstr[0] ""
"ディスク %(selected)s を選択しました。選択したディスクに含まれるデバイスの中"
"に、未選択のディスク %(unselected)s を使用するデバイスがあります。ディスクを"
"選択する場合は、一貫性のある選択を行ってください。"

#: pyanaconda/ui/tui/hubs/summary.py:35
msgid "Installation"
msgstr "インストール"

#: pyanaconda/ui/tui/hubs/summary.py:51
msgid "Starting automated install"
msgstr "自動インストールの開始"

#. TRANSLATORS: 'b' to begin installation
#: pyanaconda/ui/tui/hubs/summary.py:93
#, python-format
msgid "Enter '%s' to ignore the warning and attempt to install anyway."
msgstr "警告を無視してインストールを行うには 、'%s' を入力します。"

#. TRANSLATORS: 'b' to begin installation
#: pyanaconda/ui/tui/hubs/summary.py:95 pyanaconda/ui/tui/hubs/summary.py:122
#: pyanaconda/ui/tui/hubs/summary.py:139
msgctxt "TUI|Spoke Navigation"
msgid "b"
msgstr "b"

#: pyanaconda/ui/tui/hubs/summary.py:104
msgid "The following mandatory spokes are not completed:"
msgstr "以下の強制スポークが完了していません:"

#: pyanaconda/ui/tui/hubs/summary.py:118
#, python-format
msgid ""
"  Please make your choice from above ['%(quit)s' to quit | '%(begin)s' to "
"begin installation |\n"
"  '%(refresh)s' to refresh]: "
msgstr ""
" 以下から選択してください。   ['%(quit)s 終了 | '%(begin)s インストールの開"
"始 |\n"
"  '%(refresh)s 更新]: "

#. TRANSLATORS: 'q' to quit
#: pyanaconda/ui/tui/hubs/summary.py:120 pyanaconda/ui/tui/hubs/__init__.py:147
#: pyanaconda/ui/tui/simpleline/base.py:468
#: pyanaconda/ui/tui/simpleline/base.py:670
msgctxt "TUI|Spoke Navigation"
msgid "q"
msgstr "q"

#. TRANSLATORS: 'r' to refresh
#. TRANSLATORS:'r' to refresh
#. TRANSLATORS: 'r' to refresh
#. TRANSLATORS:'r' to refresh
#: pyanaconda/ui/tui/hubs/summary.py:124 pyanaconda/ui/tui/hubs/__init__.py:151
#: pyanaconda/ui/tui/simpleline/base.py:456
#: pyanaconda/ui/tui/simpleline/base.py:674
msgctxt "TUI|Spoke Navigation"
msgid "r"
msgstr "r"

#: pyanaconda/ui/tui/hubs/summary.py:142 pyanaconda/ui/tui/hubs/__init__.py:126
msgid "Please complete all spokes before continuing"
msgstr "すべてのスポークを完了してから継続してください"

#: pyanaconda/ui/tui/hubs/__init__.py:45
msgid "Default HUB title"
msgstr "デフォルトのハブタイトル"

#: pyanaconda/ui/tui/hubs/__init__.py:143
#, python-format
msgid ""
"  Please make your choice from [ '1' to enter the %(spoke_title)s spoke | "
"'%(quit)s' to quit |\n"
"  '%(continue)s' to continue | '%(refresh)s' to refresh]: "
msgstr ""
"  以下から選択してください。 [ '1' %(spoke_title)s スポークに入る | "
"'%(quit)s' 終了 |\n"
"  '%(continue)s' 続行 | '%(refresh)s' 更新]: "

#: pyanaconda/ui/tui/tuiobject.py:30 pyanaconda/ui/gui/main.glade.h:2
msgid "Error"
msgstr "エラー"

#: pyanaconda/ui/tui/tuiobject.py:51
msgid "Press enter to exit."
msgstr "'Enter' を押して終了します。"

#: pyanaconda/ui/tui/tuiobject.py:64 pyanaconda/ui/tui/spokes/password.py:72
#: pyanaconda/ui/gui/spokes/password.glade.h:4
#: pyanaconda/ui/gui/spokes/user.glade.h:8
msgid "Password"
msgstr "パスワード"

#: pyanaconda/ui/tui/tuiobject.py:85
msgid "Passphrase: "
msgstr "パスフレーズ: "

#: pyanaconda/ui/tui/tuiobject.py:111
msgid "Question"
msgstr "質問"

#: pyanaconda/ui/tui/tuiobject.py:134
#, python-format
msgid "Please respond '%(yes)s' or '%(no)s': "
msgstr "'%(yes)s' か '%(no)s' で応答してください: "

#. TRANSLATORS: 'yes' as positive reply
#: pyanaconda/ui/tui/tuiobject.py:136 pyanaconda/ui/tui/tuiobject.py:143
msgctxt "TUI|Spoke Navigation"
msgid "yes"
msgstr "はい (yes)"

#. TRANSLATORS: 'no' as negative reply
#: pyanaconda/ui/tui/tuiobject.py:138 pyanaconda/ui/tui/tuiobject.py:149
msgctxt "TUI|Spoke Navigation"
msgid "no"
msgstr "いいえ (no)"

#: pyanaconda/ui/tui/simpleline/base.py:92
msgid "Do you really want to quit?"
msgstr "本当に終了しますか？"

#: pyanaconda/ui/tui/simpleline/base.py:617 anaconda:538
msgid "Press ENTER to continue"
msgstr "Enter を押して続けます"

#: pyanaconda/ui/tui/simpleline/base.py:668
#, python-format
msgid ""
"  Please make your choice from above ['%(quit)s' to quit | '%(continue)s' to "
"continue |\n"
"  '%(refresh)s' to refresh]: "
msgstr ""
"次から選択してください。 ['%(quit)s'で終了 | '%(continue)s' で続行 |\n"
"  '%(refresh)s' で更新]: "

#: pyanaconda/ui/tui/spokes/askvnc.py:40
msgid "VNC"
msgstr "VNC"

#: pyanaconda/ui/tui/spokes/askvnc.py:57
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"installation or continue with a text mode installation?"
msgstr ""
"お使いのマシンで X を起動できませんでした。VNC を起動して、別のコンピューター"
"からこのマシンに接続してグラフィカルなインストールを行ないますか? または、テ"
"キストモードのインストールで続行しますか?"

#: pyanaconda/ui/tui/spokes/askvnc.py:106
msgid "q"
msgstr "q"

#: pyanaconda/ui/tui/spokes/askvnc.py:123
msgid "VNC Password"
msgstr "VNC パスワード"

#: pyanaconda/ui/tui/spokes/askvnc.py:131
msgid ""
"Please provide VNC password (must be six to eight characters long).\n"
"You will have to type it twice. Leave blank for no password"
msgstr ""
"VNC パスワードを入力してください (6 文字から 8 文字の長さ)。\n"
"2 回入力する必要があります。パスワードを設定しない場合は空白のままにしておきます"

#: pyanaconda/ui/tui/spokes/askvnc.py:150
#: pyanaconda/ui/gui/spokes/network.py:1426
msgid "Password: "
msgstr "パスワード: "

#: pyanaconda/ui/tui/spokes/askvnc.py:151
msgid "Password (confirm): "
msgstr "パスワード(確定): "

#: pyanaconda/ui/tui/spokes/askvnc.py:154
msgid "Passwords do not match!"
msgstr "パスワードが一致しません！"

#: pyanaconda/ui/tui/spokes/askvnc.py:157
msgid "The password must be at least six characters long."
msgstr "パスワードは 6 文字以上でなければなりません。"

#: pyanaconda/ui/tui/spokes/askvnc.py:161
msgid "The password cannot be more than eight characters long."
msgstr "パスワードは 8 文字以内の長さにしてください。"

#: pyanaconda/ui/tui/spokes/kernel_warning.py:36
msgid "Warning: Processor has Simultaneous Multithreading (SMT) enabled"
msgstr ""
"警告: プロセッサーで、同時マルチスレッディング (SMT) が有効になっています"

#: pyanaconda/ui/tui/spokes/langsupport.py:39
msgid "Language settings"
msgstr "言語設定"

#: pyanaconda/ui/tui/spokes/langsupport.py:73
msgid "Language is not set."
msgstr "言語が設定されていません。"

#: pyanaconda/ui/tui/spokes/langsupport.py:83
msgid "Available locales"
msgstr "使用可能なロケール"

#: pyanaconda/ui/tui/spokes/langsupport.py:86
msgid "Available languages"
msgstr "使用可能な言語"

#. TRANSLATORS: 'b' to go back
#: pyanaconda/ui/tui/spokes/langsupport.py:120
#: pyanaconda/ui/tui/spokes/langsupport.py:130
msgctxt "TUI|Spoke Navigation|Language Support"
msgid "b"
msgstr "b"

#: pyanaconda/ui/tui/spokes/langsupport.py:128
#, python-format
msgid ""
"Please select language support to install.\n"
"[%(back)s to return to language list, %(continue)s to continue, %(quit)s to "
"quit]: "
msgstr ""
"インストールする言語サポートを選択してください。\n"
"[%(back)s 言語の一覧に戻る、%(continue)s 続行する、%(quit)s 終了する]: "

#. TRANSLATORS:'c' to continue
#: pyanaconda/ui/tui/spokes/langsupport.py:132
msgctxt "TUI|Spoke Navigation|Language Support"
msgid "c"
msgstr "c"

#. TRANSLATORS:'q' to quit
#: pyanaconda/ui/tui/spokes/langsupport.py:134
msgctxt "TUI|Spoke Navigation|Language Support"
msgid "q"
msgstr "q"

#: pyanaconda/ui/tui/spokes/network.py:48
msgid "Network configuration"
msgstr "ネットワークの設定"

#: pyanaconda/ui/tui/spokes/network.py:123
#, python-format
msgid "Wired (%(interface_name)s) disconnected\n"
msgstr "有線 (%(interface_name)s) で切断されました\n"

#: pyanaconda/ui/tui/spokes/network.py:128
#, python-format
msgid "Wired (%(interface_name)s) connected\n"
msgstr "有線 (%(interface_name)s) で接続されました\n"

#: pyanaconda/ui/tui/spokes/network.py:140
#, python-format
msgid " IPv4 Address: %(addr)s Netmask: %(netmask)s Gateway: %(gateway)s\n"
msgstr ""
"IPv4 アドレス: %(addr)s ネットマスク: %(netmask)s ゲートウェイ: %(gateway)s\n"

#: pyanaconda/ui/tui/spokes/network.py:142
#, python-format
msgid " DNS: %s\n"
msgstr " DNS: %s\n"

#: pyanaconda/ui/tui/spokes/network.py:149
#, python-format
msgid " IPv6 Address: %(addr)s/%(prefix)d\n"
msgstr "IPv6 アドレス: %(addr)s/%(prefix)d\n"

#: pyanaconda/ui/tui/spokes/network.py:163
#, python-format
msgid "Host name: %s\n"
msgstr "ホスト名: %s\n"

#: pyanaconda/ui/tui/spokes/network.py:165
#, python-format
msgid "Current host name: %s\n"
msgstr "現在のホスト名: %s\n"

#: pyanaconda/ui/tui/spokes/network.py:177
msgid "Set host name"
msgstr "ホスト名の指定"

#: pyanaconda/ui/tui/spokes/network.py:179
#, python-format
msgid "Configure device %s"
msgstr "デバイス %s の設定"

#: pyanaconda/ui/tui/spokes/network.py:198
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:6
#: pyanaconda/ui/gui/spokes/network.glade.h:51
msgid "Host name"
msgstr "ホスト名"

#: pyanaconda/ui/tui/spokes/network.py:232
msgid "Configuration not saved: netmask missing in static configuration"
msgstr "設定を保存できません。静的設定にネットマスクがありません"

#: pyanaconda/ui/tui/spokes/network.py:250
msgid "Can't apply configuration, device activation failed."
msgstr "設定を適用できません。デバイスのアクティベーションに失敗しました。"

#: pyanaconda/ui/tui/spokes/network.py:292
#: pyanaconda/ui/gui/spokes/network.py:1597
#: pyanaconda/ui/gui/spokes/network.py:1616
#: pyanaconda/ui/gui/spokes/network.py:1686
#: pyanaconda/ui/gui/spokes/network.py:1702
#, python-format
msgid "Host name is not valid: %s"
msgstr "ホスト名が有効ではありません: %s"

#: pyanaconda/ui/tui/spokes/network.py:321
msgid "Device configuration"
msgstr "デバイスの設定"

#: pyanaconda/ui/tui/spokes/network.py:325
#, python-format
msgid "IPv4 address or %s for DHCP"
msgstr "IPv4 アドレス もしくは %s に対する DHCP"

#: pyanaconda/ui/tui/spokes/network.py:327
msgid "IPv4 netmask"
msgstr "IPv4 ネットマスク"

#: pyanaconda/ui/tui/spokes/network.py:328
msgid "IPv4 gateway"
msgstr "IPv4 ゲートウェイ"

#: pyanaconda/ui/tui/spokes/network.py:329
#, python-format
msgid ""
"IPv6 address[/prefix] or %(auto)s for automatic, %(dhcp)s for DHCP, "
"%(ignore)s to turn off"
msgstr ""
"IPv6 アドレス [/プレフィックス]、または  %(auto)s (自動取得)、%(dhcp)s "
"(DHCP)、%(ignore)s (機能をオフ)"

#: pyanaconda/ui/tui/spokes/network.py:332
msgid "IPv6 default gateway"
msgstr "IPv6 デフォルトゲートウェイ"

#: pyanaconda/ui/tui/spokes/network.py:333
msgid "Nameservers (comma separated)"
msgstr "DNSサーバー (カンマ区切り)"

#: pyanaconda/ui/tui/spokes/network.py:339
msgid "Connect automatically after reboot"
msgstr "再起動後に自動的に接続"

#: pyanaconda/ui/tui/spokes/network.py:340
msgid "Apply configuration in installer"
msgstr "インストーラーの設定を適用"

#: pyanaconda/ui/tui/spokes/network.py:363
#, python-format
msgid "Configuring device %s."
msgstr "デバイス %s の設定。"

#: pyanaconda/ui/tui/spokes/network.py:368
msgid "Bad format of the IP address"
msgstr "不正な IP アドレス形式です"

#: pyanaconda/ui/tui/spokes/network.py:375
msgid "Bad format of the netmask"
msgstr "不正なネットマスク形式です"

#: pyanaconda/ui/tui/spokes/password.py:32
msgid "Root password"
msgstr "Root パスワード"

#: pyanaconda/ui/tui/spokes/password.py:57
msgid "Password is set."
msgstr "パスワードは設定されています。"

#: pyanaconda/ui/tui/spokes/password.py:59
msgid "Root account is disabled."
msgstr "root アカウントは無効になっています。"

#: pyanaconda/ui/tui/spokes/password.py:61
msgid "Password is not set."
msgstr "パスワードが設定されていません。"

#: pyanaconda/ui/tui/spokes/password.py:66
msgid "Please select new root password. You will have to type it twice."
msgstr "新しい root パスワードを選択して下さい。2 回入力する必要があります。"

#: pyanaconda/ui/tui/spokes/storage.py:56
msgid "Use All Space"
msgstr "すべての領域を使用する"

#: pyanaconda/ui/tui/spokes/storage.py:57
msgid "Replace Existing Linux system(s)"
msgstr "既存の Linux システムを入れ替える"

#: pyanaconda/ui/tui/spokes/storage.py:58
msgid "Use Free Space"
msgstr "空き領域を使用する"

#: pyanaconda/ui/tui/spokes/storage.py:68
msgid "Installation Destination"
msgstr "インストール先"

#: pyanaconda/ui/tui/spokes/storage.py:128
#: pyanaconda/ui/gui/spokes/storage.py:439
msgid "No disks selected"
msgstr "ディスクが選択されていません"

#: pyanaconda/ui/tui/spokes/storage.py:138
#: pyanaconda/ui/gui/spokes/storage.py:451
msgid "Error checking storage configuration"
msgstr "ストレージ設定のチェック中にエラー"

#: pyanaconda/ui/tui/spokes/storage.py:140
#: pyanaconda/ui/gui/spokes/storage.py:453
msgid "Warning checking storage configuration"
msgstr "ストレージ設定チェックに警告"

#: pyanaconda/ui/tui/spokes/storage.py:143
#: pyanaconda/ui/gui/spokes/storage.py:455
msgid "Automatic partitioning selected"
msgstr "自動パーティション設定が選択されました"

#: pyanaconda/ui/tui/spokes/storage.py:145
#: pyanaconda/ui/gui/spokes/storage.py:457
msgid "Custom partitioning selected"
msgstr "カスタムパーティション設定が選択されました"

#: pyanaconda/ui/tui/spokes/storage.py:181
#: pyanaconda/ui/gui/spokes/storage.py:717
msgid ""
"No disks detected.  Please shut down the computer, connect at least one "
"disk, and restart to complete installation."
msgstr ""
"ディスクが検出されません。コンピューターをシャットダウンして 1 つ以上のディス"
"クに接続し、再開するとインストールが完了できます。"

#: pyanaconda/ui/tui/spokes/storage.py:183
#: pyanaconda/ui/gui/spokes/storage.py:721
msgid "No disks selected; please select at least one disk to install to."
msgstr ""
"ディスクが選択されていません。インストール先として少なくともディスクを１つ選"
"択して下さい。"

#: pyanaconda/ui/tui/spokes/storage.py:198
#: pyanaconda/ui/tui/spokes/source.py:397
#: pyanaconda/ui/gui/spokes/source.py:697
#: pyanaconda/ui/gui/spokes/storage.py:665
msgid "Probing storage..."
msgstr "ストレージを検出中..."

#: pyanaconda/ui/tui/spokes/storage.py:219
msgid "Select all"
msgstr "すべて選択"

#: pyanaconda/ui/tui/spokes/storage.py:346
msgid ""
"The following unformatted or LDL DASDs have been detected on your system. "
"You can choose to format them now with dasdfmt or cancel to leave them "
"unformatted. Unformatted DASDs cannot be used during installation.\n"
"\n"
msgstr ""
"システムで、以下の未フォーマットまたは Linux ディスクレイアウトの DASD (直接"
"アクセス記憶装置) が検出されました。デバイスを選択して dasdfmt でフォーマット"
"化するか、取り消して未フォーマットのままにするか選択します。未フォーマットの "
"DASD は、インストール中に使用できません。\n"
"\n"

#: pyanaconda/ui/tui/spokes/storage.py:351
msgid ""
"Warning: All storage changes made using the installer will be lost when you "
"choose to format.\n"
"\n"
"Proceed to run dasdfmt?\n"
msgstr ""
"警告: インストーラーを使って行なった変更は、初期化を選択すると失われます。\n"
"\n"
"dasdfmt の実行を行いますか？\n"

#: pyanaconda/ui/tui/spokes/storage.py:369
#: pyanaconda/ui/gui/spokes/lib/dasdfmt.py:94
#, python-format
msgid "Formatting /dev/%s. This may take a moment."
msgstr "/dev/%s を初期化中です。少々お待ちください..."

#: pyanaconda/ui/tui/spokes/storage.py:437
msgid "Generating updated storage configuration"
msgstr "更新したストレージ設定を生成中"

#: pyanaconda/ui/tui/spokes/storage.py:442
#: pyanaconda/ui/tui/spokes/storage.py:454
#, python-format
msgid "storage configuration failed: %s"
msgstr "ストレージの設定に失敗しました: %s"

#: pyanaconda/ui/tui/spokes/storage.py:501
#: pyanaconda/ui/tui/spokes/storage.py:549
msgid "Passphrase"
msgstr "パスフレーズ"

#: pyanaconda/ui/tui/spokes/storage.py:543
msgid "Please provide LUKS passphrase. You will have to type it twice."
msgstr "LUKS パスフレーズを入力してください。2 回入力する必要があります。"

#: pyanaconda/ui/tui/spokes/storage.py:570
msgid "Autopartitioning Options"
msgstr "自動パーティション設定のオプション"

#: pyanaconda/ui/tui/spokes/storage.py:597
msgid ""
"Installation requires partitioning of your hard drive. Select what space to "
"use for the install target."
msgstr ""
"インストールには、ハードディスクのパーティション設定が必要です。インストール"
"先として使用する領域を選択して下さい。"

#: pyanaconda/ui/tui/spokes/storage.py:637
msgid "Partition Scheme Options"
msgstr "パーティションスキーマのオプション"

#: pyanaconda/ui/tui/spokes/storage.py:661
msgid "Select a partition scheme configuration."
msgstr "パーティションスキーマの設定を選択してください。"

#: pyanaconda/ui/tui/spokes/time_spoke.py:41
msgid "status: working"
msgstr "状態: 稼働中"

#: pyanaconda/ui/tui/spokes/time_spoke.py:42
msgid "status: not working"
msgstr "状態: 非稼働中"

#: pyanaconda/ui/tui/spokes/time_spoke.py:43
msgid "checking status"
msgstr "状態の確認"

#: pyanaconda/ui/tui/spokes/time_spoke.py:53
msgid "Time settings"
msgstr "時間の設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:189
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:542
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:548
#, python-format
msgid "%s timezone"
msgstr "%s タイムゾーン"

#: pyanaconda/ui/tui/spokes/time_spoke.py:191
msgid "Timezone is not set."
msgstr "タイムゾーンが設定されていません。"

#: pyanaconda/ui/tui/spokes/time_spoke.py:201
msgid "not set"
msgstr "未設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:205
#, python-format
msgid "Timezone: %s\n"
msgstr "タイムゾーン: %s\n"

#: pyanaconda/ui/tui/spokes/time_spoke.py:211
#: pyanaconda/ui/tui/spokes/time_spoke.py:394
msgid "NTP servers:"
msgstr "NTP サーバー:"

#: pyanaconda/ui/tui/spokes/time_spoke.py:216
msgid "not configured"
msgstr "未設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:227
msgid "Change timezone"
msgstr "タイムゾーンの変更"

#: pyanaconda/ui/tui/spokes/time_spoke.py:229
msgid "Set timezone"
msgstr "タイムゾーンの設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:231
msgid "Configure NTP servers"
msgstr "NTP サーバーの設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:276
msgid "Timezone settings"
msgstr "タイムゾーンの設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:303
#, python-format
msgid "Available timezones in region %s"
msgstr "地域 %s で使用できるタイムゾーン"

#: pyanaconda/ui/tui/spokes/time_spoke.py:306
msgid "Available regions"
msgstr "使用できる地域"

#. TRANSLATORS: 'b' to go back
#: pyanaconda/ui/tui/spokes/time_spoke.py:345
msgctxt "TUI|Spoke Navigation|Timezone Settings"
msgid "b"
msgstr "b"

#: pyanaconda/ui/tui/spokes/time_spoke.py:369
#, python-format
msgid ""
"Please select the timezone.\n"
"Use numbers or type names directly [%(back)s to region list, %(quit)s to "
"quit]: "
msgstr ""
"タイムゾーンを選択してください。\n"
"番号を使用するか、タイプ名を直接入力します [%(back)s 地域一覧に戻"
"る、%(quit)s 終了する]: "

#. TRANSLATORS: 'b' to go back
#: pyanaconda/ui/tui/spokes/time_spoke.py:371
msgctxt "TUI|Spoke Navigation|Time Settings"
msgid "b"
msgstr "b"

#. TRANSLATORS:'q' to quit
#: pyanaconda/ui/tui/spokes/time_spoke.py:373
msgctxt "TUI|Spoke Navigation|Time Settings"
msgid "q"
msgstr "q"

#: pyanaconda/ui/tui/spokes/time_spoke.py:381
msgid "NTP configuration"
msgstr "NTP 設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:399
msgid "no NTP servers have been configured"
msgstr "NTP サーバーは設定されていません"

#: pyanaconda/ui/tui/spokes/time_spoke.py:408
msgid "Add NTP server"
msgstr "NTP サーバーの追加"

#: pyanaconda/ui/tui/spokes/time_spoke.py:411
msgid "Remove NTP server"
msgstr "NTP サーバーの削除"

#: pyanaconda/ui/tui/spokes/time_spoke.py:454
msgid "Add NTP server address"
msgstr "NTP サーバーアドレスの追加"

#: pyanaconda/ui/tui/spokes/time_spoke.py:473
msgid "Enter an NTP server address and press enter\n"
msgstr "NTP サーバーアドレスを入力して Enter を押します\n"

#: pyanaconda/ui/tui/spokes/time_spoke.py:492
msgid "Select an NTP server to remove"
msgstr "削除する NTP サーバーを選択"

#: pyanaconda/ui/tui/spokes/shell_spoke.py:33
msgid "Shell"
msgstr "シェル"

#: pyanaconda/ui/tui/spokes/shell_spoke.py:48
msgid "Start shell"
msgstr "シェルの開始"

#: pyanaconda/ui/tui/spokes/shell_spoke.py:57
msgid "Exit the shell to continue"
msgstr "シェルを終了して続行します"

#: pyanaconda/ui/tui/spokes/source.py:54
msgid "Installation source"
msgstr "インストールソース"

#: pyanaconda/ui/tui/spokes/source.py:57 pyanaconda/ui/tui/spokes/source.py:128
#: pyanaconda/ui/gui/spokes/source.py:581
#: pyanaconda/ui/gui/spokes/source.glade.h:25
msgid "Closest mirror"
msgstr "最寄りのミラー"

#: pyanaconda/ui/tui/spokes/source.py:118
#: pyanaconda/ui/gui/spokes/source.py:571
#, python-format
msgid "NFS server %s"
msgstr "NFS サーバー %s"

#: pyanaconda/ui/tui/spokes/source.py:120
#: pyanaconda/ui/gui/spokes/source.py:573
msgid "Local media"
msgstr "ローカルメディア"

#: pyanaconda/ui/tui/spokes/source.py:122
#: pyanaconda/ui/gui/spokes/source.py:575
msgid "Local media via SE/HMC"
msgstr "SE/HMC を用いたローカルメディア"

#: pyanaconda/ui/tui/spokes/source.py:125
#: pyanaconda/ui/tui/spokes/source.py:139
#: pyanaconda/ui/gui/spokes/source.py:567
msgid "Error setting up software source"
msgstr "ソフトウェアソースの設定でエラー"

#: pyanaconda/ui/tui/spokes/source.py:130
#: pyanaconda/ui/tui/spokes/software.py:104
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:550
#: pyanaconda/ui/gui/spokes/software.py:294
#: pyanaconda/ui/gui/spokes/software.py:302
#: pyanaconda/ui/gui/spokes/source.py:583
msgid "Nothing selected"
msgstr "何も選択されていません"

#: pyanaconda/ui/tui/spokes/source.py:141
#: pyanaconda/ui/tui/spokes/software.py:92
msgid "Processing..."
msgstr "処理中..."

#: pyanaconda/ui/tui/spokes/source.py:159
#: pyanaconda/ui/gui/spokes/source.py:914
msgid ""
"The installation source is in use by the installer and cannot be changed."
msgstr ""
"インストールソースはインストーラーに使用されているため、変更できません。"

#: pyanaconda/ui/tui/spokes/source.py:163
msgid "CD/DVD"
msgstr "CD/DVD"

#: pyanaconda/ui/tui/spokes/source.py:163
msgid "local ISO file"
msgstr "ローカル ISO ファイル"

#: pyanaconda/ui/tui/spokes/source.py:163
msgid "Network"
msgstr "ネットワーク"

#: pyanaconda/ui/tui/spokes/source.py:166
msgid "SE/HMC"
msgstr "SE/HMC"

#: pyanaconda/ui/tui/spokes/source.py:171
msgid "Choose an installation source type."
msgstr "インストールソースのタイプを選択してください。"

#: pyanaconda/ui/tui/spokes/source.py:274
#: pyanaconda/ui/tui/spokes/source.py:312
msgid "Specify Repo Options"
msgstr "リポジトリーオプションを指定"

#: pyanaconda/ui/tui/spokes/source.py:278
msgid "Repo URL"
msgstr "リポジトリーのURL"

#: pyanaconda/ui/tui/spokes/source.py:316
msgid "<server>:/<path>"
msgstr "<server>:/<path>"

#: pyanaconda/ui/tui/spokes/source.py:317
msgid "NFS mount options"
msgstr "NFS マウントオプション"

#: pyanaconda/ui/tui/spokes/source.py:359
msgid "Select device containing the ISO file"
msgstr "ISO ファイルが格納されたデバイスを選択"

#: pyanaconda/ui/tui/spokes/source.py:418
msgid "No mountable devices found"
msgstr "マウント可能なデバイスが見つかりません"

#: pyanaconda/ui/tui/spokes/source.py:446
msgid "Select an ISO to use as install source"
msgstr "インストールソースとして使用する ISO ファイルを選択"

#: pyanaconda/ui/tui/spokes/source.py:475
msgid "No *.iso files found in device root folder"
msgstr ""
"デバイスのルートディレクトリーで、拡張子 *.iso のファイルが見つかりません"

#: pyanaconda/ui/tui/spokes/software.py:39
msgid "Software selection"
msgstr "ソフトウェアの選択"

#: pyanaconda/ui/tui/spokes/software.py:90
#: pyanaconda/ui/gui/spokes/software.py:275
msgid "Error checking software selection"
msgstr "ソフトウェアの選択をチェック中にエラー"

#: pyanaconda/ui/tui/spokes/software.py:94
#: pyanaconda/ui/gui/spokes/software.py:278
msgid "Installation source not set up"
msgstr "インストールソースが設定されていません"

#: pyanaconda/ui/tui/spokes/software.py:96
#: pyanaconda/ui/gui/spokes/software.py:281
msgid "Source changed - please verify"
msgstr "ソースが変更されました。検証してください"

#: pyanaconda/ui/tui/spokes/software.py:103
#: pyanaconda/ui/gui/spokes/software.py:288
msgid "Custom software selected"
msgstr "カスタムソフトウェアが選択されています"

#: pyanaconda/ui/tui/spokes/software.py:128
msgid "Installation source needs to be set up first."
msgstr "インストールソースは最初に設定する必要があります。"

#: pyanaconda/ui/tui/spokes/software.py:138
#: pyanaconda/ui/tui/spokes/software.py:148
msgid "Base environment"
msgstr "ベース環境"

#: pyanaconda/ui/tui/spokes/software.py:232
msgid "Checking software selection"
msgstr "ソフトウェアの選択を確認中"

#: pyanaconda/ui/tui/spokes/user.py:37
msgid "User creation"
msgstr "ユーザー作成"

#: pyanaconda/ui/tui/spokes/user.py:124 pyanaconda/ui/gui/spokes/user.py:377
msgid "No user will be created"
msgstr "ユーザーは作成されません"

#: pyanaconda/ui/tui/spokes/user.py:126
msgid "You must set a password"
msgstr "パスワードを設定してください"

#: pyanaconda/ui/tui/spokes/user.py:128 pyanaconda/ui/gui/spokes/user.py:379
#, python-format
msgid "Administrator %s will be created"
msgstr "管理者 %s が作成されます"

#: pyanaconda/ui/tui/spokes/user.py:130 pyanaconda/ui/gui/spokes/user.py:381
#, python-format
msgid "User %s will be created"
msgstr "ユーザー %s が作成されます"

#: pyanaconda/ui/tui/spokes/user.py:140
msgid "Full name can't contain the ':' character"
msgstr "フルネームには ':' 文字を使用できません"

#: pyanaconda/ui/tui/spokes/user.py:145
msgid ""
"Either a group name in the group list is invalid or groups are not separated "
"by a comma"
msgstr ""
"グループ一覧のグループ名が無効か、またはグループがカンマで区切られていません"

#: pyanaconda/ui/tui/spokes/user.py:155
#, python-format
msgid ""
"Invalid user name: %(name)s.\n"
"%(error_message)s"
msgstr ""
"無効なユーザー名: %(name)s\n"
"\n"
"%(error_message)s"

#: pyanaconda/ui/tui/spokes/warnings.py:36
msgid "Warnings"
msgstr "警告"

#: pyanaconda/ui/tui/spokes/warnings.py:45
#: pyanaconda/ui/gui/spokes/welcome.glade.h:21
msgid ""
"This hardware (or a combination thereof) is not supported by Red Hat.  For "
"more information on supported hardware, please refer to http://www.redhat."
"com/hardware."
msgstr ""
"Red Hat は、このハードウェア (またはその組み合わせ) をサポートしていません。"
"サポートされているハードウェアの詳細は、http://www.redhat.com/hardware を参照"
"してください。"

#: pyanaconda/ui/tui/spokes/progress.py:37
msgid "Progress"
msgstr "進行状況"

#: pyanaconda/ui/tui/spokes/progress.py:141
#, python-format
msgid ""
"\tUse of this product is subject to the license agreement found at %s\n"
"\n"
"\tInstallation complete.  Press return to quit"
msgstr ""
"\t本製品の使用は、 %s で定められている使用許諾契約の対象となります\n"
"\n"
"\tインストールが完了しました。Enter を押すと終了します。"

#: pyanaconda/ui/tui/spokes/__init__.py:50
msgid "Default spoke title"
msgstr "デフォルトのスポークタイトル"

#: pyanaconda/ui/tui/spokes/__init__.py:62
msgid "testing status..."
msgstr "状態をテスト中..."

#: pyanaconda/ui/tui/spokes/__init__.py:107
msgid "New value"
msgstr "新しい値"

#: pyanaconda/ui/tui/spokes/__init__.py:145
#, python-format
msgid "%s: "
msgstr "%s: "

#: pyanaconda/ui/tui/spokes/__init__.py:146
#, python-format
msgid "%s (confirm): "
msgstr "%s (確認): "

#: pyanaconda/ui/tui/spokes/__init__.py:169
msgid ""
"\n"
"Would you like to use it anyway?"
msgstr ""
"\n"
"それでも、このパスワードを使用しますか？"

#: pyanaconda/ui/tui/spokes/__init__.py:193
#, python-format
msgid "Enter new value for '%s' and press enter\n"
msgstr "'%s' に新しい値を入力して 'Enter' を押します\n"

#: pyanaconda/ui/tui/spokes/__init__.py:212
msgid "You have provided an invalid value\n"
msgstr ""
"無効な値を入力しています\n"
"\n"

#: pyanaconda/ui/tui/spokes/__init__.py:325
msgid "Password set."
msgstr "パスワードの指定。"

#: pyanaconda/ui/gui/__init__.py:391 widgets/src/BaseWindow.c:157
msgid "Help!"
msgstr "ヘルプ"

#: pyanaconda/ui/gui/__init__.py:873 widgets/src/StandaloneWindow.c:49
msgid "_Quit"
msgstr "終了(_Q)"

#: pyanaconda/ui/gui/__init__.py:889
msgid "_No"
msgstr "いいえ(_N)"

#: pyanaconda/ui/gui/__init__.py:889
msgid "_Yes"
msgstr "はい(_Y)"

#: pyanaconda/ui/gui/hubs/__init__.py:256
msgid ""
"Please complete items marked with this icon before continuing to the next "
"step."
msgstr ""
"このアイコンの付いた項目の設定を済ませてから、次のステップへ進んでください。"

#: pyanaconda/ui/gui/hubs/progress.py:116
msgid "Complete!"
msgstr "インストールが完了しました!"

#: pyanaconda/ui/gui/hubs/progress.py:144
#, python-format
msgid "Use of this product is subject to the license agreement found at %s"
msgstr "本製品の使用は、以下 %s に定められている使用許諾契約の対象となります"

#: pyanaconda/ui/gui/hubs/progress.py:220
#, python-format
msgid ""
"%s is now successfully installed on your system and ready for you to use!  "
"When you are ready, reboot your system to start using it!"
msgstr ""
"%s がシステムに正常にインストールされ、使用準備が整いました。使用を開始するた"
"めシステムを再起動してください！"

#: pyanaconda/ui/gui/hubs/progress.py:223
msgctxt "GUI|Progress"
msgid "_Quit"
msgstr "終了 (_Q)"

#: pyanaconda/ui/gui/hubs/progress.py:231
#, python-format
msgid ""
"%s is now successfully installed, but some configuration still needs to be "
"done.\n"
"Finish it and then click the Finish configuration button please."
msgstr ""
"%s は正しくインストールされましたが、設定が必要な項目が残っています。\n"
"必要な設定をすべて完了してから「設定完了」ボタンをクリックしてください。"

#: pyanaconda/ui/gui/hubs/progress.py:236
#, python-format
msgid ""
"%s is now successfully installed and ready for you to use!\n"
"Go ahead and reboot to start using it!"
msgstr ""
"%s が正しくインストールされ、使用準備が整いました。\n"
"使用開始するには再起動してください。"

#: pyanaconda/ui/gui/hubs/summary.py:81
msgid ""
"Warning: Processor has Simultaneous Multithreading (SMT) enabled.  <a href="
"\"\">Click for details.</a>"
msgstr ""
"警告: プロセッサーで、同時マルチスレッディング (SMT) が有効になっています。"
"<a href=\"\">Click for details.</a>"

#: pyanaconda/ui/gui/hubs/summary.py:91
msgid ""
"The following warnings were encountered when checking your kernel "
"configuration. These are not fatal, but you may wish to make changes to your "
"kernel config."
msgstr ""
"Kernel 設定のチェック時に以下の警告が発生しました。致命的ではありませんが、"
"kernel 設定を変更することをおすすめします。"

#: pyanaconda/ui/gui/hubs/summary.py:99
msgctxt "GUI|Summary|Warning Dialog"
msgid "_OK"
msgstr "_OK"

#: pyanaconda/ui/gui/spokes/custom.py:114
#, python-format
msgid "Create a new %(container_type)s ..."
msgstr "新規 %(container_type)s を作成中 ..."

#: pyanaconda/ui/gui/spokes/custom.py:115
#, python-format
msgid "Create or select %(container_type)s"
msgstr "%(container_type)s を作成または選択"

#: pyanaconda/ui/gui/spokes/custom.py:117
msgid "Device reconfiguration failed. <a href=\"\">Click for details.</a>"
msgstr ""
"デバイスの再設定に失敗しました。<a href=\"\">クリックすると詳細を表示します。"
"</a>"

#: pyanaconda/ui/gui/spokes/custom.py:119
msgid ""
"Storage configuration reset due to unrecoverable error. <a href=\"\">Click "
"for details.</a>"
msgstr ""
"復元不可能なエラーにより、ストレージ設定がリセットされました。<a href=\"\">ク"
"リックすると詳細を表示します。</a>"

#: pyanaconda/ui/gui/spokes/custom.py:143
#: pyanaconda/ui/gui/spokes/custom.glade.h:12
msgid "MANUAL PARTITIONING"
msgstr "手動パーティション設定"

#: pyanaconda/ui/gui/spokes/custom.py:369
#, python-format
msgctxt "GUI|Custom Partitioning"
msgid "%d _storage device selected"
msgid_plural "%d _storage devices selected"
msgstr[0] "%d 個のストレージデバイスが選択されています(_S)"

#: pyanaconda/ui/gui/spokes/custom.py:522
#, python-format
msgid ""
"When you create mount points for your %(name)s %(version)s installation, "
"you'll be able to view their details here."
msgstr ""
"%(name)s %(version)s をインストールするマウントポイントを作成すると、ここでそ"
"の詳細を確認できます。"

#: pyanaconda/ui/gui/spokes/custom.py:676
#, python-format
msgid ""
"/boot/efi must be on a device of type %(oneFsType)s or %(anotherFsType)s"
msgstr ""
"/boot/efi は、%(oneFsType)s または %(anotherFsType)s のデバイスに配置してくだ"
"さい。"

#: pyanaconda/ui/gui/spokes/custom.py:680
#, python-format
msgid "%(fs)s must be on a device of type %(type)s"
msgstr "%(fs)s は、タイプ %(type)s のデバイス上でなければなりません"

#: pyanaconda/ui/gui/spokes/custom.py:683
#: pyanaconda/ui/gui/spokes/custom.py:685
#, python-format
msgid "%s cannot be encrypted"
msgstr "%s は暗号化できません"

#: pyanaconda/ui/gui/spokes/custom.py:687
msgid "You must create a new file system on the root device."
msgstr "新しいファイルシステムは、root デバイス上に作成する必要があります。"

#: pyanaconda/ui/gui/spokes/custom.py:692
#, python-format
msgid "Device does not support RAID level selection %s."
msgstr "デバイスは、RAID レベル選択 %s をサポートしていません。"

#: pyanaconda/ui/gui/spokes/custom.py:800
msgid "Device resize request failed. <a href=\"\">Click for details.</a>"
msgstr ""
"デバイスのサイズ変更要求に失敗しました。<a href=\"\">クリックすると詳細を表示"
"します。</a>"

#: pyanaconda/ui/gui/spokes/custom.py:873
msgid "Device reformat request failed. <a href=\"\">Click for details.</a>"
msgstr ""
"デバイスの再フォーマット要求に失敗しました。<a href=\"\">クリックすると詳細を"
"表示します。</a>"

#: pyanaconda/ui/gui/spokes/custom.py:1239
#, python-format
msgid "Specified name %s already in use."
msgstr "指定された名前 %s はすでに存在します。"

#: pyanaconda/ui/gui/spokes/custom.py:1397
msgid "No disks assigned"
msgstr "ディスクが割り当てられていません"

#: pyanaconda/ui/gui/spokes/custom.py:1403
#, python-format
msgctxt "GUI|Custom Partitioning|Devices"
msgid " and %d other"
msgid_plural " and %d others"
msgstr[0] "その他 %d 個"

#: pyanaconda/ui/gui/spokes/custom.py:1464
msgid "The container is encrypted."
msgstr "コンテナーは暗号化されています。"

#: pyanaconda/ui/gui/spokes/custom.py:1507
msgid ""
"The space available to this mount point can be changed by modifying the "
"volume below."
msgstr ""
"以下のボリュームを変更することによって、このマウントポイントが使用できる空き"
"領域を変更することができます。"

#: pyanaconda/ui/gui/spokes/custom.py:1509
msgid "This file system may not be resized."
msgstr "このファイルシステムはリサイズできません。"

#: pyanaconda/ui/gui/spokes/custom.py:1565
msgid ""
"Error checking storage configuration.  <a href=\"\">Click for details</a> or "
"press Done again to continue."
msgstr ""
"ストレージ構成のチェック中にエラーが発生しました。<a href=\"\">クリックして詳"
"細を表示させる</a> か、完了をもう一度押して続行します。"

#: pyanaconda/ui/gui/spokes/custom.py:1567
msgid ""
"Warning checking storage configuration.  <a href=\"\">Click for details</a> "
"or press Done again to continue."
msgstr ""
"ストレージ構成のチェック中に警告が発生しました。<a href=\"\">クリックして詳細"
"を表示させる</a> か、完了をもう一度押して続行します。"

#: pyanaconda/ui/gui/spokes/custom.py:1675
#, python-format
msgid "Added new %(type)s to existing container %(name)s."
msgstr "新しい %(type)s をすでに存在するコンテナー %(name)s へ追加しました。"

#: pyanaconda/ui/gui/spokes/custom.py:1686
msgid "Failed to add new device. <a href=\"\">Click for details.</a>"
msgstr ""
"新規デバイスの追加に失敗しました。<a href=\"\">クリックすると詳細を表示します"
"</a>。"

#: pyanaconda/ui/gui/spokes/custom.py:1691
msgid "Invalid partition size set. Use a valid integer."
msgstr ""
"無効なパーティション容量が設定されました。有効な範囲の整数を使用してくださ"
"い。"

#: pyanaconda/ui/gui/spokes/custom.py:1802
msgid "Device removal request failed. <a href=\"\">Click for details.</a>"
msgstr ""
"デバイスの除去要求は失敗しました。<a href=\"\">クリックすると詳細を表示しま"
"す。</a>"

#: pyanaconda/ui/gui/spokes/custom.py:1992
msgid "No disks selected. Keeping previous disk set."
msgstr "ディスクが選択されていません"

#: pyanaconda/ui/gui/spokes/custom.py:2050
msgid "No disks selected. Not saving changes."
msgstr "ディスクが選択されていません。変更は保存されません。"

#: pyanaconda/ui/gui/spokes/custom.py:2058
#, python-format
msgid "Volume Group name %s is already in use. Not saving changes."
msgstr "ボリュームグループ名 %s はすでに使われています。変更は保存されません。"

#: pyanaconda/ui/gui/spokes/custom.py:2090
#, python-format
msgid "(%s free)"
msgstr "(%s の空き領域)"

#: pyanaconda/ui/gui/spokes/custom.py:2247
#, python-format
msgid ""
"This Software RAID array is missing %(missingMembers)d of %(totalMembers)d "
"member partitions. You can remove it or select a different device."
msgstr ""
"このソフトウェア RAID アレイには、%(totalMembers)d メンバーパーティションのう"
"ち、%(missingMembers)d メンバーパーティションが不足しています。削除するか別の"
"デバイスを選択してください。"

#: pyanaconda/ui/gui/spokes/custom.py:2253
#, python-format
msgid ""
"This LVM Volume Group is missing %(missingPVs)d of %(totalPVs)d physical "
"volumes. You can remove it or select a different device."
msgstr ""
"この LVM のボリュームグループには、%(totalPVs)d 物理ボリュームのう"
"ち、%(missingPVs)d  物理ボリュームが不足しています。削除するか別のデバイスを"
"選択してください。"

#: pyanaconda/ui/gui/spokes/custom.py:2335
msgid "No disks selected."
msgstr "ディスクが選択されていません。"

#: pyanaconda/ui/gui/spokes/custom.py:2340
msgid "Not enough free space on selected disks."
msgstr "選択したディスクには十分な空き領域がありません。"

#: pyanaconda/ui/gui/spokes/custom.py:2345
#: pyanaconda/ui/gui/spokes/custom.py:2351
#: pyanaconda/ui/gui/spokes/custom.py:2376
msgid "Automatic partitioning failed. <a href=\"\">Click for details.</a>"
msgstr ""
"自動パーティション設定に失敗しました。<a href=\"\">クリックすると詳細を表示し"
"ます</a>。"

#: pyanaconda/ui/gui/spokes/custom.py:2590
msgid ""
"Continuing with this action will reset all your partitioning selections to "
"their current on-disk state."
msgstr ""
"この操作を行うと、パーティション設定をリセットして現在のディスク状態へ戻しま"
"す。"

#: pyanaconda/ui/gui/spokes/custom.py:2598
msgid "_Reset selections"
msgstr "選択をリセットする(_R)"

#: pyanaconda/ui/gui/spokes/custom.py:2598
msgid "_Preserve current selections"
msgstr "現在の選択を保持する(_P)"

#: pyanaconda/ui/gui/spokes/custom.py:2677
msgid ""
"Failed to unlock encrypted block device. <a href=\"\">Click for details.</a>"
msgstr ""
"暗号化されたブロックデバイスを解除できませんでした。 <a href=\"\">クリックす"
"ると詳細を表示します。</a>"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:393
msgctxt "GUI|Spoke"
msgid "DATE & _TIME"
msgstr "日付と時刻(_T)"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:530
msgid "Restoring hardware time..."
msgstr "ハードウェア時刻をリストア中..."

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:544
msgid "Invalid timezone"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:715
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:729
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:911
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:27
msgid "PM"
msgstr "PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:717
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:726
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:910
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:913
msgid "AM"
msgstr "午前"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:1065
msgid "You need to set up networking first if you want to use NTP"
msgstr "NTP を使用する場合は、ネットワークを最初に設定する必要があります"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:1069
msgid "You have no working NTP server configured"
msgstr "稼働中の NTP サーバーが設定されていません"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:1072
msgid "NTP service failed to start."
msgstr "NTP サービスの起動に失敗しました。"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:1075
msgid "NTP service failed to stop."
msgstr "NTP サービスの停止に失敗しました。"

#: pyanaconda/ui/gui/spokes/filter.py:576
msgctxt "GUI|Spoke"
msgid "_INSTALLATION DESTINATION"
msgstr "インストール先(_I)"

#: pyanaconda/ui/gui/spokes/filter.py:711
#, python-format
msgctxt "GUI|Installation Destination|Filter"
msgid "%d _storage device selected"
msgid_plural "%d _storage devices selected"
msgstr[0] "%d 個のストレージデバイスが選択されています(_S)"

#: pyanaconda/ui/gui/spokes/keyboard.py:52
#, python-format
msgid "%s to switch layouts."
msgstr "%s レイアウトの切り替え。"

#: pyanaconda/ui/gui/spokes/keyboard.py:276
msgctxt "GUI|Spoke"
msgid "_KEYBOARD"
msgstr "キーボード(_K)"

#: pyanaconda/ui/gui/spokes/keyboard.py:374
msgid "Testing layouts configuration not available."
msgstr "レイアウト設定のテストは出来ません。"

#: pyanaconda/ui/gui/spokes/keyboard.py:382
msgid "Getting list of layouts..."
msgstr "レイアウトの一覧を取得中..."

#: pyanaconda/ui/gui/spokes/keyboard.py:435
msgid ""
"Keyboard layouts are not supported when using VNC.\n"
"However the settings will be used after the installation."
msgstr ""
"VNC を使用する場合、キーボードレイアウトはサポートされません。\n"
"ただし、この設定はインストール後に使用されます。"

#: pyanaconda/ui/gui/spokes/keyboard.py:445
msgid "Layout switching not configured."
msgstr "レイアウトの切り替えは設定されていません。"

#: pyanaconda/ui/gui/spokes/langsupport.py:57
msgctxt "GUI|Spoke"
msgid "_LANGUAGE SUPPORT"
msgstr "言語サポート(_L)"

#: pyanaconda/ui/gui/spokes/network.py:96
msgid "Status unknown (missing)"
msgstr "状態は不明です (情報欠如)"

#: pyanaconda/ui/gui/spokes/network.py:99
msgid "Status unknown"
msgstr "状態は不明です"

#: pyanaconda/ui/gui/spokes/network.py:101
msgid "Unmanaged"
msgstr "管理されていません"

#: pyanaconda/ui/gui/spokes/network.py:104
#: pyanaconda/ui/gui/spokes/network.py:108
msgid "Unavailable"
msgstr "利用できません"

#: pyanaconda/ui/gui/spokes/network.py:106
msgid "Firmware missing"
msgstr "ファームウェアがありません"

#: pyanaconda/ui/gui/spokes/network.py:112
msgid "Cable unplugged"
msgstr "ケーブルが外れています"

#: pyanaconda/ui/gui/spokes/network.py:114
msgid "Disconnected"
msgstr "切断されています"

#: pyanaconda/ui/gui/spokes/network.py:119
msgid "Connecting"
msgstr "接続しています"

#: pyanaconda/ui/gui/spokes/network.py:121
msgid "Authentication required"
msgstr "認証が必要です"

#: pyanaconda/ui/gui/spokes/network.py:123
msgid "Connected"
msgstr "接続済みです"

#: pyanaconda/ui/gui/spokes/network.py:125
msgid "Disconnecting"
msgstr "切断しています"

#: pyanaconda/ui/gui/spokes/network.py:127
msgid "Connection failed"
msgstr "接続に失敗しました"

#: pyanaconda/ui/gui/spokes/network.py:327
msgid "Ethernet"
msgstr "Ethernet"

#: pyanaconda/ui/gui/spokes/network.py:328
msgid "Wireless"
msgstr "無線LAN"

#: pyanaconda/ui/gui/spokes/network.py:329
#: pyanaconda/ui/gui/spokes/network.glade.h:1
msgid "Bond"
msgstr "Bond"

#: pyanaconda/ui/gui/spokes/network.py:330
#: pyanaconda/ui/gui/spokes/network.glade.h:4
msgid "VLAN"
msgstr "VLAN"

#: pyanaconda/ui/gui/spokes/network.py:331
#: pyanaconda/ui/gui/spokes/network.glade.h:3
msgid "Team"
msgstr "チーム"

#: pyanaconda/ui/gui/spokes/network.py:332
#: pyanaconda/ui/gui/spokes/network.glade.h:2
msgid "Bridge"
msgstr "ブリッジ"

#. TRANSLATORS: ethernet cable is unplugged
#: pyanaconda/ui/gui/spokes/network.py:821
msgid "unplugged"
msgstr "外れています"

#: pyanaconda/ui/gui/spokes/network.py:917
#: pyanaconda/ui/gui/spokes/network.glade.h:16
msgid "IPv4 Address"
msgstr "IPv4 アドレス"

#: pyanaconda/ui/gui/spokes/network.py:918
#: pyanaconda/ui/gui/spokes/network.glade.h:15
msgid "IPv6 Address"
msgstr "IPv6 アドレス"

#: pyanaconda/ui/gui/spokes/network.py:920
#: pyanaconda/ui/gui/spokes/network.py:922
#: pyanaconda/ui/gui/spokes/network.glade.h:31
msgid "IP Address"
msgstr "IP アドレス"

#: pyanaconda/ui/gui/spokes/network.py:1012
#, python-format
msgid "%d Mb/s"
msgstr "%d Mb/s"

#: pyanaconda/ui/gui/spokes/network.py:1232
msgid "WEP"
msgstr "WEP"

#: pyanaconda/ui/gui/spokes/network.py:1235
msgid "WPA"
msgstr "WPA"

#: pyanaconda/ui/gui/spokes/network.py:1238
msgid "WPA2"
msgstr "WPA2"

#: pyanaconda/ui/gui/spokes/network.py:1242
msgid "Enterprise"
msgstr "Enterprise"

#: pyanaconda/ui/gui/spokes/network.py:1247 widgets/src/SpokeSelector.c:82
#: pyanaconda/ui/gui/spokes/filter.glade.h:3
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:21
msgid "None"
msgstr "なし"

#: pyanaconda/ui/gui/spokes/network.py:1388
#: pyanaconda/ui/gui/spokes/network.glade.h:61
msgid "Authentication required by wireless network"
msgstr "この無線 LAN には認証が必要です"

#: pyanaconda/ui/gui/spokes/network.py:1389
#, python-format
msgid ""
"Passwords or encryption keys are required to access\n"
"the wireless network '%(network_id)s'."
msgstr ""
"無線 LAN '%(network_id)s' にアクセスするにはパスワード\n"
"もしくは暗号キーが必要です。"

#: pyanaconda/ui/gui/spokes/network.py:1403
msgctxt "GUI|Network|Secrets Dialog"
msgid "_Password:"
msgstr "パスワード(_P):"

#: pyanaconda/ui/gui/spokes/network.py:1411
msgctxt "GUI|Network|Secrets Dialog"
msgid "_Key:"
msgstr "キー(_K):"

#: pyanaconda/ui/gui/spokes/network.py:1421
msgid "User name: "
msgstr "ユーザー名:"

#: pyanaconda/ui/gui/spokes/network.py:1432
msgid "Identity: "
msgstr "識別:"

#: pyanaconda/ui/gui/spokes/network.py:1437
msgid "Private key password: "
msgstr "秘密鍵パスワード: "

#: pyanaconda/ui/gui/spokes/network.py:1493
msgctxt "GUI|Spoke"
msgid "_NETWORK & HOST NAME"
msgstr "ネットワークとホスト名(_N)"

#: pyanaconda/ui/gui/spokes/password.py:54
msgctxt "GUI|Spoke"
msgid "_ROOT PASSWORD"
msgstr "ROOT パスワード(_R)"

#: pyanaconda/ui/gui/spokes/password.py:82
#: pyanaconda/ui/gui/spokes/password.py:83
msgid "The password is set."
msgstr "パスワードが設定されています。"

#: pyanaconda/ui/gui/spokes/password.py:117
msgid "Root password is set"
msgstr "root パスワードは設定されています"

#: pyanaconda/ui/gui/spokes/password.py:119
msgid "Root account is disabled"
msgstr "root アカウントは無効になっています"

#: pyanaconda/ui/gui/spokes/password.py:121
msgid "Root password is not set"
msgstr "root パスワードが設定されていません"

#: pyanaconda/ui/gui/spokes/software.py:56
msgctxt "GUI|Spoke"
msgid "_SOFTWARE SELECTION"
msgstr "ソフトウェアの選択(_S)"

#: pyanaconda/ui/gui/spokes/software.py:106
#: pyanaconda/ui/gui/spokes/source.py:60
msgid "Downloading package metadata..."
msgstr "パッケージメタデータをダウンロード中..."

#: pyanaconda/ui/gui/spokes/software.py:109
msgid "Downloading group metadata..."
msgstr "グループメタデータをダウンロード中..."

#: pyanaconda/ui/gui/spokes/software.py:201
#: pyanaconda/ui/gui/spokes/source.py:561
msgid "Checking software dependencies..."
msgstr "ソフトウェアの依存関係をチェック中..."

#: pyanaconda/ui/gui/spokes/software.py:206
msgid "Error checking software dependencies"
msgstr "ソフトウェアの依存関係をチェック中にエラー"

#: pyanaconda/ui/gui/spokes/software.py:291
msgid "Invalid environment specified in kickstart"
msgstr "Kickstart ファイルで不正な環境が指定されています"

#: pyanaconda/ui/gui/spokes/software.py:300
#: pyanaconda/ui/gui/spokes/software.py:307
msgid "Selected environment is not valid"
msgstr "不正な環境が選択されています"

#: pyanaconda/ui/gui/spokes/software.py:461
msgid ""
"Error checking software dependencies.  <a href=\"\">Click for details.</a>"
msgstr ""
"ソフトウェア依存性チェックでエラーが起きました。 <a href=\"\">クリックすると"
"詳細を表示します。</a>"

#: pyanaconda/ui/gui/spokes/software.py:571
msgid ""
"The software marked for installation has the following errors.  This is "
"likely caused by an error with your installation source.  You can quit the "
"installer, change your software source, or change your software selections."
msgstr ""
"インストールの印が付いたソフトウェアに、以下のエラーが発生しました。インス"
"トールソースが原因で発生した可能性があります。インストーラーを終了してソフト"
"ウェアのソースを変更するか、ソフトウェアの選択を変更してください。"

#: pyanaconda/ui/gui/spokes/software.py:576
msgctxt "GUI|Software Selection|Error Dialog"
msgid "_Quit"
msgstr "終了 (_Q)"

#: pyanaconda/ui/gui/spokes/software.py:577
msgctxt "GUI|Software Selection|Error Dialog"
msgid "_Modify Software Source"
msgstr "ソフトウェアソースを修正 (_M)"

#: pyanaconda/ui/gui/spokes/software.py:578
msgctxt "GUI|Software Selection|Error Dialog"
msgid "Modify _Selections"
msgstr "選択を修正(_S)"

#: pyanaconda/ui/gui/spokes/source.py:59
msgid "Setting up installation source..."
msgstr "インストールソースをセットアップ中..."

#: pyanaconda/ui/gui/spokes/source.py:91
msgid "Invalid proxy URL"
msgstr "無効なプロキシー URL です"

#: pyanaconda/ui/gui/spokes/source.py:96
#, python-format
msgid "Invalid proxy protocol: %s"
msgstr "無効なプロキシープロトコル: %s"

#: pyanaconda/ui/gui/spokes/source.py:102
msgid "Extra characters in proxy URL"
msgstr "プロキシー URL に余分な文字があります"

#: pyanaconda/ui/gui/spokes/source.py:106
msgid "Proxy authentication data duplicated"
msgstr "プロキシー認証データが重複しています"

#: pyanaconda/ui/gui/spokes/source.py:244
msgid "This media is good to install from."
msgstr "このメディアは、以下からのインストールに適切です。"

#: pyanaconda/ui/gui/spokes/source.py:246
msgid "This media is not good to install from."
msgstr "このメディアは、以下からのインストールに不適切です。"

#: pyanaconda/ui/gui/spokes/source.py:367
msgctxt "GUI|Spoke"
msgid "_INSTALLATION SOURCE"
msgstr "インストールソース(_I)"

#: pyanaconda/ui/gui/spokes/source.py:490
#: pyanaconda/ui/gui/spokes/source.py:716
msgid "Failed to set up installation source; check the repo url"
msgstr "インストールソースの設定に失敗しました。リポジトリーの URL を確認してください"

#: pyanaconda/ui/gui/spokes/source.py:565
msgid "Error setting up base repository"
msgstr "ベースリポジトリーのセットアップ中にエラー"

#: pyanaconda/ui/gui/spokes/source.py:578
msgid "Error setting up ISO file"
msgstr "ISO ファイルのセットアップ中にエラー"

#: pyanaconda/ui/gui/spokes/source.py:700
msgid "Testing availability..."
msgstr "アベイラビリティーをテスト中..."

#: pyanaconda/ui/gui/spokes/source.py:718
msgid ""
"Failed to set up installation source; check the repo url and proxy settings"
msgstr ""
"インストールソースの設定に失敗しました。リポジトリーの URL とプロキシーの設定"
"を確認してください。"

#: pyanaconda/ui/gui/spokes/source.py:745
#, python-format
msgid "Device: %s"
msgstr "デバイス: %s"

#: pyanaconda/ui/gui/spokes/source.py:746
#, python-format
msgid "Label: %s"
msgstr "ラベル: %s"

#: pyanaconda/ui/gui/spokes/source.py:921
msgid "You need to configure the network to use a network installation source."
msgstr ""
"ネットワーク上のインストールソースを利用する場合、ネットワークの設定が必要で"
"す。"

#: pyanaconda/ui/gui/spokes/source.py:984
msgid "URL is empty"
msgstr "URL が空です"

#: pyanaconda/ui/gui/spokes/source.py:988
msgid "Invalid URL"
msgstr "無効な URL です"

#: pyanaconda/ui/gui/spokes/source.py:1005
msgid "Protocol in URL does not match selected protocol"
msgstr "URLのプロトコルが選択されたプロトコルと一致しません"

#: pyanaconda/ui/gui/spokes/source.py:1008
msgid "NFS server is empty"
msgstr "NFSサーバーが空です"

#: pyanaconda/ui/gui/spokes/source.py:1015
msgid "Invalid host name"
msgstr "無効なホスト名です"

#: pyanaconda/ui/gui/spokes/source.py:1018
msgid "Remote directory is required"
msgstr "リモートディレクトリーは必須です"

#: pyanaconda/ui/gui/spokes/source.py:1039
msgid "Duplicate repository names."
msgstr "リポジトリー名が重複しています"

#: pyanaconda/ui/gui/spokes/source.py:1046
msgid "Empty repository name"
msgstr "リポジトリー名が空です"

#: pyanaconda/ui/gui/spokes/source.py:1049
msgid "Invalid repository name"
msgstr "無効なリポジトリー名です"

#: pyanaconda/ui/gui/spokes/source.py:1055
msgid "Repository name conflicts with internal repository name."
msgstr "内部リポジトリー名のリポジトリー名が競合しています。"

#: pyanaconda/ui/gui/spokes/storage.py:121
msgid "Please wait... software metadata still loading."
msgstr "少々お待ち下さい... ソフトウェアのメタデータがロード中です。"

#: pyanaconda/ui/gui/spokes/storage.py:122
#, python-format
msgid ""
"Your current <a href=\"\" title=\"%(tooltip)s\"><b>%(product)s</b> software "
"selection</a> requires <b>%(total)s</b> of available space, including <b>"
"%(software)s</b> for software and <b>%(swap)s</b> for swap space."
msgstr ""
"現在の <a href=\"\" title=\"%(tooltip)s\"><b>%(product)s</b> ソフトウェア選択"
"</a> には、使用可能な領域が、ソフトウェア領域用の <b>%(software)s</b>、スワッ"
"プ領域用の <b>%(swap)s</b> を含む、合計 <b>%(total)s</b> 必要になります。"

#: pyanaconda/ui/gui/spokes/storage.py:172
#, python-format
msgid "%s The disks you've selected have the following amounts of free space:"
msgstr "%s 選択したディスクには、以下の容量の空き領域があります:"

#: pyanaconda/ui/gui/spokes/storage.py:180
#, python-format
msgid ""
"<b>You don't have enough space available to install %s</b>.  You can shrink "
"or remove existing partitions via our guided reclaim space tool, or you can "
"adjust your partitions on your own in the custom partitioning interface."
msgstr ""
"<b>%s のインストールを行うのに十分な領域がありません</b>。領域を確保するツー"
"ルを使用して、既存パーティションの縮小または削除を行うことができます。ツール"
"を使用しない場合は、カスタムのパーティション設定インターフェースでパーティ"
"ションの調整を行なってください。"

#: pyanaconda/ui/gui/spokes/storage.py:204
#, python-format
msgid ""
"  You don't have enough space available to install <b>%(product)s</b>, even "
"if you used all of the free space available on the selected disks."
msgstr ""
"<b>%(product)s</b> のインストールを行うのに十分な空き容量がありません。選択し"
"たディスクで利用可能な空き容量をすべて使用しています。"

#: pyanaconda/ui/gui/spokes/storage.py:214
#, python-format
msgid ""
"<b>You don't have enough space available to install %(productName)s</b>, "
"even if you used all of the free space available on the selected disks.  You "
"could add more disks for additional space, modify your software selection to "
"install a smaller version of <b>%(productName)s</b>, or quit the installer."
msgstr ""
"選択したディスクで利用できる全ての空き領域を使用しても、<b>%(productName)s を"
"インストールするのに十分な領域</b> が確保できません。領域を増やすためにディス"
"クを追加するか、ソフトウェア選択で、必要な領域が少ない <b>%(productName)s</"
"b> に変更するか、インストーラーを終了します。"

#: pyanaconda/ui/gui/spokes/storage.py:235
msgctxt "GUI|Spoke"
msgid "INSTALLATION _DESTINATION"
msgstr "インストール先(_D)"

#: pyanaconda/ui/gui/spokes/storage.py:359
msgid "Saving storage configuration..."
msgstr "ストレージ設定を保存しています..."

#: pyanaconda/ui/gui/spokes/storage.py:363
msgid "Passphrase for autopart encryption not specified."
msgstr "ディスク暗号化用パスフレーズが指定されていません。"

#: pyanaconda/ui/gui/spokes/storage.py:372
#: pyanaconda/ui/gui/spokes/storage.py:384
msgid "Failed to save storage configuration..."
msgstr "ストレージ設定の保存に失敗しました..."

#: pyanaconda/ui/gui/spokes/storage.py:444
#: pyanaconda/ui/gui/spokes/storage.py:751
#: pyanaconda/ui/gui/spokes/storage.py:770
msgid "Formatting DASDs"
msgstr "DASD を初期化中"

#: pyanaconda/ui/gui/spokes/storage.py:590
msgid ""
"Error checking storage configuration.  <a href=\"\">Click for details.</a>"
msgstr ""
"ストレージ構成のチェック中にエラー。<a href=\"\">クリックすると詳細を表示しま"
"す。</a>"

#: pyanaconda/ui/gui/spokes/storage.py:593
msgid ""
"Warning checking storage configuration.  <a href=\"\">Click for details.</a>"
msgstr ""
"ストレージ構成のチェック中に警告。<a href=\"\">クリックすると詳細を表示しま"
"す。</a>"

#: pyanaconda/ui/gui/spokes/storage.py:637
#, python-format
msgid ""
"FCP device %(hba_id)s\n"
"WWPN %(wwpn)s\n"
"LUN %(lun)s"
msgstr ""
"FCP デバイス %(hba_id)s\n"
"WWPN %(wwpn)s\n"
"LUN %(lun)s"

#: pyanaconda/ui/gui/spokes/storage.py:640
#, python-format
msgid "NVDIMM device %(namespace)s"
msgstr "NVDIMM デバイス %(namespace)s"

#: pyanaconda/ui/gui/spokes/storage.py:649
#, python-format
msgid "%s free"
msgstr "%s 空き"

#: pyanaconda/ui/gui/spokes/storage.py:699
#, python-format
msgid "%(count)d disk selected; %(capacity)s capacity; %(free)s free"
msgid_plural "%(count)d disks selected; %(capacity)s capacity; %(free)s free"
msgstr[0] ""
"選択されたディスク数 %(count)d、容量 %(capacity)s、空き領域 %(free)s"

#: pyanaconda/ui/gui/spokes/storage.py:812
msgid ""
"You have chosen to skip boot loader installation.  Your system may not be "
"bootable."
msgstr ""
"ブートローダーのインストールを省略するよう選択しています。 システムが起動不可"
"になる可能性があります。"

#: pyanaconda/ui/gui/spokes/storage.py:914
msgid "There was a problem with your disk selection. Click here for details."
msgstr "ディスク選択中に問題が発生。クリックすると詳細を表示します。"

#: pyanaconda/ui/gui/spokes/storage.py:1089
msgid "You'll be able to make space available during custom partitioning."
msgstr ""
"カスタムのパーティション構成の間に、空き領域を利用できるようになります。"

#: pyanaconda/ui/gui/spokes/storage.py:1109
msgid ""
"The following errors were encountered when checking your disk selection. You "
"can modify your selection or quit the installer."
msgstr ""
"ディスクの選択のチェック中に以下のエラーが発生しました。ディスクの選択を変更"
"するか、インストーラーを終了してください。"

#: pyanaconda/ui/gui/spokes/storage.py:1114
#: pyanaconda/ui/gui/spokes/storage.py:1135
msgctxt "GUI|Storage|Error Dialog"
msgid "_Quit"
msgstr "終了(_Q)"

#: pyanaconda/ui/gui/spokes/storage.py:1115
msgctxt "GUI|Storage|Error Dialog"
msgid "_Modify Disk Selection"
msgstr "ディスクの選択を変更(_M)"

#: pyanaconda/ui/gui/spokes/storage.py:1130
msgid ""
"The following errors were encountered when checking your storage "
"configuration.  You can modify your storage layout or quit the installer."
msgstr ""
"ストレージ設定のチェック中に以下のエラーが発生しました。ストレージのレイアウ"
"トを変更するか、インストーラーを終了してください。"

#: pyanaconda/ui/gui/spokes/storage.py:1136
msgctxt "GUI|Storage|Error Dialog"
msgid "_Modify Storage Layout"
msgstr "ストレージ配列の修正(_M)"

#: pyanaconda/ui/gui/spokes/storage.py:1150
msgid ""
"The following warnings were encountered when checking your storage "
"configuration.  These are not fatal, but you may wish to make changes to "
"your storage layout."
msgstr ""
"ストレージ設定のチェック中に以下のような警告が発生しました。致命的ではありま"
"せんが、ストレージのレイアウトを変更することができます。"

#: pyanaconda/ui/gui/spokes/storage.py:1154
msgid "_OK"
msgstr "OK(_O)"

#: pyanaconda/ui/gui/spokes/user.py:70
#, python-format
msgid "Invalid group name: %s"
msgstr "無効なグループ名: %s"

#: pyanaconda/ui/gui/spokes/user.py:213
msgctxt "GUI|Spoke"
msgid "_USER CREATION"
msgstr "ユーザーの作成(_U)"

#: pyanaconda/ui/gui/spokes/user.py:299 pyanaconda/ui/gui/spokes/user.py:300
#: pyanaconda/ui/gui/spokes/user.py:336 pyanaconda/ui/gui/spokes/user.py:337
msgid "The password was set by kickstart."
msgstr "Kickstart ファイルからパスワードが設定されました。"

#: pyanaconda/ui/gui/spokes/user.py:328
msgid "Full name cannot contain colon characters"
msgstr "フルネームにはコロン ':' を使用できません"

#: pyanaconda/ui/gui/spokes/user.py:548
msgid "Invalid user name"
msgstr "無効なユーザー名"

#: pyanaconda/ui/gui/spokes/welcome.py:224
#, python-format
msgid "WELCOME TO %(name)s %(version)s."
msgstr "%(name)s %(version)s へようこそ。"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.py:275
#, python-format
msgid ""
"The following nodes have been discovered using the iSCSI initiator <b>"
"%(initiatorName)s</b> using the target IP address <b>%(targetAddress)s</b>.  "
"Please select which nodes you wish to log into:"
msgstr ""
"iSCSI イニシエーター <b>%(initiatorName)s</b> とターゲット IP アドレス <b>"
"%(targetAddress)s</b> の情報から、次のノードが探索されました。 ログインする"
"ノードを選択してください:"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.py:85
msgctxt "GUI|Advanced Storage|NVDIM"
msgid "No device to be reconfigured selected."
msgstr "再構成するデバイスが選択されていません。"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.py:160
msgid "Rescanning disks finished."
msgstr "ディスクの再スキャンが完了しました。"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:171
msgid "DATA"
msgstr "データ"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:293
#, python-format
msgid ""
"You haven't created any mount points for your %(product)s %(version)s "
"installation yet.  You can:"
msgstr ""
"%(product)s %(version)s をインストールするマウントポイントが作成されていませ"
"ん。次を行うことができます。"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:302
msgid "_Click here to create them automatically."
msgstr "ここをクリックして自動的に作成します(_C)。"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:327
msgid "Create new mount points by clicking the '+' button."
msgstr "「+」ボタンをクリックして新しいマウントポイントを作成する。"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:335
msgid ""
"Or, assign new mount points to existing partitions after selecting them "
"below."
msgstr ""
"既存パーティションに新しいマウントポイントを割り当てる。パーティションは以下"
"から選択する。"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:340
msgid "_New mount points will use the following partitioning scheme:"
msgstr ""
"新しいマウントポイントに次のパーティション設定スキームを使用させます (_N):"

#: pyanaconda/ui/gui/spokes/lib/cart.py:134
#, python-format
msgid ""
"<b>%(count)d disk; %(size)s capacity; %(free)s free space</b> (unpartitioned "
"and in file systems)"
msgid_plural ""
"<b>%(count)d disks; %(size)s capacity; %(free)s free space</b> "
"(unpartitioned and in file systems)"
msgstr[0] ""
"<b>ディスク数 %(count)d; 容量 %(size)s; 空き領域 %(free)s</b> (ファイルシステ"
"ムの構成、パーティション未設定)"

#: pyanaconda/ui/gui/spokes/lib/cart.py:193
msgctxt "GUI|Selected Disks Dialog"
msgid "_Do not install boot loader"
msgstr "ブートローダーをインストールしない(_D)"

#: pyanaconda/ui/gui/spokes/lib/cart.py:196
#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:8
msgctxt "GUI|Selected Disks Dialog"
msgid "_Set as Boot Device"
msgstr "ブートデバイスとして設定(_S)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:62
#, python-format
msgid ""
"The RAID level you have selected (%(level)s) requires more disks (%(min)d) "
"than you currently have selected (%(count)d)."
msgstr ""
"選択した (%(level)s) の RAID レベルには (%(min)d) 個以上のディスクが必要で"
"す。現在、 (%(count)d) 個しか選択していません。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:66
#, python-format
msgid "CONFIGURE %(container_type)s"
msgstr "%(container_type)s を設定"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:67
#, python-format
msgid ""
"Please create a name for this %(container_type)s and select at least one "
"disk below."
msgstr ""
"%(container_type)s  の名前を作成し、以下から 1 つ以上のディスクを選択してくだ"
"さい。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:70
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:71
msgid "Volume Group"
msgstr "ボリュームグループ"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:72
msgid "Volume"
msgstr "ボリューム"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:112
msgid "Cannot relabel already existing file system."
msgstr "すでに存在するファイルシステムのラベル付けを再度行うことはできません。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:117
msgid "Cannot set label on file system."
msgstr "ファイルシステムにラベルを設定できません。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:119
msgid "Unacceptable label format for file system."
msgstr "ファイルシステムには使用できないラベルの形式です。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:129
msgid "That mount point is already in use. Try something else?"
msgstr "そのマウントポイントは既に使用中です。他を試しますか?"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:131
msgid "Please enter a valid mount point."
msgstr "有効なマウントポイントを記入して下さい。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:133
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:145
msgid "That mount point is invalid. Try something else?"
msgstr "そのマウントポイントは無効です。他を試しますか?"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:286
msgid "container"
msgstr "コンテナー"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:358
#, python-format
msgctxt "GUI|Custom Partitioning|Confirm Delete Dialog"
msgid "Delete _all file systems which are only used by %s."
msgstr "%s によって使用されているファイルシステムだけをすべて削除する。(_A)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:368
#, python-format
msgid "Are you sure you want to delete all of the data on %s?"
msgstr "%s にあるすべてのデータを本当に削除してもよいですか?"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:370
#, python-format
msgid ""
"Are you sure you want to delete all of the data on %s, including snapshots "
"and/or subvolumes?"
msgstr ""
"スナップショットまたはサブボリューム、もしくはその両方を含む、 %s 上のすべて"
"のデータを削除しますか？"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:647
msgid "Invalid container name"
msgstr "無効なコンテナー名です"

#: pyanaconda/ui/gui/spokes/lib/detailederror.py:49
msgctxt "GUI|Detailed Error Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/detailederror.py:59
msgctxt "GUI|Detailed Error Dialog"
msgid "_Quit"
msgstr "終了(_Q)"

#: pyanaconda/ui/gui/spokes/lib/resize.py:58
msgid "Preserve"
msgstr "保存"

#: pyanaconda/ui/gui/spokes/lib/resize.py:59
msgid "Shrink"
msgstr "縮小"

#: pyanaconda/ui/gui/spokes/lib/resize.py:60
msgid "Delete"
msgstr "削除"

#: pyanaconda/ui/gui/spokes/lib/resize.py:87
#, python-format
msgid "Installation requires a total of <b>%s</b> for system data."
msgstr "インストールには、システムデータ用に合計 <b>%s</b> が必要です。"

#: pyanaconda/ui/gui/spokes/lib/resize.py:119
msgid "This device contains the installation source."
msgstr "インストールソースが含まれているデバイス"

#: pyanaconda/ui/gui/spokes/lib/resize.py:166
#, python-format
msgid "%(freeSize)s of %(devSize)s"
msgstr "%(freeSize)s / %(devSize)s"

#: pyanaconda/ui/gui/spokes/lib/resize.py:173
msgid "Not resizeable"
msgstr "リサイズはできません"

#: pyanaconda/ui/gui/spokes/lib/resize.py:197
msgid "Free space"
msgstr "空き領域"

#: pyanaconda/ui/gui/spokes/lib/resize.py:219
msgid ""
"You can remove existing file systems you no longer need to free up space for "
"this installation.  Removing a file system will permanently delete all of "
"the data it contains."
msgstr ""
"必要がなくなった既存のファイルシステムを削除して、このインストールに必要な領"
"域を解放してください。ファイルシステムを削除すると、そのファイルシステムに収"
"納されているすべてのデータは、永久に削除されることになります。"

#: pyanaconda/ui/gui/spokes/lib/resize.py:225
msgid ""
"There is also free space available in pre-existing file systems.  While it's "
"risky and we recommend you back up your data first, you can recover that "
"free disk space and make it available for this installation below."
msgstr ""
"既存ファイルシステムにも空き領域があります。データが失われる可能性があるた"
"め、最初にデータのバックアップを取得することが推奨されます。このディスクの空"
"き領域を確保することで、その後のインストールに利用できます。"

#: pyanaconda/ui/gui/spokes/lib/resize.py:235
#, python-format
msgid "<b>%(count)s disk; %(size)s reclaimable space</b> (in file systems)"
msgid_plural ""
"<b>%(count)s disks; %(size)s reclaimable space</b> (in file systems)"
msgstr[0] ""
"<b>%(count)s 個のディスク; %(size)s の再利用可能な領域</b> (ファイルシステム"
"内)"

#: pyanaconda/ui/gui/spokes/lib/resize.py:242
#, python-format
msgid "Total selected space to reclaim: <b>%s</b>"
msgstr "確保できる領域合計: <b>%s</b>"

#: pyanaconda/ui/gui/spokes/lib/resize.py:457
#: pyanaconda/ui/gui/spokes/lib/resize.py:462
#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:13
msgctxt "GUI|Reclaim Dialog"
msgid "Delete _all"
msgstr "すべて削除(_A)"

#: pyanaconda/ui/gui/spokes/lib/resize.py:459
msgctxt "GUI|Reclaim Dialog"
msgid "Preserve _all"
msgstr "すべて保持(_A)"

#: widgets/src/BaseWindow.c:153
msgid "DISTRIBUTION INSTALLATION"
msgstr "ディストリビューションのインストール"

#: widgets/src/BaseWindow.c:154
msgid "SPOKE NAME"
msgstr "スポーク名"

#: widgets/src/BaseWindow.c:155
msgid "PRE-RELEASE / TESTING"
msgstr "プレリリース / テスト中"

#: widgets/src/DiskOverview.c:101
msgid "New Device"
msgstr "新しいデバイス"

#: widgets/src/DiskOverview.c:103 widgets/src/DiskOverview.c:104
msgid "0 MB"
msgstr "0 MB"

#: widgets/src/MountpointSelector.c:84
msgid "0 GB"
msgstr "0 GB"

#: widgets/src/SpokeSelector.c:83
msgid "New Selector"
msgstr "新しいセレクター"

#: widgets/src/SpokeWindow.c:57
msgid "_Done"
msgstr "完了(_D)"

#: widgets/src/StandaloneWindow.c:50
msgid "_Continue"
msgstr "続行(_C)"

#: widgets/src/LayoutIndicator.c:33
#, c-format
msgid "Current layout: '%s'. Click to switch to the next layout."
msgstr "現在のレイアウト: '%s'。クリックして次のレイアウトに切り替えます。"

#: widgets/src/LayoutIndicator.c:34
#, c-format
msgid "Current layout: '%s'. Add more layouts to enable switching."
msgstr "現在のレイアウト: '%s'。クリックして次のレイアウトに切り替えます。"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:1
msgctxt "GUI|Advanced User"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:2
msgctxt "GUI|Advanced User"
msgid "_Save Changes"
msgstr "変更を保存(_S)"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:3
msgid "ADVANCED USER CONFIGURATION"
msgstr "高度なユーザー設定"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:4
msgctxt "GUI|Advanced User"
msgid "Home _directory:"
msgstr "ホームディレクトリー(_D):"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:5
msgid "User and Group IDs"
msgstr "ユーザー IDとグループ ID"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:6
msgctxt "GUI|Advanced User"
msgid "Specify a _user ID manually:"
msgstr "ユーザー ID を手動で指定する(_U):"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:7
msgctxt "GUI|Advanced User"
msgid "Specify a _group ID manually:"
msgstr "グループ ID を手動で指定する(_G):"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:8
msgid "Group Membership"
msgstr "グループメンバーシップ"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:9
msgctxt "GUI|Advanced User"
msgid "_Add user to the following groups:"
msgstr "ユーザーを次のグループに追加する(_A):"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:10
msgid "Example:"
msgstr "例:"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:11
msgid "wheel, my-team (1245), project-x (29935)"
msgstr "wheel, my-team (1245), project-x (29935)"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:12
msgid "Tip:"
msgstr "ヒント:"

#: pyanaconda/ui/gui/spokes/advanced_user.glade.h:13
msgid ""
"You may input a comma-separated list of group names and group IDs here. "
"Groups that do not already exist will be created; specify their GID in "
"parentheses. "
msgstr ""
"ここにグループ名とグループ ID の一覧をコンマ区切りで入力します。まだ存在していないグループは新規に作成されます。その GID "
"を括弧で指定してください。 "

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:1
msgctxt "GUI|Date and Time|NTP"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:2
msgctxt "GUI|Date and Time|NTP"
msgid "_OK"
msgstr "OK(_O)"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:3
msgid "Add and mark for usage NTP servers"
msgstr "使用する NTP サーバーを追加してマークする"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:4
msgid "New NTP Server"
msgstr "新しい NTP サーバー"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:5
msgid "Add NTP Server"
msgstr "NTP サーバーの追加"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:7
msgid "Working"
msgstr "稼働中"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:8
msgid "Use"
msgstr "使用"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:9
msgid "Configure NTP"
msgstr "NTP の設定"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:10
msgid "DATE & TIME"
msgstr "日付と時刻"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:11
msgctxt "GUI|Date and Time"
msgid "_Region:"
msgstr "地域(_R):"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:12
msgid "Region"
msgstr "地域"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:13
msgctxt "GUI|Date and Time"
msgid "_City:"
msgstr "都市(_C):"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:14
msgid "City"
msgstr "都市"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:15
msgctxt "GUI|Date and Time"
msgid "_Network Time"
msgstr "ネットワーク時刻(_N)"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:16
msgid "Use Network Time"
msgstr "ネットワークの時刻を使用する"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:17
msgid "Hours"
msgstr "時"

#. TRANSLATORS: This is the separator between hours and minutes, like in HH:MM
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:19
msgid ":"
msgstr ":"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:20
msgid "Minutes"
msgstr "分"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:21
msgid "Hour Up"
msgstr "時 +"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:22
msgid "Hour Down"
msgstr "時 -"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:23
msgid "AM/PM Up"
msgstr "午前/午後 +"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:24
msgid "Minutes Up"
msgstr "分 +"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:25
msgid "AM/PM Down"
msgstr "午前/午後 -"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:26
msgid "Minutes Down"
msgstr "分 -"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:28
msgctxt "GUI|Date and Time"
msgid "24-_hour"
msgstr "24 時間(_H)"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:29
msgctxt "GUI|Date and Time"
msgid "_AM/PM"
msgstr "_AM/PM(_A)"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade.h:30
msgid "Set Date & Time"
msgstr "日付と時刻の設定"

#: pyanaconda/ui/gui/spokes/filter.glade.h:1
#: pyanaconda/ui/gui/spokes/storage.glade.h:14
msgid "INSTALLATION DESTINATION"
msgstr "インストール先"

#: pyanaconda/ui/gui/spokes/filter.glade.h:2
msgctxt "GUI|Installation Destination|Filter|Search"
msgid "Search _By:"
msgstr "検索項目(_B):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:4
msgid "Port / Target / LUN #"
msgstr "ポート / ターゲット / LUN 番号"

#: pyanaconda/ui/gui/spokes/filter.glade.h:5
msgid "Target WWID"
msgstr "ターゲットの WWID"

#: pyanaconda/ui/gui/spokes/filter.glade.h:6
msgctxt "GUI|Installation Destination|Filter|Search|Port Target LUN"
msgid "_Port:"
msgstr "ポート(_P):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:7
msgctxt "GUI|Installation Destination|Filter|Search|Port Target LUN"
msgid "_Target:"
msgstr "ターゲット(_T):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:8
msgctxt "GUI|Installation Destination|Filter|Search|Port Target LUN"
msgid "_LUN:"
msgstr "LUN(_L):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:9
msgctxt "GUI|Installation Destination|Filter|Search|WWID"
msgid "_WWID:"
msgstr "WWID(_W):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:10
msgctxt "GUI|Installation Destination|Filter|Search"
msgid "Search Res_ults:"
msgstr "検索結果(_U):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:11
#: pyanaconda/ui/gui/spokes/keyboard.glade.h:18
#: pyanaconda/ui/gui/spokes/source.glade.h:34
#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:5
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:8
#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:6
msgid "Name"
msgstr "名前"

#: pyanaconda/ui/gui/spokes/filter.glade.h:12
msgid "WWID"
msgstr "WWID"

#: pyanaconda/ui/gui/spokes/filter.glade.h:13
#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:6
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:9
msgid "Capacity"
msgstr "容量"

#: pyanaconda/ui/gui/spokes/filter.glade.h:14
msgid "Interconnect"
msgstr "相互接続"

#: pyanaconda/ui/gui/spokes/filter.glade.h:15
msgid "Model"
msgstr "モデル"

#: pyanaconda/ui/gui/spokes/filter.glade.h:16
msgid "LUN"
msgstr "LUN"

#: pyanaconda/ui/gui/spokes/filter.glade.h:17
msgid "Port"
msgstr "ポート"

#: pyanaconda/ui/gui/spokes/filter.glade.h:18
msgid "Target"
msgstr "ターゲット"

#: pyanaconda/ui/gui/spokes/filter.glade.h:19
msgid "Vendor"
msgstr "ベンダー"

#: pyanaconda/ui/gui/spokes/filter.glade.h:20
msgid "Namespace"
msgstr "名前空間"

#: pyanaconda/ui/gui/spokes/filter.glade.h:21
msgid "Mode"
msgstr "モード"

#: pyanaconda/ui/gui/spokes/filter.glade.h:22
msgctxt "GUI|Installation Destination|Filter"
msgid "Searc_h"
msgstr "検索(_H)"

#: pyanaconda/ui/gui/spokes/filter.glade.h:23
msgctxt "GUI|Installation Destination|Filter|Multipath"
msgid "Filter _By:"
msgstr "フィルター項目(_B):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:24
msgctxt "GUI|Installation Destination|Filter|Multipath|Vendor"
msgid "Show Only _Devices From:"
msgstr "次から提供されるデバイスのみを表示します(_D):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:25
msgctxt "GUI|Installation Destination|Filter|Multipath|Interconnect"
msgid "Show Only _Devices With:"
msgstr "次で接続されたデバイスのみを表示します(_D):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:26
msgctxt "GUI|Installation Destination|Filter|Multipath|WWID"
msgid "Show Only _Devices Containing:"
msgstr "次を含むデバイスのみを表示します(_D):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:27
msgid "Paths"
msgstr "パス"

#: pyanaconda/ui/gui/spokes/filter.glade.h:28
msgctxt "GUI|Installation Destination|Filter"
msgid "_Multipath Devices"
msgstr "マルチパスデバイス(_M)"

#: pyanaconda/ui/gui/spokes/filter.glade.h:29
msgctxt "GUI|Installation Destination|Filter|Other"
msgid "Filter _By:"
msgstr "フィルター項目(_B):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:30
msgid "ID"
msgstr "ID"

#: pyanaconda/ui/gui/spokes/filter.glade.h:31
msgctxt "GUI|Installation Destination|Filter|Other|Vendor"
msgid "Show Only _Devices From:"
msgstr "次から提供されるデバイスのみを表示します(_D):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:32
msgctxt "GUI|Installation Destination|Filter|Other|Interconnect"
msgid "Show Only _Devices With:"
msgstr "次で接続されたデバイスのみを表示します(_D):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:33
msgctxt "GUI|Installation Destination|Filter|Other|ID"
msgid "Show Only _Devices Containing:"
msgstr "次を含むデバイスのみを表示します(_D):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:34
msgid "Identifier"
msgstr "識別子"

#: pyanaconda/ui/gui/spokes/filter.glade.h:35
msgctxt "GUI|Installation Destination|Filter"
msgid "_Other SAN Devices"
msgstr "他の SAN デバイス(_O)"

#: pyanaconda/ui/gui/spokes/filter.glade.h:36
msgctxt "GUI|Installation Destination|Filter|NVDIMM Devices"
msgid "Filter B_y:"
msgstr "フィルター(_Y):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:37
msgctxt "GUI|Installation Destination|Filter|NVDIMM Devices|Mode"
msgid "Show Only Devices in Mo_de:"
msgstr "モード(_M) のデバイスのみを表示:"

#: pyanaconda/ui/gui/spokes/filter.glade.h:38
msgid "Sector"
msgstr "セクター"

#: pyanaconda/ui/gui/spokes/filter.glade.h:39
msgid "Memory"
msgstr "メモリー"

#: pyanaconda/ui/gui/spokes/filter.glade.h:40
msgctxt "GUI|Installation Destination|Filter|NVDIMM Devices|Namespace"
msgid "Names_pace:"
msgstr "Names_pace:"

#: pyanaconda/ui/gui/spokes/filter.glade.h:41
msgctxt "GUI|Installation Destination|Filter"
msgid "_NVDIMM Devices"
msgstr "_NVDIMM デバイス"

#: pyanaconda/ui/gui/spokes/filter.glade.h:42
msgctxt "GUI|Installation Destination|Filter|zSeries"
msgid "Filter B_y:"
msgstr "フィルター(_Y):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:43
msgid "CCW"
msgstr "CCW"

#: pyanaconda/ui/gui/spokes/filter.glade.h:44
msgid "WWPN"
msgstr "WWPN"

#: pyanaconda/ui/gui/spokes/filter.glade.h:45
msgctxt "GUI|Installation Destination|Filter|zSeries|CCW"
msgid "_CCW:"
msgstr "CCW (_C):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:46
msgctxt "GUI|Installation Destination|Filter|zSeries|WWPN"
msgid "_WWPN:"
msgstr "WWPN (_W):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:47
msgctxt "GUI|Installation Destination|Filter|zSeries|LUN"
msgid "_LUN:"
msgstr "LUN(_L):"

#: pyanaconda/ui/gui/spokes/filter.glade.h:48
#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:7
msgid "Type"
msgstr "タイプ"

#: pyanaconda/ui/gui/spokes/filter.glade.h:49
msgctxt "GUI|Installation Destination|Filter"
msgid "_zSeries Devices"
msgstr "zSeries デバイス(_Z)"

#: pyanaconda/ui/gui/spokes/filter.glade.h:50
msgctxt "GUI|Installation Destination|Filter"
msgid "_Add zFCP LUN..."
msgstr "zFCP LUN を追加(_A)..."

#: pyanaconda/ui/gui/spokes/filter.glade.h:51
msgctxt "GUI|Installation Destination|Filter"
msgid "Add EC_KD DASD..."
msgstr "ECKD DASD を追加(_K)..."

#: pyanaconda/ui/gui/spokes/filter.glade.h:52
msgctxt "GUI|Installation Destination|Filter"
msgid "Add _iSCSI Target..."
msgstr "iSCSI ターゲットを追加(_I)..."

#: pyanaconda/ui/gui/spokes/filter.glade.h:53
msgctxt "GUI|Installation Destination|Filter"
msgid "Add FCo_E SAN..."
msgstr "FCoE SANを追加(_E)..."

#: pyanaconda/ui/gui/spokes/filter.glade.h:54
msgctxt "GUI|Installation Destination|Filter"
msgid "Recon_figure NVDIMM..."
msgstr "Recon_figure NVDIMM..."

#: pyanaconda/ui/gui/spokes/filter.glade.h:55
msgctxt "GUI|Installation Destination|Filter"
msgid "_Refresh List"
msgstr "一覧の更新(_R)"

#: pyanaconda/ui/gui/spokes/network.glade.h:5
msgid "Add device"
msgstr "デバイスの追加"

#: pyanaconda/ui/gui/spokes/network.glade.h:6
msgctxt "GUI|Network|Add Device Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/network.glade.h:7
msgctxt "GUI|Network|Add Device Dialog"
msgid "_Add"
msgstr "追加(_A)"

#: pyanaconda/ui/gui/spokes/network.glade.h:8
msgctxt "GUI|Network|Add Device Dialog"
msgid "_Select the type of device you wish to add"
msgstr "追加するデバイスのタイプを選択する(_S)"

#: pyanaconda/ui/gui/spokes/network.glade.h:9
msgid "NETWORK & HOST NAME"
msgstr "ネットワークとホスト名"

#: pyanaconda/ui/gui/spokes/network.glade.h:10
msgid ""
"Please use the live desktop environment's tools for customizing your network "
"configuration.  You can set the host name here."
msgstr ""
"ネットワーク設定をカスタマイズするには、Live デスクトップ環境のツールを使用し"
"てください。ここからホスト名を設定できます。"

#: pyanaconda/ui/gui/spokes/network.glade.h:11
msgid "Slaves"
msgstr "スレーブ"

#: pyanaconda/ui/gui/spokes/network.glade.h:12
msgid "DNS"
msgstr "DNS"

#: pyanaconda/ui/gui/spokes/network.glade.h:13
msgid "Default Route"
msgstr "デフォルトルート"

#: pyanaconda/ui/gui/spokes/network.glade.h:14
msgid "Subnet Mask"
msgstr "サブネットマスク"

#: pyanaconda/ui/gui/spokes/network.glade.h:17
msgid "Speed"
msgstr "速度"

#: pyanaconda/ui/gui/spokes/network.glade.h:18
msgid "Hardware Address"
msgstr "ハードウェアアドレス"

#: pyanaconda/ui/gui/spokes/network.glade.h:19
msgid "Parent"
msgstr "親"

#: pyanaconda/ui/gui/spokes/network.glade.h:20
msgid "VLAN ID"
msgstr "VLAN ID"

#: pyanaconda/ui/gui/spokes/network.glade.h:21
msgctxt "GUI|Network|Wired"
msgid "C_onfigure..."
msgstr "設定(_O)"

#: pyanaconda/ui/gui/spokes/network.glade.h:22
msgid "Security"
msgstr "セキュリティー"

#: pyanaconda/ui/gui/spokes/network.glade.h:23
msgctxt "GUI|Network|Wireless"
msgid "_Network Name"
msgstr "ネットワーク名(_N)"

#: pyanaconda/ui/gui/spokes/network.glade.h:24
msgid "Network Name"
msgstr "ネットワーク名"

#: pyanaconda/ui/gui/spokes/network.glade.h:25
msgid "Security Key"
msgstr "セキュリティーキー"

#: pyanaconda/ui/gui/spokes/network.glade.h:26
msgctxt "GUI|Network|Wireless"
msgid "_Use as Hotspot..."
msgstr "ホットスポットとして使用する(_U)..."

#: pyanaconda/ui/gui/spokes/network.glade.h:27
msgctxt "GUI|Network|Wireless"
msgid "_Stop Hotspot..."
msgstr "ホットスポットを停止(_S)..."

#: pyanaconda/ui/gui/spokes/network.glade.h:28
msgctxt "GUI|Network|Wireless"
msgid "_Configure..."
msgstr "設定(_C)..."

#: pyanaconda/ui/gui/spokes/network.glade.h:29
msgid "IMEI"
msgstr "IMEI"

#: pyanaconda/ui/gui/spokes/network.glade.h:30
msgid "Provider"
msgstr "プロバイダー"

#: pyanaconda/ui/gui/spokes/network.glade.h:32
msgctxt "GUI|Network|Mobile Broadband"
msgid "_Configure..."
msgstr "設定(_C)..."

#: pyanaconda/ui/gui/spokes/network.glade.h:33
msgid "VPN Type"
msgstr "VPN タイプ"

#: pyanaconda/ui/gui/spokes/network.glade.h:34
msgid "Gateway"
msgstr "ゲートウェイ"

#: pyanaconda/ui/gui/spokes/network.glade.h:35
msgid "Group Name"
msgstr "グループ名"

#: pyanaconda/ui/gui/spokes/network.glade.h:36
msgid "Group Password"
msgstr "グループパスワード"

#: pyanaconda/ui/gui/spokes/network.glade.h:37
#: pyanaconda/ui/gui/spokes/user.glade.h:5
msgid "User name"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/network.glade.h:38
msgctxt "GUI|Network|VPN"
msgid "_Configure..."
msgstr "設定(_C)..."

#: pyanaconda/ui/gui/spokes/network.glade.h:39
msgctxt "GUI|Network|Proxy"
msgid "_Method"
msgstr "メソッド(_M)"

#: pyanaconda/ui/gui/spokes/network.glade.h:40
msgctxt "GUI|Network|Proxy"
msgid "_Configuration URL"
msgstr "設定の URL(_C)"

#: pyanaconda/ui/gui/spokes/network.glade.h:41
msgctxt "GUI|Network|Proxy"
msgid "HTTP _Proxy"
msgstr "HTTP プロキシー(_P)"

#: pyanaconda/ui/gui/spokes/network.glade.h:42
msgctxt "GUI|Network|Proxy"
msgid "H_TTPS Proxy"
msgstr "HTTPS プロキシー(_T)"

#: pyanaconda/ui/gui/spokes/network.glade.h:43
msgctxt "GUI|Network|Proxy"
msgid "_FTP Proxy"
msgstr "FTP プロキシー(_F)"

#: pyanaconda/ui/gui/spokes/network.glade.h:44
msgctxt "GUI|Network|Proxy"
msgid "_Socks Host"
msgstr "Socks ホスト(_S)"

#: pyanaconda/ui/gui/spokes/network.glade.h:46
msgid "Network Config Box"
msgstr "ネットワーク設定ボックス"

#: pyanaconda/ui/gui/spokes/network.glade.h:47
msgctxt "GUI|Network"
msgid "Unloc_k"
msgstr "ロック解除(_K)"

#: pyanaconda/ui/gui/spokes/network.glade.h:48
msgctxt "GUI|Network"
msgid "Airplane Mode"
msgstr "機内モード"

#: pyanaconda/ui/gui/spokes/network.glade.h:49
msgid "More Network Config Box"
msgstr "詳細なネットワーク設定ボックス"

#: pyanaconda/ui/gui/spokes/network.glade.h:50
msgctxt "GUI|Network"
msgid "_Host name:"
msgstr "ホスト名(_H):"

#: pyanaconda/ui/gui/spokes/network.glade.h:52
msgid "_Apply"
msgstr "適用(_A)"

#: pyanaconda/ui/gui/spokes/network.glade.h:53
msgid "Set as current system host name."
msgstr "現在のシステムホスト名として設定します。"

#: pyanaconda/ui/gui/spokes/network.glade.h:54
msgid "Current host name:"
msgstr "現在のホスト名:"

#: pyanaconda/ui/gui/spokes/network.glade.h:55
msgid "NETWORK CONFIGURATION"
msgstr "ネットワークの設定"

#: pyanaconda/ui/gui/spokes/network.glade.h:56
msgid ""
"We'll need network access to fetch information about your location and to "
"make software\n"
"updates available for you."
msgstr ""
"ユーザーの位置情報の取得およびソフトウェア更新を取得可能に\n"
"するため、ネットワークアクセスが必要です。"

#: pyanaconda/ui/gui/spokes/network.glade.h:58
msgid "Authentication"
msgstr "認証"

#: pyanaconda/ui/gui/spokes/network.glade.h:59
msgctxt "GUI|Network|Authentication Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/network.glade.h:60
msgctxt "GUI|Network|Authentication Dialog"
msgid "C_onnect"
msgstr "接続(_O)"

#: pyanaconda/ui/gui/spokes/network.glade.h:62
msgid ""
"Passwords or encryption keys are required to access\n"
"the wireless network"
msgstr ""
"この無線 LAN にアクセスするには、パスワード\n"
"もしくは暗号キーが必要です。"

#: pyanaconda/ui/gui/spokes/software.glade.h:1
msgid "SOFTWARE SELECTION"
msgstr "ソフトウェアの選択"

#: pyanaconda/ui/gui/spokes/software.glade.h:2
msgid "Base Environment"
msgstr "ベース環境"

#: pyanaconda/ui/gui/spokes/software.glade.h:3
msgid "Add-Ons for Selected Environment"
msgstr "選択した環境のアドオン"

#: pyanaconda/ui/gui/spokes/storage.glade.h:1
msgctxt "GUI|Storage|Need Space Dialog"
msgid "Cancel & _add more disks"
msgstr "取り消してディスクを追加する(_A)"

#: pyanaconda/ui/gui/spokes/storage.glade.h:2
msgctxt "GUI|Storage|Need Space Dialog"
msgid "_Reclaim space"
msgstr "領域の確保 (_R)"

#: pyanaconda/ui/gui/spokes/storage.glade.h:3
msgid "INSTALLATION OPTIONS"
msgstr "インストールオプション"

#: pyanaconda/ui/gui/spokes/storage.glade.h:4
msgid ""
"Here we'll describe how much space is needed for the current software "
"selection."
msgstr "ここで現在のソフトウェア選択に必要となる領域を説明します。"

#: pyanaconda/ui/gui/spokes/storage.glade.h:5
msgid "disk free"
msgstr "disk free"

#: pyanaconda/ui/gui/spokes/storage.glade.h:6
msgid "Free space available for use."
msgstr "使用できる空き領域。"

#: pyanaconda/ui/gui/spokes/storage.glade.h:7
msgid "fs free"
msgstr "fs free"

#: pyanaconda/ui/gui/spokes/storage.glade.h:8
msgid "Free space unavailable but reclaimable from existing partitions."
msgstr "現在利用できないものの、既存のパーティションから再利用可能な空き領域。"

#: pyanaconda/ui/gui/spokes/storage.glade.h:9
msgid "Here we'll describe what your options are."
msgstr "ここでユーザーのオプションを説明します。"

#: pyanaconda/ui/gui/spokes/storage.glade.h:10
msgid "Need Space"
msgstr "領域が必要です"

#: pyanaconda/ui/gui/spokes/storage.glade.h:11
msgctxt "GUI|Storage|No Space Dialog"
msgid "_Quit installer"
msgstr "インストーラーの終了(_Q)"

#: pyanaconda/ui/gui/spokes/storage.glade.h:12
msgctxt "GUI|Storage|No Space Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/storage.glade.h:13
msgid "No Space"
msgstr "空きがありません"

#: pyanaconda/ui/gui/spokes/storage.glade.h:15
msgid "Device Selection"
msgstr "デバイスの選択"

#: pyanaconda/ui/gui/spokes/storage.glade.h:16
msgid ""
"Select the device(s) you'd like to install to.  They will be left untouched "
"until you click on the main menu's \"Begin Installation\" button."
msgstr ""
"インストールするデバイスを選択します。メインメニューの「インストールの開始」"
"ボタンをクリックしない限り、インストールは開始しません。"

#: pyanaconda/ui/gui/spokes/storage.glade.h:17
msgid "Local Standard Disks"
msgstr "ローカルの標準ディスク"

#: pyanaconda/ui/gui/spokes/storage.glade.h:18
msgid "Disks left unselected here will not be touched."
msgstr "ここで未選択のままにしたディスクについては、何も行なわれません。"

#: pyanaconda/ui/gui/spokes/storage.glade.h:19
msgid "Specialized & Network Disks"
msgstr "特殊なディスクおよびネットワークディスク"

#: pyanaconda/ui/gui/spokes/storage.glade.h:20
msgctxt "GUI|Storage"
msgid "_Add a disk..."
msgstr "ディスクの追加(_A)..."

#: pyanaconda/ui/gui/spokes/storage.glade.h:21
msgid "Add Specialized Disk"
msgstr "特殊なディスクの追加"

#: pyanaconda/ui/gui/spokes/storage.glade.h:22
msgid "Other Storage Options"
msgstr "その他のストレージオプション"

#: pyanaconda/ui/gui/spokes/storage.glade.h:23
msgid "Partitioning"
msgstr "パーティション構成"

#: pyanaconda/ui/gui/spokes/storage.glade.h:24
msgid "Encryption"
msgstr "暗号化"

#: pyanaconda/ui/gui/spokes/storage.glade.h:25
msgid "A_utomatically configure partitioning."
msgstr "パーティションを自動構成する(_U)"

#: pyanaconda/ui/gui/spokes/storage.glade.h:26
msgid "_I will configure partitioning."
msgstr "パーティションを自分で構成する(_I)"

#: pyanaconda/ui/gui/spokes/storage.glade.h:27
msgid "_Encrypt my data."
msgstr "データを暗号化する(_E)"

#: pyanaconda/ui/gui/spokes/storage.glade.h:28
msgid "You'll set a passphrase next."
msgstr "パスフレーズの設定は、次のセクションで行います。"

#: pyanaconda/ui/gui/spokes/storage.glade.h:29
msgid "I would like to _make additional space available."
msgstr "追加の空き領域を利用できるようにする(_M)"

#: pyanaconda/ui/gui/spokes/storage.glade.h:30
msgid "Storage Options"
msgstr "ストレージのオプション"

#: pyanaconda/ui/gui/spokes/storage.glade.h:31
msgid "summary"
msgstr "要約"

#: pyanaconda/ui/gui/spokes/storage.glade.h:32
msgctxt "GUI|Storage"
msgid "_Full disk summary and boot loader..."
msgstr "完全なディスク要約とブートローダー(_F)..."

#: pyanaconda/ui/gui/spokes/storage.glade.h:33
msgctxt "GUI|Storage"
msgid "_Refresh..."
msgstr "更新(_R)..."

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:1
msgid "KEYBOARD LAYOUT"
msgstr "キーボードレイアウト"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:2
msgid ""
"Which keyboard layouts would you like to use on this system?  You may move "
"any layout to the top of the list to select it as the default."
msgstr ""
"このシステムで使用するキーボードレイアウトを選択してください。デフォルトにす"
"るレイアウトを一覧の先頭に移動させます。"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:3
msgid ""
"Changes here will only apply to the installed system. Use the desktop's tool "
"to configure the keyboard for the installation process."
msgstr ""
"ここでの変更は、インストールされた後のシステムに対して適用されます。インス"
"トールプロセスのためにキーボードレイアウトを設定するには、デスクトップのツー"
"ルを使用してください。"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:4
msgid "name"
msgstr "名前"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:5
msgid "Selected Layouts"
msgstr "選択されたレイアウト"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:6
msgctxt "GUI|Keyboard Layout"
msgid "_Add layout"
msgstr "レイアウトの追加(_A)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:7
msgctxt "GUI|Keyboard Layout"
msgid "_Remove layout"
msgstr "レイアウトの削除(_R)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:8
msgctxt "GUI|Keyboard Layout"
msgid "Move selected layout _up"
msgstr "選択したレイアウトを上に移動(_U)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:9
msgctxt "GUI|Keyboard Layout"
msgid "Move selected layout _down"
msgstr "選択したレイアウトを下に移動(_D)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:10
msgctxt "GUI|Keyboard Layout"
msgid "_Preview layout"
msgstr "レイアウトのプレビュー(_P)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:11
msgctxt "GUI|Keyboard Layout"
msgid "_Test the layout configuration below:"
msgstr "レイアウト設定をテストする(_T):"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:12
msgid "Alt + Shift to switch layouts."
msgstr "Alt + Shift を使ってレイアウトを切り替えます。"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:13
msgctxt "GUI|Keyboard Layout"
msgid "_Options"
msgstr "オプション(_O)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:14
msgctxt "GUI|Keyboard Layout|Add Layout"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:15
msgctxt "GUI|Keyboard Layout|Add Layout"
msgid "_Add"
msgstr "追加(_A)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:16
msgid "ADD A KEYBOARD LAYOUT"
msgstr "キーボードレイアウトを追加"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:17
msgid "You may add a keyboard layout by selecting it below:"
msgstr "以下の一覧から、キーボードレイアウトを選択して追加できます。"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:19
msgid "Available Layouts"
msgstr "利用可能なレイアウト"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:20
msgid "Add Layout"
msgstr "レイアウトの追加"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:21
msgctxt "GUI|Keyboard Layout|Switching Options"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:22
msgctxt "GUI|Keyboard Layout|Switching Options"
msgid "_OK"
msgstr "OK(_O)"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:23
msgid "LAYOUT SWITCHING OPTIONS"
msgstr "レイアウト切り替えのオプション"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:24
msgid ""
"Which combination(s) would you prefer for switching between keyboard layouts?"
msgstr ""
"キーボードレイアウトの切り替えに使用するキーコンビネーションを選択してくださ"
"い。"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:25
msgid "use"
msgstr "使用"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:26
msgid "description"
msgstr "詳細"

#: pyanaconda/ui/gui/spokes/keyboard.glade.h:27
msgid "Layout Options"
msgstr "レイアウトのオプション"

#: pyanaconda/ui/gui/spokes/langsupport.glade.h:1
msgid "LANGUAGE SUPPORT"
msgstr "言語サポート"

#: pyanaconda/ui/gui/spokes/langsupport.glade.h:2
msgid "Select additional language support to be installed:"
msgstr "インストールしたい追加の言語サポートを選択:"

#: pyanaconda/ui/gui/spokes/langsupport.glade.h:3
#: pyanaconda/ui/gui/spokes/welcome.glade.h:11
msgid "nativeName"
msgstr "nativeName"

#: pyanaconda/ui/gui/spokes/langsupport.glade.h:4
#: pyanaconda/ui/gui/spokes/welcome.glade.h:12
msgid "englishName"
msgstr "englishName"

#: pyanaconda/ui/gui/spokes/langsupport.glade.h:5
#: pyanaconda/ui/gui/spokes/welcome.glade.h:13
msgid "selected"
msgstr "selected"

#: pyanaconda/ui/gui/spokes/langsupport.glade.h:6
#: pyanaconda/ui/gui/spokes/welcome.glade.h:15
msgid "Type here to search."
msgstr "ここに入力して検索します。"

#: pyanaconda/ui/gui/spokes/langsupport.glade.h:7
msgid "checked"
msgstr "checked"

#: pyanaconda/ui/gui/spokes/password.glade.h:1
msgid "ROOT PASSWORD"
msgstr "root パスワード"

#: pyanaconda/ui/gui/spokes/password.glade.h:2
msgctxt "GUI|Password"
msgid "_Root Password:"
msgstr "root パスワード(_R):"

#: pyanaconda/ui/gui/spokes/password.glade.h:3
msgctxt "GUI|Password"
msgid "_Confirm:"
msgstr "確認(_C):"

#: pyanaconda/ui/gui/spokes/password.glade.h:5
#: pyanaconda/ui/gui/spokes/user.glade.h:9
msgid "Confirm Password"
msgstr "パスワードの確認"

#: pyanaconda/ui/gui/spokes/password.glade.h:6
#: pyanaconda/ui/gui/spokes/user.glade.h:12
msgid "empty password"
msgstr "パスワードが入力されていません"

#: pyanaconda/ui/gui/spokes/password.glade.h:7
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""
"システムの管理には root アカウントを使用します。root ユーザーのパスワードを入"
"力してください。"

#: pyanaconda/ui/gui/spokes/source.glade.h:1
msgctxt "GUI|Software Source|ISO Chooser Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/source.glade.h:2
msgctxt "GUI|Software Source|ISO Chooser Dialog"
msgid "_Open"
msgstr "開く(_O)"

#: pyanaconda/ui/gui/spokes/source.glade.h:3
msgctxt "GUI|Software Source|Media Check Dialog"
msgid "_Done"
msgstr "完了 (_D)"

#: pyanaconda/ui/gui/spokes/source.glade.h:4
msgid "MEDIA VERIFICATION"
msgstr "メディアの検証"

#: pyanaconda/ui/gui/spokes/source.glade.h:5
msgid "Verifying media, please wait..."
msgstr "メディアを検証しています。お待ち下さい..."

#: pyanaconda/ui/gui/spokes/source.glade.h:6
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/source.glade.h:7
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_OK"
msgstr "OK(_O)"

#: pyanaconda/ui/gui/spokes/source.glade.h:8
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_Enable HTTP Proxy"
msgstr "HTTP プロキシーを有効にする(_E)"

#: pyanaconda/ui/gui/spokes/source.glade.h:9
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_Proxy Host"
msgstr "プロキシーのホスト(_P)"

#: pyanaconda/ui/gui/spokes/source.glade.h:10
msgid "<span size=\"small\"><b>Example:</b> squid.mysite.org:3128</span>"
msgstr "<span size=\"small\"><b>例:</b> squid.mysite.org:3128</span>"

#: pyanaconda/ui/gui/spokes/source.glade.h:11
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_Use Authentication"
msgstr "認証を使用する(_U)"

#: pyanaconda/ui/gui/spokes/source.glade.h:12
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "User _name"
msgstr "ユーザー名(_N)"

#: pyanaconda/ui/gui/spokes/source.glade.h:13
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "Pass_word"
msgstr "パスワード(_W)"

#: pyanaconda/ui/gui/spokes/source.glade.h:14
msgid "INSTALLATION SOURCE"
msgstr "インストールソース"

#: pyanaconda/ui/gui/spokes/source.glade.h:15
msgid "Which installation source would you like to use?"
msgstr "使用するインストールソースを選択してください。"

#: pyanaconda/ui/gui/spokes/source.glade.h:16
msgctxt "GUI|Software Source"
msgid "_Auto-detected installation media:"
msgstr "自動検出したインストールメディア(_A):"

#: pyanaconda/ui/gui/spokes/source.glade.h:17
msgid "Device:"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/source.glade.h:18
msgid "Label:"
msgstr "ラベル:"

#: pyanaconda/ui/gui/spokes/source.glade.h:19
msgctxt "GUI|Software Source"
msgid "_Verify"
msgstr "検証する (_V)"

#: pyanaconda/ui/gui/spokes/source.glade.h:20
msgctxt "GUI|Software Source"
msgid "Installation media via SE/_HMC"
msgstr "SE/_HMC を用いたインストールメディア"

#: pyanaconda/ui/gui/spokes/source.glade.h:21
msgctxt "GUI|Software Source"
msgid "_ISO file:"
msgstr "ISO ファイル (_I):"

#: pyanaconda/ui/gui/spokes/source.glade.h:22
msgctxt "GUI|Software Source"
msgid "D_evice:"
msgstr "デバイス(_E):"

#: pyanaconda/ui/gui/spokes/source.glade.h:23
msgctxt "GUI|Software Source"
msgid "_Choose an ISO"
msgstr "ISO を１つ選択(_C)"

#: pyanaconda/ui/gui/spokes/source.glade.h:24
msgctxt "GUI|Software Source"
msgid "_On the network:"
msgstr "ネットワーク上(_O):"

#: pyanaconda/ui/gui/spokes/source.glade.h:26
msgctxt "GUI|Software Source"
msgid "_Proxy setup..."
msgstr "プロキシーの設定(_P)..."

#: pyanaconda/ui/gui/spokes/source.glade.h:27
msgctxt "GUI|Software Source"
msgid "This URL refers to a _mirror list."
msgstr "この URL はミラーリストを参照します(_M)。"

#: pyanaconda/ui/gui/spokes/source.glade.h:28
msgctxt "GUI|Software Source"
msgid "N_FS mount options:"
msgstr "NFS マウントオプション(_F):"

#: pyanaconda/ui/gui/spokes/source.glade.h:29
msgid "This field is optional."
msgstr "このフィールドはオプションです。"

#: pyanaconda/ui/gui/spokes/source.glade.h:30
msgid "Updates"
msgstr "更新"

#: pyanaconda/ui/gui/spokes/source.glade.h:31
msgctxt "GUI|Software Source"
msgid ""
"Don't install the latest available software _updates. Install the default "
"versions provided by the installation source above."
msgstr ""
"最新バージョンのソフトウェアはインストールしません。上記のインストールソース"
"で提供されるデフォルトのバージョンをインストールします(_U)。"

#: pyanaconda/ui/gui/spokes/source.glade.h:32
msgid "Additional repositories"
msgstr "追加のリポジトリー"

#: pyanaconda/ui/gui/spokes/source.glade.h:33
msgid "Enabled"
msgstr "有効"

#: pyanaconda/ui/gui/spokes/source.glade.h:35
msgid "Add a new repository."
msgstr "新規のリポジトリーを追加します。"

#: pyanaconda/ui/gui/spokes/source.glade.h:36
msgctxt "GUI|Software Source"
msgid "A_dd"
msgstr "追加(_D)"

#: pyanaconda/ui/gui/spokes/source.glade.h:37
msgid "Remove the selected repository."
msgstr "選択したリポジトリーを削除します。"

#: pyanaconda/ui/gui/spokes/source.glade.h:38
msgctxt "GUI|Software Source"
msgid "_Remove"
msgstr "削除(_R)"

#: pyanaconda/ui/gui/spokes/source.glade.h:39
msgid "Revert to the previous list of repositories."
msgstr "リポジトリ－一覧を以前のものに戻します。"

#: pyanaconda/ui/gui/spokes/source.glade.h:40
msgctxt "GUI|Software Source"
msgid "Rese_t"
msgstr "リセット(_T)"

#: pyanaconda/ui/gui/spokes/source.glade.h:41
msgid "URL for the repository, without protocol."
msgstr "リポジトリーの URL、プロトコルなし。"

#: pyanaconda/ui/gui/spokes/source.glade.h:42
msgid "URL of proxy in the form of protocol://host:[port]"
msgstr "プロキシーの URL (書式 protocol://host:[port])"

#: pyanaconda/ui/gui/spokes/source.glade.h:43
msgid "Optional proxy user name."
msgstr "オプションのプロキシーユーザー名です。"

#: pyanaconda/ui/gui/spokes/source.glade.h:44
msgid "Optional proxy password."
msgstr "オプションのプロキシーパスワードです。"

#: pyanaconda/ui/gui/spokes/source.glade.h:45
msgctxt "GUI|Software Source"
msgid "This URL refers to a mirror _list."
msgstr "この URL はミラーリストを参照します(_L)"

#: pyanaconda/ui/gui/spokes/source.glade.h:46
msgctxt "GUI|Software Source"
msgid "_Name:"
msgstr "名前(_N):"

#: pyanaconda/ui/gui/spokes/source.glade.h:47
msgid "Protocol for the repository URL."
msgstr "リポジトリー URL のプロトコルです。"

#: pyanaconda/ui/gui/spokes/source.glade.h:48
msgctxt "GUI|Software Source"
msgid "Pro_xy URL:"
msgstr "プロキシーの URL(_X):"

#: pyanaconda/ui/gui/spokes/source.glade.h:49
msgctxt "GUI|Software Source"
msgid "U_ser name:"
msgstr "ユーザー名(_S):"

#: pyanaconda/ui/gui/spokes/source.glade.h:50
msgctxt "GUI|Software Source"
msgid "Pass_word:"
msgstr "パスワード(_W):"

#: pyanaconda/ui/gui/spokes/source.glade.h:51
msgid "Name of the repository."
msgstr "リポジトリー名。"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:1
msgctxt "GUI|Welcome|Beta Warn Dialog"
msgid "I want to _exit."
msgstr "終了(_E)。"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:2
msgctxt "GUI|Welcome|Beta Warn Dialog"
msgid "I want to _proceed."
msgstr "続行(_P)。"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:3
msgid "This is unstable, pre-release software."
msgstr "リリース前の不安定なソフトウェアです。"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:4
msgid ""
"Notice:  This is pre-release software that is intended for development and "
"testing purposes only.  Do not use this software for any critical work or "
"for production environments.\n"
"\n"
"By clicking \"I want to proceed\", you understand and accept the risks "
"associated with pre-release software, that you intend to use this for "
"testing and development purposes only, and are willing to report any bugs or "
"issues in order to enhance this work.\n"
"\n"
"If you do not understand or accept the risks, then please exit this program "
"by clicking \"I want to exit\" which will reboot your system."
msgstr ""
"注意: 開発およびテストを目的としたプレリリースソフトウェアになります。実稼動"
"環境または大事な作業を行うための環境として本ソフトウェアは使用しないでくださ"
"い。\n"
"\n"
"「続行」をクリックすると、プレリリースソフトウェアに関連するリスクを理解して"
"受け入れ、テストおよび開発目的に限定して使用すること、テストおよび開発に貢献"
"するためバグや問題を進んで報告することに同意したものとみなします。\n"
"\n"
"プレリリースソフトウェアに伴うリスクがよくわからない場合、またはリスクを受け"
"入れたくない場合は「終了」をクリックしてプログラムを終了してください。システ"
"ムが再起動します。"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:9
msgid "Beta Warn"
msgstr "Beta 警告"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:10
msgid "What language would you like to use during the installation process?"
msgstr "インストール時に使用する言語を選択してください。"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:14
msgid "Languages"
msgstr "言語"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:16
msgid "Locales"
msgstr "ロケール"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:17
msgid "WELCOME"
msgstr "ようこそ"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:18
msgctxt "GUI|Welcome|Unsupported Hardware Dialog"
msgid "_Quit"
msgstr "終了(_Q)"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:19
msgctxt "GUI|Welcome|Unsupported Hardware Dialog"
msgid "_Continue"
msgstr "続行(_C)"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:20
msgid "Unsupported Hardware Detected"
msgstr "サポートされていないハードウェアが検出されました"

#: pyanaconda/ui/gui/spokes/welcome.glade.h:22
msgid "Unsupported Hardware"
msgstr "未対応のハードウェア"

#: pyanaconda/ui/gui/spokes/user.glade.h:1
msgid "CREATE USER"
msgstr "ユーザーの作成"

#: pyanaconda/ui/gui/spokes/user.glade.h:2
msgctxt "GUI|User"
msgid "_Full name"
msgstr "フルネーム(_F)"

#: pyanaconda/ui/gui/spokes/user.glade.h:3
msgctxt "GUI|User"
msgid "_User name"
msgstr "ユーザー名(_U):"

#: pyanaconda/ui/gui/spokes/user.glade.h:4
msgid "Full Name"
msgstr "フルネーム"

#: pyanaconda/ui/gui/spokes/user.glade.h:6
msgctxt "GUI|User"
msgid "_Password"
msgstr "パスワード(_P)"

#: pyanaconda/ui/gui/spokes/user.glade.h:7
msgctxt "GUI|User"
msgid "_Confirm password"
msgstr "パスワードの確認(_C)"

#: pyanaconda/ui/gui/spokes/user.glade.h:10
msgid ""
"<b>Tip:</b> Keep your user name shorter than 32 characters and do not use "
"spaces."
msgstr ""
"<b>ヒント:</b> ユーザー名は 32 文字未満にし、空白は使用しないでください。"

#: pyanaconda/ui/gui/spokes/user.glade.h:11
msgctxt "GUI|User"
msgid "Require a password to use this account"
msgstr "このアカウントを使用する場合にパスワードを必要とする"

#: pyanaconda/ui/gui/spokes/user.glade.h:13
msgctxt "GUI|User"
msgid "Make this user administrator"
msgstr "このユーザーを管理者にする"

#: pyanaconda/ui/gui/spokes/user.glade.h:14
msgctxt "GUI|User"
msgid "_Advanced..."
msgstr "高度(_A)..."

#: pyanaconda/ui/gui/spokes/custom.glade.h:6
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:23
msgid "RAID0 <span foreground=\"grey\">(Performance)</span>"
msgstr "RAID0 <span foreground=\"grey\">(パフォーマンス)</span>"

#: pyanaconda/ui/gui/spokes/custom.glade.h:7
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:24
msgid "RAID1 <span foreground=\"grey\">(Redundancy)</span>"
msgstr "RAID1 <span foreground=\"grey\">(冗長化)</span>"

#: pyanaconda/ui/gui/spokes/custom.glade.h:8
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:25
msgid "RAID4 <span foreground=\"grey\">(Error Checking)</span>"
msgstr "RAID4 <span foreground=\"grey\">(エラーチェック)</span>"

#: pyanaconda/ui/gui/spokes/custom.glade.h:9
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:26
msgid "RAID5 <span foreground=\"grey\">(Distributed Error Checking)</span>"
msgstr "RAID5 <span foreground=\"grey\">(分散エラーチェック)</span>"

#: pyanaconda/ui/gui/spokes/custom.glade.h:10
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:27
msgid "RAID6 <span foreground=\"grey\">(Redundant Error Checking)</span>"
msgstr "RAID6 <span foreground=\"grey\">(冗長エラーチェック)</span>"

#: pyanaconda/ui/gui/spokes/custom.glade.h:11
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:28
msgid "RAID10 <span foreground=\"grey\">(Performance, Redundancy)</span>"
msgstr "RAID10 <span foreground=\"grey\">(パフォーマンス、冗長化)</span>"

#: pyanaconda/ui/gui/spokes/custom.glade.h:13
msgid "Add a new mount point."
msgstr "新しいマウントポイントの追加(_A)"

#: pyanaconda/ui/gui/spokes/custom.glade.h:14
msgctxt "GUI|Custom Partitioning"
msgid "Add"
msgstr "追加"

#: pyanaconda/ui/gui/spokes/custom.glade.h:15
msgid "Remove the selected mount point(s)."
msgstr "選択したマウントポイントを削除します。"

#: pyanaconda/ui/gui/spokes/custom.glade.h:16
msgctxt "GUI|Custom Partitioning"
msgid "Remove"
msgstr "削除"

#: pyanaconda/ui/gui/spokes/custom.glade.h:17
msgid "Reload storage configuration from disk."
msgstr "ディスクからストレージ設定を再読み込みします。"

#: pyanaconda/ui/gui/spokes/custom.glade.h:18
msgctxt "GUI|Custom Partitioning"
msgid "Refresh"
msgstr "更新"

#: pyanaconda/ui/gui/spokes/custom.glade.h:19
msgid "Selected Device"
msgstr "選択したデバイス"

#: pyanaconda/ui/gui/spokes/custom.glade.h:20
msgid "Device description"
msgstr "デバイスの説明"

#: pyanaconda/ui/gui/spokes/custom.glade.h:21
msgid "Mount _Point:"
msgstr "マウントポイント(_P):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:22
msgid "_Desired Capacity:"
msgstr "割り当てる容量(_D):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:23
msgid "_Label:"
msgstr "ラベル(_L):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:24
msgid "Device(s):"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/custom.glade.h:25
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "_Modify..."
msgstr "修正(_M)..."

#: pyanaconda/ui/gui/spokes/custom.glade.h:26
msgid "_Name:"
msgstr "名前(_N):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:27
msgctxt "GUI|Custom Partitioning|Configure"
msgid "Device _Type:"
msgstr "デバイスタイプ(_T):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:28
msgctxt "GUI|Custom Partitioning|Configure"
msgid "_Encrypt"
msgstr "暗号化(_E)"

#: pyanaconda/ui/gui/spokes/custom.glade.h:29
msgctxt "GUI|Custom Partitioning|Configure"
msgid "File S_ystem:"
msgstr "ファイルシステム(_Y):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:30
msgctxt "GUI|Custom Partitioning|Configure"
msgid "Ref_ormat"
msgstr "再フォーマット(_O)"

#: pyanaconda/ui/gui/spokes/custom.glade.h:31
msgctxt "GUI|Custom Partitioning|Configure"
msgid "_Volume Group:"
msgstr "ボリュームグループ(_V):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:32
msgctxt "GUI|Custom Partitioning|Configure"
msgid "_Modify..."
msgstr "修正(_M)..."

#: pyanaconda/ui/gui/spokes/custom.glade.h:33
msgctxt "GUI|Custom Partitioning|Configure"
msgid "RA_ID Level:"
msgstr "RAID レベル(_I):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:34
msgid "_Update Settings"
msgstr "設定の更新(_U)"

#: pyanaconda/ui/gui/spokes/custom.glade.h:35
msgid ""
"Note:  The settings you make on this screen will not be applied until you "
"click on the main menu's 'Begin Installation' button."
msgstr ""
"注意: ここで行った設定は、メインメニューの「インストールの開始」を選択するま"
"で反映されません。"

#: pyanaconda/ui/gui/spokes/custom.glade.h:36
msgid ""
"This device is encrypted and cannot be read without a valid passphrase. You "
"may unlock it below."
msgstr ""
"このデバイスは暗号化されているため、有効なパスフレーズがないと読み込めませ"
"ん。以下でアンロックできます。"

#: pyanaconda/ui/gui/spokes/custom.glade.h:37
msgctxt "GUI|Custom Partitioning|Encrypted"
msgid "_Passphrase:"
msgstr "パスフレーズ(_P):"

#: pyanaconda/ui/gui/spokes/custom.glade.h:38
msgctxt "GUI|Custom Partitioning|Encrypted"
msgid "_Unlock"
msgstr "ロック解除(_U)"

#: pyanaconda/ui/gui/spokes/custom.glade.h:39
msgid ""
"This device cannot be edited directly. You can remove it or select a "
"different device."
msgstr ""
"このデバイスは直接編集できません。デバイスを削除するか、別のデバイスを選択し"
"ます。"

#: pyanaconda/ui/gui/spokes/custom.glade.h:40
msgid "AVAILABLE SPACE"
msgstr "使用できる領域"

#: pyanaconda/ui/gui/spokes/custom.glade.h:41
msgid "TOTAL SPACE"
msgstr "すべての領域"

#: pyanaconda/ui/gui/spokes/custom.glade.h:42
msgctxt "GUI|Custom Partitioning"
msgid "_Reset All"
msgstr "すべてリセット(_R)"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:1
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:2
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_OK"
msgstr "OK(_O)"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:3
msgid "ADD DASD STORAGE TARGET"
msgstr "DASD ストレージターゲットの追加"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:4
msgid "To use DASD disks, you must provide the device number."
msgstr "DASD ディスクを使用する場合は、デバイス番号を入力する必要があります。"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:5
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_Device number:"
msgstr "デバイス番号(_D):"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:6
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_Start Discovery"
msgstr "探索を開始(_S)"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:7
msgid "Discovering DASD devices.  This may take a moment..."
msgstr "zFCP デバイスを検索中です。少々お待ちください..."

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:8
#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:7
msgid "Device discovery failed."
msgstr "デバイスの検索に失敗しました。"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:9
msgid ""
"The following error occurred discovering DASD devices.  Please double check "
"your configuration information and try again."
msgstr ""
"DASD デバイスの探索中に次のエラーが発生しました。設定情報をもう一度確認してか"
"らやり直してください。"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:10
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_Retry Discovery"
msgstr "探索を再試行(_R)"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:11
msgid "Device discovery succeeded."
msgstr "デバイスの検索に成功しました。"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade.h:12
msgid "The added DASD can be found under \"Local Standard Disks\"."
msgstr ""
"追加された DASD は、\"ローカルの標準ディスク\" として見つけることができます。"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade.h:1
msgctxt "GUI|Advanced Storage|FCoE"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade.h:2
msgid ""
"Please select the network interface which is connected to your FCoE switch."
msgstr ""
"FCoE スイッチに接続するネットワークインターフェースを選択してください。"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade.h:3
msgctxt "GUI|Advanced Storage|FCoE"
msgid "_NIC:"
msgstr "NIC(_N):"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade.h:4
msgctxt "GUI|Advanced Storage|FCoE"
msgid "Use _DCB"
msgstr "DCB の使用(_D)"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade.h:5
msgctxt "GUI|Advanced Storage|FCoE"
msgid "Use auto _VLAN"
msgstr "自動 VLAN を使用(_V)"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade.h:6
msgctxt "GUI|Advanced Storage|FCoE"
msgid "_Add FCoE Disk(s)"
msgstr "FCoE ディスクの追加(_A)"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade.h:7
msgid "Error adding FCoE SAN."
msgstr "FCoE SAN 追加時にエラー。"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade.h:8
msgid ""
"The following error occurred while attempting to add an FCoE SAN.  Please "
"check your configuration and try again"
msgstr "FCoE SAN への追加中に、次のエラーが発生しました。設定を再度確認し、再試行してください"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:1
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:2
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_OK"
msgstr "OK(_O)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:3
msgid "ADD iSCSI STORAGE TARGET"
msgstr "iSCSI ターゲットの追加"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:4
msgid ""
"To use iSCSI disks, you must provide the address of your iSCSI target and "
"the iSCSI initiator name you've configured for your host."
msgstr ""
"iSCSI ディスクを使用するには、このシステムに使用する iSCSI イニシエーター名お"
"よび iSCSI ターゲットのアドレスを入力してください。"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:5
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_Target IP Address:"
msgstr "ターゲットIP アドレス(_T):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:6
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "iSCSI _Initiator Name:"
msgstr "iSCSIイニシエーター名(_I):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:7
msgid "No credentials (discovery authentication disabled)"
msgstr "証明書なし (探索時の認証は無効となります)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:8
msgid "CHAP pair"
msgstr "CHAP 秘密鍵"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:9
msgid "CHAP pair and a reverse pair"
msgstr "CHAP 秘密鍵と逆順鍵"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:10
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_Discovery Authentication Type:"
msgstr "認証タイプの探索(_D):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:11
msgid ""
"<span size=\"small\"><b>Example:</b> iqn.2012-09.com.example:diskarrays-sn-"
"a8675309</span>"
msgstr ""
"<span size=\"small\"><b>記述例:</b> iqn.2012-09.com.example:diskarrays-sn-"
"a8675309</span>"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:12
msgctxt "GUI|Advanced Storage|iSCSI|Configure|CHAP"
msgid "CHAP _User name:"
msgstr "CHAP ユーザー名(_U):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:13
msgctxt "GUI|Advanced Storage|iSCSI|Configure|CHAP"
msgid "CHAP _Password:"
msgstr "CHAP パスワード(_P):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:14
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Reverse CHAP"
msgid "CHAP _User name:"
msgstr "CHAP ユーザー名(_U):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:15
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Reverse CHAP"
msgid "CHAP _Password:"
msgstr "CHAP パスワード(_P):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:16
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Reverse CHAP"
msgid "Reverse CHAP User _name:"
msgstr "逆順 CHAP ユーザー名(_N):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:17
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Reverse CHAP"
msgid "Reverse CHAP Pass_word:"
msgstr "逆順 CHAP パスワード(_W):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:18
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Start"
msgid "_Start Discovery"
msgstr "探索を開始(_S)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:19
msgid "Discovering iSCSI targets.  This may take a moment..."
msgstr "iSCSI ターゲットを探索中です。少々お待ちください..."

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:20
msgid "Discovery login rejected."
msgstr "ログインの探索が拒否されました。"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:21
msgid ""
"The following error occurred discovering iSCSI targets.  Please double check "
"your authorization information and try again."
msgstr ""
"iSCSI ターゲットの探索中に、次のエラーが発生しました。認証情報を再度確認し、"
"再試行してください。"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:22
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Retry"
msgid "_Retry Discovery"
msgstr "探索を再試行(_R)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:23
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_Bind targets to network interfaces. This may take a moment..."
msgstr ""
"ターゲットをネットワークインターフェースにバインドします。時間がかかる場合が"
"あります..."

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:24
msgid "Node Name"
msgstr "ノード名"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:25
msgid "Interface"
msgstr "インターフェース"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:26
msgid "Portal"
msgstr "ポータル"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:27
msgctxt "GUI|Advanced Storage|iSCSI|Login"
msgid "_Node Login Authentication Type:"
msgstr "ノードログインの認証タイプ(_N):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:28
msgid "Use the credentials from discovery"
msgstr "探索時の証明書を使用"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:29
msgctxt "GUI|Advanced Storage|iSCSI|Login|CHAP"
msgid "CHAP _User name:"
msgstr "CHAP ユーザー名(_U):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:30
msgctxt "GUI|Advanced Storage|iSCSI|Login|CHAP"
msgid "CHAP _Password:"
msgstr "CHAP パスワード(_P):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:31
msgctxt "GUI|Advanced Storage|iSCSI|Login|Reverse CHAP"
msgid "CHAP _User name:"
msgstr "CHAP ユーザー名(_U):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:32
msgctxt "GUI|Advanced Storage|iSCSI|Login|Reverse CHAP"
msgid "CHAP _Password:"
msgstr "CHAP パスワード(_P):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:33
msgctxt "GUI|Advanced Storage|iSCSI|Login|Reverse CHAP"
msgid "_Reverse CHAP User name:"
msgstr "逆順 CHAP ユーザー名(_R):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:34
msgctxt "GUI|Advanced Storage|iSCSI|Login|Reverse CHAP"
msgid "Reverse CHAP Pass_word:"
msgstr "逆順 CHAP パスワード(_W):"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:35
msgctxt "GUI|Advanced Storage|iSCSI|Login|Login"
msgid "_Log In"
msgstr "ログイン(_L)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:36
msgid "Node login failed."
msgstr "ノードのログインに失敗しました。"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:37
msgid ""
"The following error occurred logging into the selected iSCSI node.  Please "
"double check your authorization information and try again"
msgstr ""
"選択した iSCSI ノードへのログイン中に、次のエラーが発生しました。認証情報を再"
"度確認し、再試行してください。"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade.h:38
msgctxt "GUI|Advanced Storage|iSCSI|Login|Retry"
msgid "Retry _Log In"
msgstr "ログインを再試行(_L)"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:1
msgctxt "GUI|Advanced Storage|NVDIMM|Reconfigure"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:2
msgid ""
"The following NVDIMM devices selected from the list will be reconfigured to "
"sector mode:"
msgstr "一覧から選択された以下の NVDIMM デバイスが、セクタモードに再設定されます:"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:3
msgctxt "GUI|Advanced Storage|NVDIMM|Reconfigure"
msgid "_Sector size:"
msgstr "セクタサイズ(_S):"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:4
msgctxt "GUI|Advanced Storage|NVDIMM|Reconfigure"
msgid "Start _Reconfiguration"
msgstr "再構成の開始(_R)"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:5
msgid "Reconfiguring NVDIMM devices. This may take a moment..."
msgstr "NVDIMMデバイスを再構成しています。しばらくお待ちください..."

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:6
msgid "Device reconfiguration failed."
msgstr "デバイスの再設定に失敗しました。"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:7
msgid "The following error occurred reconfiguring NVDIMM devices:"
msgstr "NVDIMM デバイスの再設定中に次のエラーが発生しました:"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:8
msgid "Devices reconfiguration succeeded."
msgstr "デバイスの再設定が正常に行われました。"

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:9
msgid ""
"Rescanning disks after reconfiguration.\n"
"This may take a moment ..."
msgstr ""
"再設定後にディスクを再びスキャンしています。\n"
"少々お待ちください..."

#: pyanaconda/ui/gui/spokes/advstorage/nvdimm.glade.h:11
msgid "Warning: Existing data on reconfigured devices will be lost."
msgstr "警告: 再設定されたデバイスの既存のデータは失われます。"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:1
msgid "ADD zFCP STORAGE TARGET"
msgstr "zFCP ターゲットの追加"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:2
msgid ""
"To use zFCP disks, you must provide the device number, WWPN, and LUN "
"configured for the device."
msgstr ""
"zFCP ディスクを使用する場合は、そのデバイスに設定されているデバイス番号、"
"WWPN、LUN を入力する必要があります。"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:3
msgctxt "GUI|Advanced Storage|zFCP|Device Number"
msgid "_Device number:"
msgstr "デバイス番号(_D):"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:4
msgid "WWPN:"
msgstr "WWPN:"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:5
msgctxt "GUI|Advanced Storage|zFCP|Start Discovery"
msgid "_Start Discovery"
msgstr "探索を開始(_S)"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:6
msgid "Discovering zFCP devices.  This may take a moment..."
msgstr "zFCP デバイスを検索中です。少々お待ちください..."

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:8
msgid ""
"The following error occurred discovering zFCP devices.  Please double check "
"your configuration information and try again."
msgstr ""
"zFCP デバイスの探索中に、次のエラーが発生しました。設定情報をもう一度確認して"
"からやり直してください。"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:9
msgctxt "GUI|Advanced Storage|zFCP|Retry Discovery"
msgid "_Retry Discovery"
msgstr "探索を再試行(_R)"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade.h:10
msgid "LUN:"
msgstr "LUN:"

#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:1
msgid "SELECTED DISKS"
msgstr "選択したディスク"

#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:2
msgctxt "GUI|Selected Disks Dialog"
msgid "_Close"
msgstr "閉じる(_C)"

#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:3
msgid "Boot"
msgstr "ブート"

#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:4
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:7
msgid "Description"
msgstr "説明"

#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:7
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:10
msgid "Free"
msgstr "空き"

#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:9
msgctxt "GUI|Selected Disks Dialog"
msgid "_Remove"
msgstr "削除(_R)"

#: pyanaconda/ui/gui/spokes/lib/cart.glade.h:10
msgid "Disk summary goes here"
msgstr "ディスクの要約"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:1
msgctxt "GUI|Custom Partitioning|Confirm Delete Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:2
msgctxt "GUI|Custom Partitioning|Confirm Delete Dialog"
msgid "_Delete It"
msgstr "削除(_D)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:3
msgctxt "GUI|Custom Partitioning|Configure Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:4
msgctxt "GUI|Custom Partitioning|Configure Dialog"
msgid "_Select"
msgstr "選択(_S)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:5
msgid "CONFIGURE MOUNT POINT"
msgstr "マウントポイントの設定"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:6
msgid "Select one or more disks this device may reside on."
msgstr "このデバイスを存在させるディスクをひとつまたは複数選択してください。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:11
msgctxt "GUI|Custom Partitioning|Add Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:12
msgctxt "GUI|Custom Partitioning|Add Dialog"
msgid "_Add mount point"
msgstr "マウントポイントの追加(_A)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:13
msgctxt "GUI|Custom Partitioning|Add Dialog"
msgid "_Desired Capacity:"
msgstr "割り当てる領域(_D):"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:14
msgctxt "GUI|Custom Partitioning|Add Dialog"
msgid "Mount _Point:"
msgstr "マウントポイント(_P):"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:15
msgid "ADD A NEW MOUNT POINT"
msgstr "新規のマウントポイントの追加"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:16
msgid ""
"More customization options are available\n"
"after creating the mount point below."
msgstr ""
"以下にマウントポイントを作成した後に、他のカスタマイズ\n"
"オプションが利用できます。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:18
msgid ""
"That mount point is already in\n"
"use.  Try something else?"
msgstr ""
"そのマウントポイントは使用中です。\n"
"他を試しますか？"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:20
msgid "eg: \"20 GB\", \"500mb\" (minus the quotation marks)"
msgstr "例: \"20 GB\"、\"500 mb\" (引用符は除く)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:22
msgid "Single <span foreground=\"grey\">(No Redundancy, No Striping)</span>"
msgstr "シングル <span foreground=\"grey\">(非冗長, 非ストライピング)</span>"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:29
msgctxt "GUI|Custom Partitioning|Container Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:30
msgctxt "GUI|Custom Partitioning|Container Dialog"
msgid "_Save"
msgstr "保存(_S)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:31
msgid "CONFIGURE CONTAINER"
msgstr "コンテナーの設定"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:32
msgid ""
"Please create a name for this container and select at least one disk below."
msgstr ""
"このコンテナーの名前を作成し、以下から 1 つ以上のディスクを選択してください。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:33
msgctxt "GUI|Custom Partitioning|Container Dialog"
msgid "_Name:"
msgstr "名前(_N):"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:34
msgid "RAID Level:"
msgstr "RAID レベル:"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:35
msgid "Encrypt"
msgstr "暗号化"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:36
msgid "Please enter a valid name."
msgstr "有効な名前を入力してください。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:37
msgctxt "GUI|Custom Partitioning|Container Dialog"
msgid "Si_ze policy:"
msgstr "サイズポリシー(_Z):"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:38
msgid "Automatic"
msgstr "自動"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:39
msgid "As large as possible"
msgstr "できるだけ大きく"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade.h:40
msgid "Fixed"
msgstr "固定"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:1
msgid "UNFORMATTED DASDS"
msgstr "初期化されていない DASD"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:2
msgctxt "GUI|DASD Format Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:3
msgctxt "GUI|DASD Format Dialog"
msgid "_OK"
msgstr "OK(_O)"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:4
msgid ""
"The following unformatted or LDL DASDs have been detected on your system. "
"You can choose to format them now with dasdfmt or cancel to leave them "
"unformatted. Unformatted DASDs cannot be used during installation."
msgstr ""
"システムで、以下の未フォーマットまたは Linux ディスクレイアウトの DASD (直接"
"アクセス記憶装置) が検出されました。デバイスを選択して dasdfmt でフォーマット"
"化するか、取り消して未フォーマットのままにするか選択します。未フォーマットの "
"DASD はインストール中は使用できません。"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:5
msgid "Unformatted DASDs Detected"
msgstr "初期化されていない DASD が見つかりました"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:6
msgid ""
"<b>Warning</b>: All storage changes made using the installer will be lost "
"when you choose to format."
msgstr ""
"<b>警告:</b> インストーラーを使って行なった変更は、初期化を選択すると失われま"
"す。"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:7
msgctxt "GUI|DASD Format Dialog"
msgid "_Format with dasdfmt"
msgstr "dasdfmt で初期化する(_F)"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:8
msgid ""
"You may <a href=\"\">go back to the main menu</a> to complete other\n"
"installation options while formatting completes."
msgstr ""
"フォーマットが完了するまで、<a href=\"\">メインメニューに戻って</a>、\n"
"他のインストールオプションを完了することができます。"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:10
msgid "Disk formatting complete."
msgstr "ディスクの初期化が完了しました。"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade.h:11
#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:11
msgid ""
"Pressing 'OK' below will take you to the disk selection screen where you "
"will need to re-select your disks."
msgstr ""
"以下の「OK」を押すとディスクの選択画面に移動します。ここでディスクを再度選択"
"する必要があります。"

#: pyanaconda/ui/gui/spokes/lib/detailederror.glade.h:1
msgid "An unknown error occurred during installation.  Details are below."
msgstr "インストール中に不明なエラーが発生しました。詳細は以下にあります。"

#: pyanaconda/ui/gui/spokes/lib/entropy_dialog.glade.h:1
msgid ""
"The system needs better quality of random data, you can improve it by typing "
"randomly on keyboard and moving your mouse. The installation will continue "
"automatically regardless of random data quality when time runs out."
msgstr ""
"このシステムは質のよい乱数データを必要としています。キーボードをランダム入力"
"するか、マウスを動かすことで質のよい乱数を生成できます。十分な乱数データのエ"
"ントロピーが確保できたらインストールが自動的に続行されます。"

#: pyanaconda/ui/gui/spokes/lib/entropy_dialog.glade.h:2
msgid "Random data quality:"
msgstr "乱数データの品質"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade.h:1
msgctxt "GUI|Passphrase Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade.h:2
msgctxt "GUI|Passphrase Dialog"
msgid "_Save Passphrase"
msgstr "パスフレーズの保存(_S)"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade.h:3
msgid "DISK ENCRYPTION PASSPHRASE"
msgstr "ディスク暗号化用パスフレーズ"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade.h:4
msgid ""
"You have chosen to encrypt some of your data. You will need to create a "
"passphrase that you will use to access your data when you start your "
"computer."
msgstr ""
"データの一部を暗号化する選択をしました。コンピューターの起動時に、データへの"
"アクセスに使用するパスフレーズを作成する必要があります。"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade.h:5
msgctxt "GUI|Passphrase Dialog"
msgid "_Passphrase:"
msgstr "パスフレーズ(_P):"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade.h:6
msgctxt "GUI|Passphrase Dialog"
msgid "Con_firm:"
msgstr "確認(_F):"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade.h:8
msgid ""
"Warning: You won't be able to switch between keyboard layouts (from the "
"default one) when you decrypt your disks after install."
msgstr ""
"警告: インストール後のディスク復号時は、キーボードレイアウトを切り替えられま"
"せん (デフォルトのものを使用します)。"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:1
msgid "RESCAN DISKS"
msgstr "ディスクの再スキャン"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:2
msgctxt "GUI|Refresh Dialog|Rescan"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:3
msgctxt "GUI|Refresh Dialog|Rescan"
msgid "_OK"
msgstr "OK(_O)"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:4
msgid ""
"You can remove or insert additional disks at this time and press 'Rescan "
"Disks' below for the changes to take effect."
msgstr ""
"ここで追加ディスクの削除または挿入を行ってから以下の「ディスクの再スキャン」"
"を押すと、その変更を反映させることができます。"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:5
msgid ""
"<b>Warning:</b> All storage changes made using the installer will be lost "
"when you press 'Rescan Disks'."
msgstr ""
"<b>警告:</b> インストーラーを使って行なった変更はすべて「ディスクの再スキャ"
"ン」を押すと失われます。"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:6
msgctxt "GUI|Refresh Dialog|Rescan"
msgid "_Rescan Disks"
msgstr "ディスクの再スキャン(_R)"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:7
msgid "Scanning disks.  This may take a moment..."
msgstr "ディスクのスキャン中です。少々お待ちください..."

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:8
msgid ""
"You may <a href=\"\">go back to the main menu</a> to complete other\n"
"installation options while this scan completes."
msgstr ""
"スキャン中、他のインストールオプションを完了するため <a href=\"\">メインメ"
"ニューに戻る</a> \n"
"ことができます。"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade.h:10
msgid "Disk rescan complete."
msgstr "ディスクの再スキャンが完了しました。"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:1
msgctxt "GUI|Reclaim Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:2
msgctxt "GUI|Reclaim Dialog"
msgid "_Reclaim space"
msgstr "領域の再利用(_R)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:3
msgid "RECLAIM DISK SPACE"
msgstr "ディスク領域の確保"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:4
msgid "Description goes here."
msgstr "説明。"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:7
msgid "File System"
msgstr "ファイルシステム"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:8
msgid "Reclaimable Space"
msgstr "確保可能な領域"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:9
#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:6
msgid "Action"
msgstr "アクション"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:10
msgctxt "GUI|Reclaim Dialog"
msgid "_Preserve"
msgstr "保持(_P)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:11
msgctxt "GUI|Reclaim Dialog"
msgid "_Delete"
msgstr "削除(_D)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade.h:12
msgctxt "GUI|Reclaim Dialog"
msgid "_Shrink"
msgstr "縮小(_S)"

#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:1
msgid "SUMMARY OF CHANGES"
msgstr "変更の概要"

#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:2
msgctxt "GUI|Summary Dialog"
msgid "_Cancel & Return to Custom Partitioning"
msgstr "取り消して手動パーティション設定に戻る(_C)"

#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:3
msgctxt "GUI|Summary Dialog"
msgid "_Accept Changes"
msgstr "変更を許可する(_A)"

#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:4
msgid ""
"Your customizations will result in the following changes taking effect after "
"you return to the main menu and begin installation:"
msgstr ""
"このパーティション設定により次の変更が行われます。変更の適用は、メインメ"
"ニューに戻ってインストールを開始した後に行われます。"

#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:5
msgid "Order"
msgstr "順序"

#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:8
msgid "Device Name"
msgstr "デバイス名"

#: pyanaconda/ui/gui/spokes/lib/summary.glade.h:9
msgid "Mount point"
msgstr "マウントポイント"

#: pyanaconda/ui/gui/main.glade.h:3
msgctxt "GUI|Main"
msgid "_No"
msgstr "いいえ(_N)"

#: pyanaconda/ui/gui/main.glade.h:4
msgctxt "GUI|Main"
msgid "_Yes"
msgstr "はい(_Y)"

#: pyanaconda/ui/gui/main.glade.h:5
msgid ""
"Are you sure you wish to quit the\n"
"installation process?"
msgstr ""
"インストールプロセスを本当に\n"
"終了したいですか？"

#: pyanaconda/ui/gui/main.glade.h:7
msgid "Quit"
msgstr "終了"

#: pyanaconda/ui/gui/hubs/summary.glade.h:1
msgid "INSTALLATION SUMMARY"
msgstr "インストールの概要"

#: pyanaconda/ui/gui/hubs/summary.glade.h:2
msgctxt "GUI|Summary"
msgid "_Quit"
msgstr "終了 (_Q)"

#: pyanaconda/ui/gui/hubs/summary.glade.h:3
msgctxt "GUI|Summary"
msgid "_Begin Installation"
msgstr "インストールの開始(_B)"

#: pyanaconda/ui/gui/hubs/summary.glade.h:4
msgid "We won't touch your disks until you click 'Begin Installation'."
msgstr ""
"「インストールの開始」をクリックするまで、ディスクに変更は行われません。"

#: pyanaconda/ui/gui/hubs/progress.glade.h:1
msgid "CONFIGURATION"
msgstr "設定"

#: pyanaconda/ui/gui/hubs/progress.glade.h:2
msgid "Preparing to install"
msgstr "インストールの準備中"

#: pyanaconda/ui/gui/hubs/progress.glade.h:3
msgctxt "GUI|Progress"
msgid "_Finish configuration"
msgstr "設定完了(_F)"

#: pyanaconda/ui/gui/hubs/progress.glade.h:4
msgctxt "GUI|Progress"
msgid "_Reboot"
msgstr "再起動(_R)"

#: data/liveinst/liveinst.desktop.in.h:1
msgid "Install to Hard Drive"
msgstr "ハードディスクへインストール"

#: data/liveinst/liveinst.desktop.in.h:2
msgid "Install"
msgstr "インストール"

#: data/liveinst/liveinst.desktop.in.h:3
msgid "Install the live CD to your hard disk"
msgstr "LiveCD からハードディスクへインストール"

#: /home/rvykydal/anaconda/data/liveinst/console.apps/liveinst:5
msgid "Starting Install to Hard Drive"
msgstr "ハードディスクへのインストールを開始します"

#: data/liveinst/gnome/fedora-welcome.desktop.in.h:1
#: data/liveinst/gnome/fedora-welcome:65
msgid "Welcome to Fedora"
msgstr "Fedora へようこそ"

#: anaconda:490
#, python-format
msgid ""
"%(product_name)s requires %(needed_ram)s MB of memory to install, but you "
"only have %(total_ram)s MB on this machine.\n"
msgstr ""
"%(product_name)s をインストールするには最低 %(needed_ram)s MB のメモリーが必要ですが、このシステムには "
"%(total_ram)s MB しかありません。\n"

#: anaconda:492
#, python-format
msgid ""
"The %(product_name)s graphical installer requires %(needed_ram)s MB of "
"memory, but you only have %(total_ram)s MB\n"
"."
msgstr ""
"%(product_name)s グラフィカルインストーラーには %(needed_ram)s MB のメモリー"
"が必要ですが、%(total_ram)s MB しかありません。\n"
" "

#: anaconda:495
msgid ""
"\n"
"Press <return> to reboot your system.\n"
msgstr ""
"\n"
"<return> キーを押すと、システムを再起動します。\n"

#: anaconda:497
msgid "Not enough RAM"
msgstr "RAM が足りません"

#: anaconda:498
msgid ""
" Try the text mode installer by running:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" from a root terminal."
msgstr ""
" 次のとおり実行してテキストモードインストーラーを試してください:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
"なお、この操作は root のターミナルで実行します。"

#: anaconda:501
msgid " Starting text mode."
msgstr " テキストモードを開始しています。"

#: anaconda:537
msgid "The installation cannot continue and the system will be rebooted"
msgstr "インストールを続行できません。システムを再起動します"

#: anaconda:664
msgid "DISPLAY variable not set. Starting text mode."
msgstr "DISPLAY 変数がセットされていません。テキストモードで起動します。"

#: anaconda:672
msgid "Graphical installation is not available. Starting text mode."
msgstr "グラフィカルインストールは使用できません。テキストモードで起動します。"

#: anaconda:680
msgid ""
"Text mode provides a limited set of installation options. It does not offer "
"custom partitioning for full control over the disk layout. Would you like to "
"use VNC mode instead?"
msgstr ""
"テキストモードによるインストールは限定的なインストールオプションしか提供され"
"ず、パーティション設定の細かなカスタマイズが行えません。代わりに VNC モード"
"を 使用しますか？"

#: anaconda:776
#, python-format
msgid "Please ssh install@%s to begin the install."
msgstr "インストールを開始するには、ssh install@%s を実行します。"

#: anaconda:778
msgid "Please ssh install@<host> to continue installation."
msgstr "インストールを継続するには、ssh install@<host> を実行してください。"

#: data/liveinst/gnome/fedora-welcome:94
msgid "Try Fedora"
msgstr "Fedora を試す"

#: data/liveinst/gnome/fedora-welcome:110
msgid ""
"You are currently running Fedora from live media.\n"
"You can install Fedora now, or choose \"Install to Hard Drive\" in the "
"Activities Overview at any later time."
msgstr ""
"現在、Live メディアから Fedora を稼働しています。\n"
"ここで Fedora をインストールできます。または後で、アクティビティオーバー"
"ビューで「ハードドライブへインストール」を選択することもできます。"

#: data/liveinst/gnome/fedora-welcome:128
msgid ""
"You can choose \"Install to Hard Drive\"\n"
"in the Activities Overview at any later time."
msgstr ""
"後で「アクティビティの概要」から 「ハードディスクへ\n"
"インストール」を選択することができます。"

#: data/liveinst/gnome/fedora-welcome:131
msgid "Close"
msgstr "閉じる"
